class PostsController < ApplicationController
  @posts: Post::ActiveRecord_Relation?
  @comments: Comment::ActiveRecord_Relation?
  @post: (Post | (Post & Post::Validated))?
  @test: (Post & Post::Validated)?

  include FilterConfiguration

  def index: () -> void
  def show: () -> void
  def new: () -> void
  def create: () -> void
  def update: () -> void
  def destroy: () -> void
  def publish: () -> void

  private

  def set_post: () -> (Post & Post::Validated)
  def set_test: () -> (Post & Post::Validated)?
  def post_params: () -> untyped
end
