class PostsController < ApplicationController
  @posts: Post::ActiveRecord_Relation
  @comments: Comment::ActiveRecord_Relation
  @post: Post
  @test: Post?
  include FilterConfiguration
  def index: () -> void
  def show: () -> void
  def new: () -> void
  def create: () -> void
  def update: () -> void
  def destroy: () -> void
  def publish: () -> void

  private

  def set_post: () -> Post
  def set_test: () -> Post?
  def post_params: () -> untyped
end
