# frozen_string_literal: true
#
# GENERATED by RbsInfer::Extensions::Rails::BelongsToDefaultGenerator.
# The example.rb-shaped expansion of `belongs_to ..., default:` that
# Steep type-checks; diagnostics map back via .steep_belongs_to_default.yml.
# Regenerated on every run; do not edit.

class RbsInferBelongsToDefaultPost
  def user; raise; end
end

class RbsInferBelongsToDefaultUser
end

class RbsInferBelongsToDefaultAssignment
  attr_accessor :post, :owner
  def save; run_before_validation_callbacks; end
  def run_before_validation_callbacks; run_belongs_to_default_callbacks; end
  def run_belongs_to_default_callbacks
    self.owner = post.user
  end
end

class RbsInferBelongsToDefaultRunner
  def self.witness_assignment
    record = RbsInferBelongsToDefaultAssignment.new
    record.post = RbsInferBelongsToDefaultPost.new
    record.owner = RbsInferBelongsToDefaultUser.new
  end
  def self.site_1
    record = RbsInferBelongsToDefaultAssignment.new
    owner = RbsInferBelongsToDefaultPost.new
    record.post = owner
    record.save
  end
end
