# ⚠️  Generated by rbs_infer for debugging — NEVER loaded at runtime.
#     Expanded view of app/models/article.rb (macros desugared into pseudo-code).
#     Regenerated on every run; do not edit.
class Article < ApplicationRecord
  # The fixture for the ActionText generator, which writes exactly one file:
  # `has_rich_text` as ActionText wrote it. Nothing generates the accessors —
  # the macro defines them by `class_eval`ing a string, and the string is a
  # literal once this call site fixes `name`, so the checker folds it and
  # `Project::StringEvalMacroExpander` places what it folded HERE.
  has_rich_text :content

  # `store_if_blank: false` is the branch Rails writes a different writer body
  # for, and the call above takes the default it omits. Narrowing decides both,
  # so nothing in the tooling knows the option exists.
  has_rich_text :summary, store_if_blank: false
end

class Article
  def content
    rich_text_content || build_rich_text_content
  end

  def content?
    rich_text_content.present?
  end

  def content=(body)
    self.content.body = body
  end

  def summary
    rich_text_summary || build_rich_text_summary
  end

  def summary?
    rich_text_summary.present?
  end

  def summary=(body)
    if body.present?
      self.summary.body = body
    else
      if summary?
        self.summary.body = body
        self.summary.mark_for_destruction
      end
    end
  end
end
