# ⚠️  Generated by rbs_infer for debugging — NEVER loaded at runtime.
#     Expanded view of app/models/article.rb (macros desugared into pseudo-code).
#     Regenerated on every run; do not edit.
class Article < ApplicationRecord
  # The fixture for the ActionText runtime generator. `has_rich_text` writes
  # its accessors with `class_eval` on a heredoc string, so nothing static
  # reads them; the generated pseudo-code under
  # `sig/generated/steep_actiontext_runtime/` is what makes `article.content`
  # a method the checker can see.
  has_rich_text :content

  # `store_if_blank: false` is the branch Rails writes a DIFFERENT writer body
  # for — the generator picks it by reading the macro's own `if`, so this pins
  # that the branch is followed rather than assumed.
  has_rich_text :summary, store_if_blank: false
end

class Article
  def content
    rich_text_content || build_rich_text_content
  end

  def content?
    rich_text_content.present?
  end

  def content=(body)
    self.content.body = body
  end

  def summary
    rich_text_summary || build_rich_text_summary
  end

  def summary?
    rich_text_summary.present?
  end

  def summary=(body)
    if body.present?
      self.summary.body = body
    else
      if summary?
        self.summary.body = body
        self.summary.mark_for_destruction
      end
    end
  end
end
