# ⚠️  Generated by rbs_infer for debugging — NEVER loaded at runtime.
#     Expanded view of app/models/current.rb (macros desugared into pseudo-code).
#     Regenerated on every run; do not edit.
# frozen_string_literal: true

# Fixture for felixefelip/rbs_infer#19: the type of `attribute :user` is
# inferred from assignment call-sites in other files
# (`Current.user = @post.user` in PostsController#publish and
# `Current.with(user: ...)` in ProfileFormatterJob), unlocking the type
# of the derived method `self.author_full_name`.
class Current < ActiveSupport::CurrentAttributes
  def user; @user; end
  def user=(value); @user = value; end
  def self.user; @user; end
  def self.user=(value); @user = value; end
  def self.set(user: nil, &block); @user = user; block.call; end
  def self.with(user: nil, &block); @user = user; block.call; end

  # `&.` because the attribute is honestly nilable (per-request reset);
  # inference propagates the safe-nav nil → `String?`.
  def self.author_full_name
    user&.full_name
  end
end
