# ⚠️  Generated by rbs_infer for debugging — NEVER loaded at runtime.
#     Expanded view of app/models/example28.rb (macros desugared into pseudo-code).
#     Regenerated on every run; do not edit.
class Example28
  module Foo
    attr_reader :bazingado_block

    def bazinga(module_included)
      class_eval(&module_included.bazingado_block)
    end

    def bazingado(&block)
      @bazingado_block = block
    end
  end

  module Baz
    extend Example28::Foo

    bazingado do
      def greet
        "Hello, world!"
      end

      def age_after_a_decade
        age + 10
      end
    end
  end

  class Bar
    extend Example28::Foo

    bazinga(Example28::Baz)

    def age
      42
    end

    def call_test
      greet
    end
  end
end

class Example28::Bar
  def greet
    "Hello, world!"
  end

  def age_after_a_decade
    age + 10
  end
end
