# ⚠️  Generated by rbs_infer for debugging — NEVER loaded at runtime.
#     Expanded view of app/models/example59.rb (macros desugared into pseudo-code).
#     Regenerated on every run; do not edit.
# The host: `human_name` reaches it through the SINGLETON ancestry — the
# `extend ::Example59::Naming::ClassMethods` the concern's expansion emits —
# which no name in the caller spells and only the RBS knows.
class Example59
  include Naming
end

class Example59
  extend Example59::Naming::ClassMethods
end
