# ⚠️  Generated by rbs_infer for debugging — NEVER loaded at runtime.
#     Expanded view of app/models/example35.rb (macros desugared into pseudo-code).
#     Regenerated on every run; do not edit.
class Example35
  class Foo
    def self.bazinga(module_included)
      module_included.bazingado(self)
    end

    def self.bazingado(base=nil, &block)
      if base.nil?
        @_bazingado_block = block
      else
        base.class_eval(&@_bazingado_block) if @_bazingado_block
      end
    end
  end

  class Baz < Example35::Foo
    bazingado do
      def age
        31
      end
    end
  end

  class Bar < Baz
    bazinga(Example35::Baz)

    def call_age
      age + 10
    end
  end
end

class Example35::Bar
  def age
    31
  end
end
