# ⚠️  Generated by rbs_infer for debugging — NEVER loaded at runtime.
#     Expanded view of app/models/example38.rb (macros desugared into pseudo-code).
#     Regenerated on every run; do not edit.
class Example38
  module Foo
    def bazinga(*modules)
      modules.reverse_each do |mod|
        mod.send(:bazingado, self)
      end
    end

    private

    def bazingado(base=nil, &block)
      if base.nil?
        @_bazingado_block = block
      else
        base.class_eval(&@_bazingado_block) if @_bazingado_block
      end
    end
  end

  class Baz
    extend Example38::Foo

    bazingado do
      def age
        31
      end
    end
  end

  class BazOther
    extend Example38::Foo

    bazingado do
      def name
        "John Doe"
      end
    end
  end

  class Bar
    extend Example38::Foo

    bazinga(Example38::Baz, Example38::BazOther)

    def call_age
      age + 10
    end
  end
end

class Example38::Bar
      def age
        31
      end
end

class Example38::Bar
      def name
        "John Doe"
      end
end
