# ⚠️  Generated by rbs_infer for debugging — NEVER loaded at runtime.
#     Expanded view of app/models/example30.rb (macros desugared into pseudo-code).
#     Regenerated on every run; do not edit.
module Example30
  class Foo
    def name
      "Foo"
    end

    def build_age
      self.class.class_eval do
        def age
          25
        end
      end
    end

    def call_age
      age # no method error

      build_age

      age + 10 # => works -> 35
    end
  end
end

class Example30::Foo::AfterBuildAge
        def age
          25
        end
end
