# ⚠️  Generated by rbs_infer for debugging — NEVER loaded at runtime.
#     Expanded view of app/models/example57.rb (macros desugared into pseudo-code).
#     Regenerated on every run; do not edit.
# A concern included by the name it is WRITTEN with, not by its full path.
#
# `include Fields` inside `class Example57` reaches `Example57::Fields` — the
# ordinary way an app writes a nested concern, and the way the app this was
# found in writes `Filter`'s. The replay pass asked the project for `Fields` as
# spelled; nothing declares that, so the concern's file was never opened, its
# shapes were never absorbed, and the `def` in its `included do` stayed on the
# concern instead of moving onto the includer (felixefelip/rbs_infer#289).
#
# A name is not a constant: which one `Fields` means is decided by what the
# PROJECT declares, exactly as `resolve_constant` decides it from what the file
# declares.
class Example57
  include Fields

  def window_size
    creation_window + 1
  end

  # The control for the lookup ORDER. `Example57Windowed` has no nested
  # candidate, so the walk has to run out of prefixes and land on the top-level
  # module — the answer the pass gave before there was a walk at all, and the
  # one every constant that lives outside the app's own sources still needs.
  class Inner
    include Example57Windowed

    def doubled
      window_days * 2
    end
  end
end

class Example57
  def creation_window
    7
  end
end

class Example57::Inner
  def window_days
    30
  end
end
