# ⚠️  Generated by rbs_infer for debugging — NEVER loaded at runtime.
#     Expanded view of app/models/example44.rb (macros desugared into pseudo-code).
#     Regenerated on every run; do not edit.
class Example44
  module Foo
    def included(base=nil, &block)
      if base.nil?
        @_bazingado_block = block
      else
        base.class_eval(&@_bazingado_block) if @_bazingado_block
      end
    end
  end

  module Baz
    extend Example44::Foo

    included do
      def age
        31
      end
    end
  end

  class Bar
    extend Example44::Foo

    include(Example44::Baz)

    def call_age
      age + 10
    end
  end

  class BarOther
    extend Example44::Foo

    include(Example44::Baz)

    def call_age
      age + 20
    end
  end
end

class Example44::Bar
  def age
    31
  end
end

class Example44::BarOther
  def age
    31
  end
end
