# ⚠️  Generated by rbs_infer for debugging — NEVER loaded at runtime.
#     Expanded view of app/models/example54.rb (macros desugared into pseudo-code).
#     Regenerated on every run; do not edit.
class Example54
  class Bar
    include Example54::Baz

    def self.call_age
      age + 10
    end
  end
end

class Example54::Bar
  extend Example54::Baz::BananaMethods
end
