# ⚠️  Generated by rbs_infer for debugging — NEVER loaded at runtime.
#     Expanded view of app/models/example55.rb (macros desugared into pseudo-code).
#     Regenerated on every run; do not edit.
class Example55
  class Bar
    include Example55::Baz

    def self.call_age
      age + 10
    end
  end
end

class Example55::Bar
  extend Example55::Baz::BananaMethods
end
