# ⚠️  Generated by rbs_infer for debugging — NEVER loaded at runtime.
#     Expanded view of app/models/example34.rb (macros desugared into pseudo-code).
#     Regenerated on every run; do not edit.
class Example34
  module Foo
    def include(*modules)
      modules.reverse_each do |mod|
        mod.included(self)
      end
    end

    def included(base=nil, &block)
      if base.nil?
        @_bazingado_block = block
      else
        base.class_eval(&@_bazingado_block) if @_bazingado_block
      end
    end
  end

  module Baz
    extend Example34::Foo

    included do
      def age
        31
      end
    end
  end

  class Bar
    extend Example34::Foo

    include(Example34::Baz)
  end
end

class Example34::Bar
  def age
    31
  end
end
