# ⚠️  Generated by rbs_infer for debugging — NEVER loaded at runtime.
#     Expanded view of app/models/example46.rb (macros desugared into pseudo-code).
#     Regenerated on every run; do not edit.
class Example46
  module Baz
    module BananaWritten
    end

    module BananaDynamic
    end
  end

  class Bar
    def written
      Example46::Baz::BananaWritten
    end

    def dynamic
      Example46::Baz::BananaDynamic
    end
  end
end
