# ⚠️  Generated by rbs_infer for debugging — NEVER loaded at runtime.
#     Expanded view of app/models/example33.rb (macros desugared into pseudo-code).
#     Regenerated on every run; do not edit.
class Example33
  module Foo
    def bazinga(module_included)
      module_included.bazingado(self)
    end

    def bazingado(base=nil, &block)
      if base.nil?
        @_bazingado_block = block
      else
        base.class_eval(&@_bazingado_block) if @_bazingado_block
      end
    end
  end

  module Baz
    extend Example33::Foo

    bazingado do
      def age
        31
      end
    end
  end

  class Bar
    extend Example33::Foo

    bazinga(Example33::Baz)
  end

  module BazOther
    extend Example33::Foo

    bazingado do
      def name_upcase
        name.upcase
      end
    end
  end

  class BarOther
    extend Example33::Foo

    bazinga(Example33::BazOther)

    def name
      "John Doe"
    end

    def call_name_upcase
      name_upcase
    end
  end
end

class Example33::Bar
      def age
        31
      end
end

class Example33::BarOther
      def name_upcase
        name.upcase
      end
end
