# ⚠️  Generated by rbs_infer for debugging — NEVER loaded at runtime.
#     Expanded view of app/models/included_hook_second.rb (macros desugared into pseudo-code).
#     Regenerated on every run; do not edit.
# frozen_string_literal: true

# The second host, which is what makes the hook block ambiguous: one block, two `base`s.
class IncludedHookSecond
  include IncludedHook::Shared
end

class IncludedHookSecond
  def from_shared
    1
  end
end
