# ⚠️  Generated by rbs_infer for debugging — NEVER loaded at runtime.
#     Expanded view of app/models/user.rb (macros desugared into pseudo-code).
#     Regenerated on every run; do not edit.
# frozen_string_literal: true

class User < ApplicationRecord
  include User::Recoverable
  include User::Displayable
  # Contributes `has_many :notifications` — declared only in the concern's
  # `included do`, never here (felixefelip/rbs_infer#139).
  include User::Notifiable

  mount_uploader :avatar, AvatarUploader

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true

  scope :active, -> { where(active: true) }
  scope :by_name, ->(name) { where(name: name) }

  attr_accessor :session_token

  def full_name
    "#{first_name} #{last_name}"
  end

  def active?
    active
  end

  # The Fizzy shape of felixefelip/rbs_infer#185: a model class method called on
  # a has_many collection proxy (`Current.user.filters.from_params …`).
  def known_post_tag?(name)
    posts.known_tag?(name)
  end

  def posts_count
    posts.count
  end

  def recent_posts(limit = 5)
    posts.order(created_at: :desc).limit(limit)
  end

  # Called from ONE place: dashboard/show.html.erb, on a `Current.user` receiver,
  # inside `@recent_posts.each do |post|`. Both halves of that call site used to be
  # invisible (felixefelip/rbs_infer#131) — the template never spells `User`, so it
  # was not a candidate caller, and `Current.user` is nilable, so its type never
  # matched the target. `post` is typed here only because both were fixed.
  def posts_titled_like(post)
    posts.where(title: post.title).count
  end

  # The same deref as in `User::Notifiable`, but from the HOST body — the getter
  # has to be on `User`, not on the concern, which is where the runtime puts it.
  def unread_notifications_count
    notifications.unread.count
  end
end

class User
  scope :inactive, -> { where(active: false) }
end

class User
  has_many :notifications, dependent: :destroy

  # Declared in a concern's `included do`, which is where Rails apps put it (it
  # is where fizzy's `store_accessor :fields, …` lives) and the half only
  # `ConcernResolver` can see: reading `user.rb` alone finds no macro, so the
  # pair has to be spliced onto the INCLUDER — the module is `User`'s, not the
  # concern's, because the keys belong to whoever includes it.
  store_accessor :preferences, :digest_hour
end
