# ⚠️  Generated by rbs_infer for debugging — NEVER loaded at runtime.
#     Expanded view of app/models/zz_args.rb (macros desugared into pseudo-code).
#     Regenerated on every run; do not edit.
class ZzArgs
end

class ZzArgs
  def positional(value)
    value.to_s
  end

  def with_default(value, limit = 10)
    "#{value}:#{limit}"
  end

  def keywords(name:, tags: [])
    "#{name}-#{tags.size}"
  end

  def splat(*values, **opts, &blk)
    values.size + opts.size
  end
end

class ZzArgsCaller
  def call
    t = ZzArgs.new
    t.positional(42)
    t.with_default("a", 3)
    t.keywords(name: "n", tags: ["x"])
    t.splat(1, 2, k: true)
  end
end
