# frozen_string_literal: true

require "prism"

module RbsInfer
  module Extensions
    module Rails
      module Controllers
        # Transcribes the FRAMEWORK'S OWN SOURCE into the controller-runtime
        # sidecar (felixefelip/rbs_infer#144).
        #
        # A fact can be true because of what a gem does with a block, and no
        # amount of reading the application will show it. `Current.identity =`
        # inside
        #
        #   authenticate_or_request_with_http_token do |token|
        #     Current.identity = identity if identity = ...
        #   end
        #
        # holds on every exit that did not render a 401 — because Rails returns
        # the block's value when it is truthy and renders otherwise. That is
        # ordinary Ruby, three methods deep in actionpack; it is invisible only
        # because a gem is described by RBS, which carries types and not flow.
        #
        # So the pseudo-code here is not a model of what Rails "effectively
        # does": it IS the gem's code, sliced from the installed version at
        # generation time. The generators run inside the app with Rails loaded,
        # so `source_location` points at the real file, and the transcription
        # tracks whatever version is installed rather than drifting from it.
        #
        # What this buys is nothing on its own — following it needs the
        # inference to carry a block's return through a delegation chain. It is
        # stage 1 of #144, and it exists so stages 2 and 3 have real code to be
        # right about instead of a hand-written summary to agree with.
        class FrameworkSourceTranscriber
          # Where a transcription may land is decided by the collection: RBS
          # refuses two declarations of one method on one owner, and the
          # collection already declares this family. So each seed names an owner
          # DIFFERENT from the declaring one, chosen so resolution still favours
          # the transcription:
          #
          #   * the two controller methods are declared on
          #     `HttpAuthentication::Token::ControllerMethods`, a module
          #     `ActionController::Base` includes — and a class's own method wins
          #     over an included module's;
          #   * `Token.authenticate` is declared as an INSTANCE method of `Token`,
          #     reachable because `Token` extends itself — and a singleton method
          #     defined directly wins over one obtained by `extend`.
          #
          # Both were measured against Steep's own resolution before being relied
          # on. `as_singleton` rewrites the `def` line (`def authenticate` ->
          # `def self.authenticate`) and nothing else: the body stays verbatim.
          Seed = Struct.new(:receiver, :method_name, :singleton, :namespace, :as_singleton, keyword_init: true)

          SEEDS = [
            Seed.new(
              receiver: "ActionController::Base",
              method_name: :authenticate_or_request_with_http_token,
              singleton: false,
              namespace: ["ActionController", "Base"],
              as_singleton: false
            ),
            Seed.new(
              receiver: "ActionController::Base",
              method_name: :authenticate_with_http_token,
              singleton: false,
              namespace: ["ActionController", "Base"],
              as_singleton: false
            ),
            Seed.new(
              receiver: "ActionController::HttpAuthentication::Token",
              method_name: :authenticate,
              singleton: true,
              namespace: ["ActionController", "HttpAuthentication", "Token"],
              as_singleton: true
            )
          ].freeze

          FILENAME = "action_controller_framework.rb"

          # Returns the file's source, or nil when nothing could be transcribed —
          # a Rails version that renamed or removed a seed, or an environment
          # where the constant is not loaded. Missing seeds are SKIPPED rather
          # than raised on: a generator that dies on a framework upgrade is worse
          # than one that emits less.
          def build
            blocks = SEEDS.group_by(&:namespace).filter_map do |namespace, seeds|
              defs = seeds.filter_map { |seed| transcribe(seed) }
              next if defs.empty?

              wrap(namespace, defs)
            end
            return nil if blocks.empty?

            <<~HEADER + blocks.join("\n")
              # frozen_string_literal: true
              #
              # GENERATED by #{self.class.name}.
              # Regenerated on every run; do not edit.
              #
              # The framework's own source, transcribed from the installed gem so
              # the checker can follow the flow an RBS signature cannot express
              # (felixefelip/rbs_infer#144). Bodies are verbatim; only a `def`
              # line may be rewritten, to place the method on an owner that does
              # not collide with the signature the RBS collection already ships.

            HEADER
          end

          private

          # The method's source, dedented, or nil when it cannot be reached.
          def transcribe(seed)
            method = resolve(seed) or return nil
            file, line = method.source_location
            return nil unless file && line && File.file?(file)

            node = def_node_at(file, line) or return nil
            source = dedent(node.slice, node.location.start_column)
            seed.as_singleton ? singleton_def(source, seed.method_name) : source
          end

          def resolve(seed)
            receiver = Object.const_get(seed.receiver)
            seed.singleton ? receiver.method(seed.method_name) : receiver.instance_method(seed.method_name)
          rescue NameError
            nil
          end

          # The `def` whose own line is `line`. Located by position rather than by
          # name so a file defining the same name twice cannot be confused.
          def def_node_at(file, line)
            result = Prism.parse_file(file)
            return nil unless result.success?

            RbsInfer::Analyzer.find_all_nodes(result.value) { |n| n.is_a?(Prism::DefNode) }
                              .find { |n| n.location.start_line == line }
          end

          # `def authenticate(...)` -> `def self.authenticate(...)`, first line
          # only. The method is reached as `Token.authenticate` because the module
          # extends itself; declaring it as the singleton is what makes the
          # transcription the one a call resolves to.
          def singleton_def(source, method_name)
            source.sub(/\Adef #{Regexp.escape(method_name.to_s)}\b/, "def self.#{method_name}")
          end

          # `node.slice` starts AT the `def` keyword, so the first line carries no
          # indentation while the rest keep the file's. The margin to strip is
          # therefore the def's own column, not the minimum across lines — which
          # is zero, and left every body at the gem's absolute indentation.
          def dedent(source, margin)
            first, *rest = source.lines
            ([first] + rest.map { |line| line.strip.empty? ? line : line.sub(/\A {0,#{margin}}/, "") }).join
          end

          # Nests the defs under `namespace`, `class` for a constant that is one
          # and `module` otherwise, so the reopen matches what is being reopened.
          def wrap(namespace, defs)
            body = defs.join("\n\n").rstrip
            depth = namespace.size

            lines = namespace.each_with_index.map { |segment, i| "#{'  ' * i}#{keyword_for(namespace[0..i])} #{segment}" }
            lines << body.lines.map { |l| l.strip.empty? ? l : "#{'  ' * depth}#{l}" }.join
            lines.concat((0...depth).to_a.reverse.map { |i| "#{'  ' * i}end" })
            "#{lines.join("\n")}\n"
          end

          def keyword_for(path)
            Object.const_get(path.join("::")).is_a?(Class) ? "class" : "module"
          rescue NameError
            "module"
          end
        end
      end
    end
  end
end
