# frozen_string_literal: true

require "prism"

module RbsInfer
  module Extensions
    module Rails
      module Controllers
        # Transcribes the FRAMEWORK'S OWN SOURCE into the controller-runtime
        # sidecar (felixefelip/rbs_infer#144).
        #
        # A fact can be true because of what a gem does with a block, and no
        # amount of reading the application will show it. `Current.identity =`
        # inside
        #
        #   authenticate_or_request_with_http_token do |token|
        #     Current.identity = identity if identity = ...
        #   end
        #
        # holds on every exit that did not render a 401 — because Rails returns
        # the block's value when it is truthy and renders otherwise. That is
        # ordinary Ruby, three methods deep in actionpack; it is invisible only
        # because a gem is described by RBS, which carries types and not flow.
        #
        # So the pseudo-code here is not a model of what Rails "effectively
        # does": it IS the gem's code, sliced from the installed version at
        # generation time. The generators run inside the app with Rails loaded,
        # so `source_location` points at the real file, and the transcription
        # tracks whatever version is installed rather than drifting from it.
        #
        # What this buys is nothing on its own — following it needs the
        # inference to carry a block's return through a delegation chain. It is
        # stage 1 of #144, and it exists so stages 2 and 3 have real code to be
        # right about instead of a hand-written summary to agree with.
        class FrameworkSourceTranscriber
          # A body is transcribed into ITS OWN OWNER, and the owner is read off
          # the method rather than chosen. The choice looked free and is not: a
          # body carries references that resolve by the lexical nesting of where
          # it was WRITTEN. `Token.authenticate(self, &login_procedure)` moved
          # into `ActionController::Base` stops resolving, because the nesting
          # there is `[Base, ActionController]` and no `ActionController::Token`
          # exists — Ruby raises the same NameError the checker reports.
          #
          # Keeping the owner means the transcription is verbatim, with no `def`
          # line rewritten, and it means the RBS collection must stop declaring
          # what is transcribed: RBS refuses two declarations of one method on
          # one owner, and now there is only one place the method can live.
          # Declarations have a free owner; bodies do not.
          Seed = Struct.new(:receiver, :method_name, keyword_init: true)

          SEEDS = [
            Seed.new(
              receiver: "ActionController::HttpAuthentication::Token::ControllerMethods",
              method_name: :authenticate_or_request_with_http_token
            ),
            Seed.new(
              receiver: "ActionController::HttpAuthentication::Token::ControllerMethods",
              method_name: :authenticate_with_http_token
            ),
            Seed.new(
              receiver: "ActionController::HttpAuthentication::Token",
              method_name: :authenticate
            )
          ].freeze

          FILENAME = "action_controller_framework.rb"

          # Returns the file's source, or nil when nothing could be transcribed —
          # a Rails version that renamed or removed a seed, or an environment
          # where the constant is not loaded. Missing seeds are SKIPPED rather
          # than raised on: a generator that dies on a framework upgrade is worse
          # than one that emits less.
          def build
            transcribed = SEEDS.filter_map { |seed| transcribe(seed) }
            blocks = transcribed.group_by(&:first).map { |namespace, pairs| wrap(namespace, pairs.map(&:last)) }
            return nil if blocks.empty?

            <<~HEADER + blocks.join("\n")
              # frozen_string_literal: true
              #
              # GENERATED by #{self.class.name}.
              # Regenerated on every run; do not edit.
              #
              # The framework's own source, transcribed from the installed gem so
              # the checker can follow the flow an RBS signature cannot express
              # (felixefelip/rbs_infer#144). Bodies are verbatim: the
              # bodies land in the owner they were written in, so their constant
              # references resolve by the same lexical nesting the gem relies on.

            HEADER
          end

          private

          # `[namespace, source]` for a seed, or nil when it cannot be reached.
          # The namespace is the method's OWNER, so the body lands back in the
          # nesting it was written in.
          def transcribe(seed)
            method = resolve(seed) or return nil
            owner = method.owner.name or return nil
            file, line = method.source_location
            return nil unless file && line && File.file?(file)

            node = def_node_at(file, line) or return nil
            [owner.split("::"), dedent(node.slice, node.location.start_column)]
          end

          def resolve(seed)
            Object.const_get(seed.receiver).instance_method(seed.method_name)
          rescue NameError
            nil
          end

          # The `def` whose own line is `line`. Located by position rather than by
          # name so a file defining the same name twice cannot be confused.
          def def_node_at(file, line)
            result = Prism.parse_file(file)
            return nil unless result.success?

            RbsInfer::Analyzer.find_all_nodes(result.value) { |n| n.is_a?(Prism::DefNode) }
                              .find { |n| n.location.start_line == line }
          end

          # `node.slice` starts AT the `def` keyword, so the first line carries no
          # indentation while the rest keep the file's. The margin to strip is
          # therefore the def's own column, not the minimum across lines — which
          # is zero, and left every body at the gem's absolute indentation.
          def dedent(source, margin)
            first, *rest = source.lines
            ([first] + rest.map { |line| line.strip.empty? ? line : line.sub(/\A {0,#{margin}}/, "") }).join
          end

          # Nests the defs under `namespace`, `class` for a constant that is one
          # and `module` otherwise, so the reopen matches what is being reopened.
          def wrap(namespace, defs)
            body = defs.join("\n\n").rstrip
            depth = namespace.size

            lines = namespace.each_with_index.map { |segment, i| "#{'  ' * i}#{keyword_for(namespace[0..i])} #{segment}" }
            lines << body.lines.map { |l| l.strip.empty? ? l : "#{'  ' * depth}#{l}" }.join
            lines.concat((0...depth).to_a.reverse.map { |i| "#{'  ' * i}end" })
            "#{lines.join("\n")}\n"
          end

          def keyword_for(path)
            Object.const_get(path.join("::")).is_a?(Class) ? "class" : "module"
          rescue NameError
            "module"
          end
        end
      end
    end
  end
end
