# frozen_string_literal: true

require "active_support/core_ext/string/inflections"
require_relative "callback_chain_scanner"

module RbsInfer
  module Extensions
    module Rails
      module Controllers
        # Builds the controller-runtime pseudo-code (felixefelip/rbs_infer#81):
        # plain Ruby that models what Rails does at request time, so the Steep
        # fork can prove — by reading it — what an action may assume on entry.
        #
        # Two kinds of file, both plain `.rb`:
        #
        #   * the FRAMEWORK reopen (`action_controller_base.rb`) — gives
        #     `redirect_to`/`render`/`head` a body that records the halt, and
        #     `performed?` (Rails' own halt predicate) a body that reads it back.
        #     This is the only place the "a callback can abort the chain"
        #     semantics lives.
        #   * one CONTROLLER reopen per controller — a private
        #     `__rbs_infer__run_<action>` per action, holding that action's
        #     effective before_action chain inlined, each link followed by the
        #     halt check, and the action call last.
        #
        # No `.rbs` is emitted: the RBS for these bodies is the analyzer's job
        # (`rbs_infer sig/ --output`), exactly as for any other source. Emitting
        # it here too would declare the same methods twice and RBS rejects that
        # (`Non-overloading method definition of `performed?` … cannot be
        # duplicated`). Everything the pseudo-code declares must therefore be
        # INFERRABLE FROM A BODY — which is why the opaque condition below has
        # one.
        #
        # The controller is REOPENED rather than wrapped in a `Runner` class for
        # two reasons: callbacks are private (an external caller could not invoke
        # them), and everything stays rooted at `self` — which is the shape the
        # Steep fork's contract machinery reasons about best, so ivar narrowing
        # (`@post` set by `set_post`, read by the action) needs no new machinery.
        #
        # The chain is inlined per action instead of factored into a shared
        # `__rbs_infer__run_before_actions_<action>`: facts do not cross a call
        # boundary in the fork today, and every extra hop is machinery someone
        # has to build. Duplication in generated code is free.
        class PseudoCodeBuilder
          # One emitted file: `filename` within the sidecar dir, `source` its
          # full contents.
          FileEntry = Struct.new(:filename, :source, keyword_init: true)

          # Rails halts the before_action chain with its own predicate:
          #
          #   terminator: ->(controller, result_lambda) {
          #     result_lambda.call; controller.performed?
          #   }                       (abstract_controller/callbacks.rb)
          #
          # so `return if performed?` after each link is a transcription of the
          # runtime terminator, not an approximation of it.
          HALTED = "performed?"
          UNKNOWN_CONDITION_METHOD = "__rbs_infer__unknown_condition?"

          HEADER = <<~RUBY
            # frozen_string_literal: true
            #
            # GENERATED by RbsInfer::Extensions::Rails::Controllers::RuntimeGenerator.
            # Regenerated on every run; do not edit.
          RUBY

          def initialize(scanner:)
            @scanner = scanner
          end

          # => [FileEntry] (framework reopen first, then one .rb per controller
          # that has at least one action).
          def build
            controllers = @scanner.controllers
            return [] if controllers.empty?

            framework_files + controllers.flat_map { |name| controller_files(name) }
          end

          private

          # Models Rails' own halt mechanism: `redirect_to`/`render`/`head` mark
          # the response as performed, and `performed?` reads that back — which
          # is what the callback terminator calls to stop the chain.
          #
          # The state itself is a TOOL-OWNED, `bool`-typed ivar rather than
          # Rails' real `@_response_body`: state is the only channel a callee
          # (`redirect_to`, often nested inside `respond_to { |f| f.html { … } }`)
          # can use to reach the runner's frame, and only a TYPED ivar can carry
          # a fact — `@_response_body` is declared `untyped`, so refining it
          # would assert nothing.
          #
          # Giving `performed?` a body also re-types it: the analyzer infers
          # `() -> true?` from it, replacing the inherited `() -> untyped`. That
          # is what makes the predicate usable as a proof carrier — testing an
          # `untyped` predicate refines nothing.
          #
          # `(*args)` (no `**kwargs`, which trips a Steep internal error) is
          # permissive enough for every framework signature, and each body ends
          # with a literal `true` so it satisfies the narrowest declared return
          # among them (`head: (...) -> true`).
          #
          # `redirect_to` keeps its FAITHFUL return type (whatever the framework
          # RBS says): modelling the halt as a non-returning `bot` would be both
          # untrue to runtime and useless here, since the halt usually sits inside
          # nested blocks whose bottom-ness would not kill the enclosing call
          # anyway.
          def framework_files
            body = <<~RUBY
              #{HEADER}
              module ActionController
                class Base
                  def redirect_to(*args)
                    @__rbs_infer__performed = true
                    true
                  end

                  def render(*args)
                    @__rbs_infer__performed = true
                    true
                  end

                  def head(*args)
                    @__rbs_infer__performed = true
                    true
                  end

                  def #{HALTED}
                    @__rbs_infer__performed
                  end

                  # Stands for a callback condition we cannot name (a proc taking
                  # the controller, a multi-statement lambda): the link "may or may
                  # not run", so it proves nothing. The body is deliberately an
                  # opaque runtime predicate — the checker can type it (bool) but
                  # never decide it, which is exactly the semantics wanted. It
                  # needs A body at all because the analyzer, not this generator,
                  # emits the RBS.
                  def #{UNKNOWN_CONDITION_METHOD}
                    request.present?
                  end
                end
              end
            RUBY

            [FileEntry.new(filename: "action_controller_base.rb", source: body)]
          end

          def controller_files(class_name)
            actions = @scanner.actions_for(class_name)

            [FileEntry.new(
              filename: "#{filename_for(class_name)}.rb",
              source: controller_source(class_name, actions)
            )]
          end

          def controller_source(class_name, actions)
            runners = actions.map { |action| runner_method(class_name, action) }

            <<~RUBY
              #{HEADER}
              class #{class_name}
                private

              #{runners.join("\n").chomp}
              end
            RUBY
          end

          # The request flow of one action: every before_action link that runs
          # for it, each followed by the halt check, then the action itself.
          def runner_method(class_name, action)
            lines = @scanner.chain_for(class_name, action).flat_map do |callback|
              link_lines(callback) + ["return if #{HALTED}", ""]
            end

            body = (lines + [action]).map { |line| line.empty? ? "" : "    #{line}" }

            ["  def __rbs_infer__run_#{action}", *body, "  end"].join("\n") + "\n"
          end

          # A handler link is a self-send; a block link is the block's body
          # inlined verbatim (it runs in the controller instance's context, so
          # it is valid there as written).
          def link_lines(callback)
            condition = condition_for(callback)

            if callback.kind == :block
              block_lines(callback, condition)
            elsif condition
              ["#{callback.handler} if #{condition}"]
            else
              [callback.handler]
            end
          end

          def block_lines(callback, condition)
            body = callback.block_source.to_s.lines.map(&:strip).reject(&:empty?)
            return [] if body.empty?

            return body unless condition

            ["if #{condition}", *body.map { |line| "  #{line}" }, "end"]
          end

          # `if:` / `unless:` become a literal Ruby condition — this is where the
          # pseudo-code approach earns its keep: the Steep fork resolves the
          # predicate itself (`authenticated_account_access?` is just a call),
          # with no need to statically prove the condition here.
          def condition_for(callback)
            parts = []
            parts << predicate(callback.if_cond) if callback.if_cond
            parts << "!#{predicate(callback.unless_cond)}" if callback.unless_cond
            return nil if parts.empty?

            parts.join(" && ")
          end

          def predicate(cond)
            cond == Controllers::UNKNOWN_CONDITION ? UNKNOWN_CONDITION_METHOD : cond
          end

          def filename_for(class_name)
            class_name.gsub("::", "_").underscore
          end
        end
      end
    end
  end
end
