# frozen_string_literal: true

require "fileutils"
require "prism"

module RbsInfer
  module Extensions
    module Rails
      module Jobs
        # Emits *pseudo-code* for what ActiveJob does between `perform_later` and
        # `perform` — the enqueue/execute round trip — so the analyzer can read a
        # job's arguments off its call sites instead of being handed them.
        #
        # A job's `perform` is never called by the app; `MyJob.perform_later(user)`
        # is. The gem RBS types that as `(*untyped) -> untyped`, so today every
        # `perform` parameter infers `untyped` no matter how unambiguous the call
        # site is. What the framework actually does — serialize the arguments,
        # then hand them back to `perform` on a fresh instance — is a plain-Ruby
        # forward, and this writes it:
        #
        #     class ActiveJob::Base
        #       def self.perform_later(*args, **kwargs)
        #         new.perform(*args, **kwargs)
        #         new
        #       end
        #     end
        #
        # The trailing `new` is the return value `perform_later` really has (the
        # enqueued job), not `perform`'s.
        #
        # KNOWN LIMITATION — this does not yet type any `perform`. Written once on
        # `ActiveJob::Base`, the reopen is shared by every job in the app, so the
        # call-site evidence lands on THAT class's `*args`: `NotifyUserJob` and
        # `ExportJob` both feed the same parameter, and `new.perform` in this body
        # has no way back to the job that was called. Measured on the dummy, a
        # single call site yields
        #
        #     def self.perform_later: (*(User & User::Validated | { message: String }) args, **untyped) -> ActiveJob::Base
        #
        # while `NotifyUserJob#perform` stays `(untyped user, message: untyped)`.
        # Closing it needs the receiver of the call site to reach the forward —
        # either per-subclass instantiation of this body, or `InvokerSelfTypes`
        # learning to resolve a call made ON a receiver (it declines those today).
        class RuntimeGenerator
          # NOT dot-prefixed: `.rb` SOURCE the analyzer and the Steep fork read
          # via `sig/**/*.rb` (`**` skips hidden dirs).
          SIDECAR_DIR = "sig/generated/steep_activejob_runtime"
          JOB_ROOTS = %w[app/jobs].freeze
          SUPERCLASS_NAMES = ["ActiveJob::Base", "::ActiveJob::Base"].freeze
          FILENAME = "active_job_base.rb"

          def initialize(app_dir:)
            @app_dir = app_dir
          end

          # => [{ filename:, source: }] — empty unless the app defines a job.
          def build
            return [] unless job_base_subclass?

            [{ filename: FILENAME, source: reopen_source }]
          end

          # Writes the sidecar dir, removing a stale one when nothing qualifies.
          # Returns the sidecar dir path.
          def generate
            files = build
            dir = File.join(@app_dir, SIDECAR_DIR)

            FileUtils.rm_rf(dir)
            unless files.empty?
              FileUtils.mkdir_p(dir)
              files.each { |file| File.write(File.join(dir, file[:filename]), file[:source]) }
            end

            dir
          end

          private

          # Gated on the app actually subclassing `ActiveJob::Base` (which
          # `ApplicationJob` does), so a project without jobs pays nothing and
          # the reopen never names a class that isn't loaded.
          def job_base_subclass?
            JOB_ROOTS.any? do |root|
              Dir.glob(File.join(@app_dir, root, "**/*.rb")).sort.any? do |path|
                source = File.read(path)
                next false unless source.include?("ActiveJob::Base")

                subclasses_job_base?(source)
              end
            end
          end

          def subclasses_job_base?(source)
            result = Prism.parse(source)
            return false unless result.success?

            RbsInfer::Analyzer.find_all_nodes(result.value) { |n| n.is_a?(Prism::ClassNode) }.any? do |klass|
              superclass = klass.superclass
              superclass && SUPERCLASS_NAMES.include?(RbsInfer::Analyzer.extract_constant_path(superclass))
            end
          end

          def reopen_source
            <<~RUBY
              # frozen_string_literal: true
              #
              # GENERATED by RbsInfer::Extensions::Rails::Jobs::RuntimeGenerator.
              # Regenerated on every run; do not edit.
              #
              # What ActiveJob does between `perform_later` and `perform`, as plain
              # Ruby: the arguments handed to the enqueue call are the arguments
              # `perform` receives, on a fresh instance. The trailing `new` is the
              # enqueued job `perform_later` returns.

              class ActiveJob::Base
                def self.perform_later(*args, **kwargs)
                  new.perform(*args, **kwargs)
                  new
                end
              end
            RUBY
          end
        end
      end
    end
  end
end
