class Post
  module Taggable
    extend ActiveSupport::Concern
    def tag_names: () -> untyped
    def tag_with: (untyped name) -> untyped
    def untag: (untyped name) -> untyped
    def tagged_with?: (untyped name) -> untyped
    def replace_tags: (untyped names) -> untyped
  end
end
