---
name: actiontext
version: '7.2'
source:
  type: git
  name: ruby/gem_rbs_collection
  revision: 1c5e96b6c43ba1518821d860b0bc804d6265d32b
  remote: https://github.com/felixefelip/gem_rbs_collection.git
  repo_dir: gems
