---
name: actiontext
version: '7.2'
source:
  type: git
  name: ruby/gem_rbs_collection
  revision: 4d9d8513381f344add6de90fac339953a57d142c
  remote: https://github.com/felixefelip/gem_rbs_collection.git
  repo_dir: gems
