class Example59
  module Naming
    extend ActiveSupport::Concern
  end
end

class Example59
  module Naming
    module ClassMethods
      def human_name: (("all" | "closed") index) -> String
    end
  end
end
