# frozen_string_literal: true
#
# GENERATED by RbsInfer::Extensions::Rails::ActiveRecord::RuntimeGenerator.
# Regenerated on every run; do not edit.

module Comment::GeneratedRelationMethods
  def latest_author_full_name
    ::Comment.latest_author_full_name
  end
end
