# frozen_string_literal: true

require_relative "template_scanner"
require_relative "path_naming"

module RbsInfer
  module Extensions
    module Rails
      module Views
        # Builds the view-runtime pseudo-code: one plain `.rb` per ERB template, modelling
        # what ActionView does at render time, so the ANALYZER derives the view's RBS the
        # same way it derives any other class's.
        #
        # This replaces hand-rolled inference with the generic pipeline. The generator it
        # retired (`ErbConventionGenerator`, removed once this shipped) emitted `.rbs`
        # directly and had to compute the types itself: it walked every `render` call site,
        # mapped Prism nodes to type strings by hand, resolved collection element types, and
        # merged the results by STRING CONCATENATION — a union over every call site in the
        # app. A partial rendered from two actions got the union of both, with no way to say
        # "on this path it is the narrowed one".
        #
        # Emitting Ruby instead makes each render a real call site:
        #
        #     class ERBPostsEdit
        #       def initialize(post:) = @post = post
        #       def render(*args)
        #         ERBPartialPostsForm.new(post: @post)
        #       end
        #     end
        #
        # `@post`'s type comes from `ERBPostsEdit.new(post: …)` in the controller runtime,
        # and the partial's `post` from THIS call site — so the type flows
        # `action -> view ivar -> partial local`, per path, through `NewCallCollector` /
        # `ParamTypeInferrer` / `TypeMerger`. Nothing here computes a type.
        #
        # As with the controller runtime, no `.rbs` is emitted: that is the analyzer's job
        # (`rbs_infer sig/ --output`), and declaring the same methods twice is something RBS
        # rejects outright.
        #
        # Why `render` hosts the constructor calls but does NOT dispatch on its argument:
        # the controller-runtime override can do `case args.first when :edit` because an
        # action renders by symbol. A template renders by `render partial: "x", locals: {…}`,
        # where `args.first` is a HASH — so a `when "x"` branch would never match and the
        # dispatch would be dead code. Since only the presence of the call site matters for
        # inference, the calls are emitted unconditionally.
        class PseudoCodeBuilder
          include PathNaming

          FileEntry = Struct.new(:filename, :source, keyword_init: true)

          HEADER = <<~HEADER
            # frozen_string_literal: true
            #
            # GENERATED by RbsInfer::Extensions::Rails::Views::RuntimeGenerator.
            # Regenerated on every run; do not edit.
          HEADER

          def initialize(app_dir:)
            @app_dir = app_dir
          end

          def build
            templates.filter_map { |path| file_for(path) }
          end

          private

          def templates
            Dir[File.join(@app_dir, "app/views/**/*.{html,turbo_stream}.erb")].sort
          end

          def file_for(path)
            view_relative = path.sub("#{@app_dir}/", "").sub(%r{\Aapp/views/}, "")
            class_name = erb_class_name(view_relative) or return nil

            scan = TemplateScanner.scan(File.read(path))
            caller_dir = File.dirname(view_relative)
            caller_dir = nil if caller_dir == "."

            FileEntry.new(
              filename: view_relative.sub(/\.(html|turbo_stream)\.erb\z/, ".rb"),
              source: source_for(class_name, view_relative, scan, caller_dir)
            )
          end

          def source_for(class_name, view_relative, scan, caller_dir)
            partial = partial_key_from_view_relative(view_relative)
            # A partial's inputs are its LOCALS, read in the template as bare names, so they
            # get an `attr_reader`. A view's inputs are its controller's IVARS, read as
            # `@post`, so the reader would be wrong.
            locals = partial ? local_names(view_relative) : []
            ivars = scan.ivars

            members = []
            members << includes(view_relative)
            members << initializer(locals.empty? ? ivars : locals)
            members << render_method(scan, caller_dir)
            members << params_method
            members << body_method
            members << reader_section(locals)

            "#{HEADER}\nclass #{class_name}\n#{members.compact.join("\n\n")}\nend\n"
          end

          # The locals a partial declares. Nothing in the template says what they are —
          # a partial reads them as bare local variables — so the names come from the
          # render call sites that target it, collected across the app. Only NAMES: the
          # types are the analyzer's job, from the emitted `.new` call sites.
          def local_names(view_relative)
            key = partial_key_from_view_relative(view_relative) or return []
            names = []

            templates.each do |path|
              dir = File.dirname(path.sub("#{@app_dir}/", "").sub(%r{\Aapp/views/}, ""))
              dir = nil if dir == "."
              TemplateScanner.scan(File.read(path)).renders.each do |render|
                next unless resolve_partial(render.partial, dir) == key
                names.concat(render.locals.keys)
              end
            end

            names.uniq.sort
          end

          # `ActionViewContext` (from the rails_custom generator) already bundles
          # ActionView::Helpers, the path/flash helpers and ApplicationHelper; the
          # controller's own helper module is added when the app defines one.
          def includes(view_relative)
            modules = ["ActionViewContext"]
            if (info = parse_view_path(view_relative))
              helper = info[:controller_class].sub(/Controller\z/, "Helper")
              path = File.join(@app_dir, "app/helpers/#{info[:controller_name]}_helper.rb")
              modules << helper if File.exist?(path)
            end
            modules.map { |m| "  include #{m}" }.join("\n")
          end

          def initializer(names)
            return nil if names.empty?

            params = names.map { |n| "#{n}:" }.join(", ")
            assigns = names.map { |n| "    @#{n} = #{n}" }
            ["  def initialize(#{params})", *assigns, "  end"].join("\n")
          end

          # Hosts one constructor call per partial this template renders. An iteration-bound
          # render is re-emitted AS the loop, so the local's type is the collection's element
          # type — derived by the pipeline, not unwrapped here.
          def render_method(scan, caller_dir)
            calls = scan.renders.filter_map { |render| render_call(render, caller_dir) }
            return nil if calls.empty?

            ["  def render(*args)", *calls, "  end"].join("\n")
          end

          def render_call(render, caller_dir)
            key = resolve_partial(render.partial, caller_dir) or return nil
            # Only emit a call to a partial that actually exists: naming a class no file
            # defines would turn a missing template into a type error about the pseudo-code.
            partial_relative = partial_file(key) or return nil
            klass = erb_class_name(partial_relative) or return nil

            args = render.locals.map { |name, value| "#{name}: #{value}" }.join(", ")
            construct = args.empty? ? "#{klass}.new" : "#{klass}.new(#{args})"

            if (iteration = render.iteration)
              "    #{iteration[:receiver]}.each { |#{iteration[:param]}| #{construct} }"
            else
              "    #{construct}"
            end
          end

          # "posts/form" => "posts/_form.html.erb" for whichever format exists, else nil.
          def partial_file(key)
            underscored = key.sub(%r{([^/]+)\z}, '_\1')
            %w[html turbo_stream].each do |format|
              relative = "#{underscored}.#{format}.erb"
              return relative if File.exist?(File.join(@app_dir, "app/views", relative))
            end
            nil
          end

          def resolve_partial(name, caller_dir)
            return nil unless name
            return name if name.include?("/") || caller_dir.nil?

            "#{caller_dir}/#{name}"
          end

          def params_method
            ["  def params", "    ActionController::Parameters.new", "  end"].join("\n")
          end

          # The template-as-method identity (Steep `@type self_method:`, felixefelip/steep#85):
          # at runtime ActionView compiles the template into a method, and the controller
          # runtime "renders" the view by calling this one. It must exist for the ERB body to
          # map onto it; the body itself lives in the template.
          def body_method
            ["  def __rbs_infer__body", "    nil", "  end"].join("\n")
          end

          def reader_section(locals)
            return nil if locals.empty?

            ["  private", "", *locals.map { |n| "  attr_reader :#{n}" }].join("\n")
          end
        end
      end
    end
  end
end
