# frozen_string_literal: true

require "fileutils"
require_relative "pseudo_code_builder"

module RbsInfer
  module Extensions
    module Rails
      module Views
        # Emits the view-runtime pseudo-code sidecar: one plain `.rb` per ERB template, from
        # which the analyzer infers the view's RBS.
        #
        # Sibling of `Controllers::RuntimeGenerator`, and the same idea — model at the source
        # level what the framework does at runtime, then let the ordinary pipeline read it —
        # applied to ActionView instead of ActionController. See Views::PseudoCodeBuilder for
        # why this replaces the hand-derived types `ErbConventionGenerator` emitted.
        class RuntimeGenerator
          # NOT dot-prefixed: these are `.rb` SOURCE files Steep must type-check (via a
          # `check "sig/**/*.rb"` glob), and `**` skips hidden (dot) directories.
          SIDECAR_DIR = "sig/generated/steep_actionview_runtime"

          # Bare declarations for every class the pseudo-code defines
          # (felixefelip/rbs_infer#123). A template is read as a CALLER file, and checking
          # one goes through its `@type self_method: ERBFoo#__rbs_infer__body` annotation —
          # which makes Steep build `ERBFoo`. Before its RBS has been inferred there is no
          # such class, and RBS raises rather than reporting, taking the whole run with it.
          # A template therefore could not bootstrap: the run that would generate its RBS
          # was the run that died.
          #
          # Empty on purpose. It exists so the name resolves; every member still comes from
          # the analyzer, and RBS merges the two declarations.
          DECLARATIONS_FILE = "erb_classes.rbs"

          def initialize(app_dir:)
            @app_dir = app_dir
          end

          # Returns [PseudoCodeBuilder::FileEntry]. Public so the CLI/specs can inspect the
          # pseudo-code without touching disk.
          def build
            PseudoCodeBuilder.new(app_dir: @app_dir).build
          end

          # Writes the sidecar directory, removing a stale one when nothing qualifies.
          # Returns the sidecar dir path.
          def generate
            files = build
            dir = File.join(@app_dir, SIDECAR_DIR)

            FileUtils.rm_rf(dir)
            unless files.empty?
              files.each do |file|
                path = File.join(dir, file.filename)
                FileUtils.mkdir_p(File.dirname(path))
                File.write(path, file.source)
              end
              File.write(File.join(dir, DECLARATIONS_FILE), declarations(files))
            end

            dir
          end

          # `class ERBFoo end` for every emitted class, one file for the lot.
          def declarations(files = build)
            lines = [
              "# GENERATED by RbsInfer::Extensions::Rails::Views::RuntimeGenerator.",
              "#",
              "# Bare declarations so a template's `@type self_method:` resolves before its",
              "# RBS has been inferred (felixefelip/rbs_infer#123). Members come from the",
              "# analyzer; RBS merges the two declarations.",
              ""
            ]
            files.map(&:class_name).compact.uniq.sort.each do |class_name|
              lines << "class #{class_name}"
              lines << "end"
              lines << ""
            end
            lines.join("\n")
          end
        end
      end
    end
  end
end
