# frozen_string_literal: true
#
# GENERATED by RbsInfer::Extensions::Rails::ActiveRecord::BelongsToDefaultGenerator.
# Regenerated on every run; do not edit.

class RbsInferBelongsToDefaultRunner
  def self.witness_assignment
    record = RbsInferBelongsToDefaultAssignment.new
    record.post = RbsInferBelongsToDefaultPost.new
    record.owner = RbsInferBelongsToDefaultUser.new
  end

  def self.site_1
    record = RbsInferBelongsToDefaultAssignment.new
    owner = RbsInferBelongsToDefaultPost.new
    record.post = owner
    record.save
  end
end
