# frozen_string_literal: true
#
# GENERATED by RbsInfer::Extensions::Rails::ActiveRecord::BelongsToDefaultGenerator.
# Regenerated on every run; do not edit.

class RbsInferBelongsToDefaultAssignment
  attr_accessor :post, :owner

  def save
    run_before_validation_callbacks
  end

  def run_before_validation_callbacks
    run_belongs_to_default_callbacks
  end

  def run_belongs_to_default_callbacks
    self.owner = post.user
  end
end
