class DashboardController < ApplicationController
  @account: (Account & Account::Validated)?
  @recent_posts: Post::ActiveRecord_Relation?

  def show: () -> void

  private

  def set_current_account: () -> (Account & Account::Validated)
end
