class Post
  module Taggable
    module ClassMethods
      def default_tag_names: () -> Array[String]
      def known_tag?: (untyped name) -> bool
      def tags_ordered_by_tag_name: () -> Post::ActiveRecord_Relation
      def touch_recently_tagged: () -> nil
    end

    extend ActiveSupport::Concern

    def tag_names: () -> Array[untyped]
    def tag_with: (untyped name) -> (Tag & Tag::Validated)
    def untag: (untyped name) -> untyped
    def tagged_with?: (untyped name) -> bool
    def replace_tags: (untyped names) -> untyped
  end
end
