class User
  module Notifiable
    extend ActiveSupport::Concern

    def unread_notifications: () -> Notification::ActiveRecord_Relation
    def notifications_count: () -> Integer
    def notify!: ("Welcome" title) -> Notification
    def notify_welcome!: () -> Notification
    def mute_latest_notification!: () -> "none"?
    def latest_notification_headline: () -> String?
  end
end
