class Example23
  module Foo
    def bazinga: (singleton(::Example23::Baz) module_included) -> String
    def bazingado: (untyped base_foo) -> nil
  end

  module Baz
    extend ::Example23::Foo

    def self.bazingado: (singleton(Example23::Bar) base_foo) -> String
  end
end

class Example23
  class Bar
    extend ::Example23::Foo

    def self.log_something: (String message) -> String
  end
end
