class Example47
  module Foo
    def banana_class_method: () ?{ (*untyped) -> Symbol } -> untyped
  end

  module Baz
    extend ::Example47::Foo
  end

  module Baz::BananaMethods
    def color: () -> String
  end
end

class Example47
  class Bar
    extend ::Example47::Baz::BananaMethods

    def self.call_color: () -> String
    def self.call_age: () -> untyped
  end
end
