class Example3
  def self.run: () -> nil
  def self.gap_alias_write: () -> String
  def self.gap_conditional: (untyped cond) -> String
  def self.gap_callee_mutation: () -> String
  def self.gap_alias_read: () -> untyped
end

class Example3
  class User
    attr_reader name: String

    def initialize: (name: String) -> void
  end
end

class Example3
  class Foo
    self.@foo_instance: Foo?

    module GeneratedAttributes
      attr_accessor user: (User | nil)?
      attr_accessor name: String?
      attr_writer foo_instance: untyped
    end

    include GeneratedAttributes

    def self.foo_instance: () -> Example3::Foo
    def self.user: () -> (Example3::User | nil)?
    def self.user=: ((User | nil) value) -> (User | nil)
    def self.name: () -> String?
    def self.name=: (String? value) -> String?
    def self.clear_user: () -> nil

    def user=: ((User | nil) value) -> untyped
  end
end
