class Example62
  module Deferring
    @kept: (^(*untyped) [self: Module] -> Symbol)?

    def self.extended: (Object base) -> Array[untyped]

    def keep: () ?{ (*untyped) [self: Module] -> Symbol } -> (^(*untyped) [self: Module] -> Symbol)?
    def append_features: (Module base) -> Symbol?
  end

  module Shared
    extend Deferring
  end

  module Middle
    include Shared
    extend Deferring
  end

  include Slots
  include Middle

  def hallmark: () -> String
end

class Example62Caller
  def fill: () -> String
  def read_hallmark: () -> String
end
