class Example5
  def run: () -> "JOHN DOE"
end

class Example5
  class Foo
    self.@name: "John Doe"?

    def self.name: () -> "John Doe"?
    def self.name=: ("John Doe" value) -> "John Doe"
  end
end

class Example5
  class Bar
    def foo_name: () -> "JOHN DOE"
    def deep_foo_name: () -> "JOHN DOE"
  end
end
