class Example26
  module Foo
    def bazinga: ((singleton(::Example26::Baz) | singleton(::Example26::BazOther)) module_included) -> String?
    def bazingado: (singleton(Example26::Bar) base_foo) -> nil
  end

  module Baz
    extend ::Example26::Foo
  end

  module BazOther
    extend ::Example26::Foo

    def self.bazingado: (singleton(Example26::BarOther) base_foo) -> String
  end
end

class Example26
  class Bar
    extend ::Example26::Foo
  end
end

class Example26
  class BarOther
    extend ::Example26::Foo

    def self.log_something: (String message) -> String
  end
end
