class Example49
  class Bar
    extend ::Example49::Baz

    def self.call_color: () -> "YELLOW"
    def self.call_age: () -> 41
  end
end

class Example49
  module Baz
    def color: () -> "yellow"
    def age: () -> 31
  end
end
