module Example77
  module Writer
    def self.generate: (singleton(Peel) owner, (:human_name | :nick) method) -> untyped
  end
end

module Example77
  class Peel
    def self.human_name: ("all" index) -> "ALL"
    def self.banana_delegate: ((:human_name | :nick) method) -> untyped
  end
end

module Example77
  class Rind < Peel
    def self.nick: ("x" name) -> "x"
  end
end

module Example77
  class Eater
    def label: () -> "ALL"
    def nickname: () -> "x"
  end
end
