module Example71
  module Writes
    def writes_mixed: (:from_mixin name) -> untyped
  end
end

module Example71
  class Target
    def from_constant: () -> :constant
    def from_local: () -> :local
  end
end

module Example71
  class Host
    def self.writes_on_self: (:from_self name) -> untyped
    def self.writes_on_constant: (:from_constant name) -> untyped
    def self.writes_on_local: (:from_local name) -> untyped

    def from_self: () -> :self
  end
end

module Example71
  class Base
    def self.writes: (:from_inherited name) -> untyped
  end
end

module Example71
  class Child < Base
    def from_inherited: () -> :inherited
  end
end

module Example71
  class Mixed
    extend Writes

    def from_mixin: () -> :mixed
  end
end
