module Example30
  class Foo
    def name: () -> String
    def build_age: () -> Symbol
    def call_age: () -> Integer
  end
end

module Example30
  class Foo
    class AfterBuildAge
      def age: () -> Integer
    end
  end
end
