class Example87
  module Writer
    def self.define_accessors: (singleton(Example87) model, HasManyReflection reflection) -> untyped
  end

  def self.has_association: ((:posts | :comments) name, ?Hash[untyped, untyped] options) -> untyped
  def self.summary: () -> [ :many, :many ]
end

class Example87
  class MacroReflection
    @options: Hash[untyped, untyped]

    attr_reader name: (:posts | :comments)

    def initialize: ((:posts | :comments) name, Hash[untyped, untyped] options) -> void
  end
end

class Example87
  class AssociationReflection < MacroReflection
    @collection: false

    def initialize: ((:posts | :comments) name, Hash[untyped, untyped] options) -> false
  end
end

class Example87
  class HasManyReflection < AssociationReflection
  end
end
