class Example81
  @owner: User

  module Shelf
    def self.fetch: (untyped key) -> untyped
  end

  def initialize: () -> User
  def author: () -> User
  def full_name: () -> String
  def owner_full_name: () -> String
  def fetch: (untyped key) ?{ (*untyped) -> untyped } -> untyped
end
