class Column
  attr_accessor board: Board?
  attr_accessor column_name: "To Do"
  attr_accessor user_name: String?

  def initialize: (column_name: "To Do") -> void
  def set_default_user_name: () -> String
  def save: () -> true

  class AfterInitialize
    attr_reader column_name: String
  end

  class AfterSetDefaultUserName
    attr_reader user_name: String
  end
end

class Board
  attr_reader user_name: "John Doe"

  def initialize: (user_name: "John Doe") -> void

  class AfterInitialize
    attr_reader user_name: String
  end
end

class Example
  def self.run: () -> bool
end
