class Example14
  @halted: true?
  @user: Example14::User?

  def run: () -> String?

  private

  def halt: () -> true
  def verify: () -> Example14::User
  def set_user: () -> Example14::User
end

class Example14
  class User
    attr_reader name: "Joe"

    def initialize: (name: "Joe") -> void

    class AfterInitialize
      attr_reader name: String
    end
  end
end
