class Example17
  def with_token: () { (String) -> String } -> String
  def with_optional: () ?{ (String) -> untyped } -> untyped
  def with_yield: () { (String) -> untyped } -> untyped
  def with_pair: () { (String, Integer) -> untyped } -> untyped
  def with_either: (untyped flag) { (String | Integer) -> untyped } -> untyped
  def forward_required: () { (String) -> untyped } -> String
  def forward_optional: () ?{ (*untyped) -> untyped } -> untyped
  def forward_guarded: () ?{ (*untyped) -> untyped } -> String?
  def forward_anonymous: () { (String) -> untyped } -> String
  def forward_anonymous_guarded: () ?{ (*untyped) -> untyped } -> String?
  def name: () -> String
  def run: () -> String
end
