module Example73
  class Foo
    def array_fixed: () -> [ "a", "b", "c" ]
    def array_dynamic: () -> [ "a", "b", "c" ]
    def from_a_literal: () -> [ "a", "b" ]
    def through_a_call: () -> Array[untyped]
    def fill: (Array[untyped] parts) -> Array[untyped]
  end
end
