class Example10
  def run: () -> Example10::Bar
end

class Example10
  class Foo
    self.@name: String?

    def self.name: () -> String?
    def self.name=: (String value) -> String
  end
end

class Example10
  class Sink
    self.@last: Example10::Bar?

    def self.last: () -> Example10::Bar?
    def self.last=: (Example10::Bar value) -> Example10::Bar
  end
end

class Example10
  class Bar
    def greet: () -> untyped
  end
end
