class Example7
  def run_name: () -> (String | Integer | nil)
  def run_age: () -> (String | Integer | nil)
end

class Example7
  class Foo
    self.@name: "John Doe"?

    def self.name: () -> String?
    def self.name=: ("John Doe" value) -> "John Doe"
  end
end

class Example7
  class Age
    self.@value: 42?

    def self.value: () -> Integer?
    def self.value=: (42 value) -> 42
  end
end

class Example7
  class Dispatcher
    def show: ((:name | :age) which) -> (String | Integer | nil)
  end
end
