class Post < ApplicationRecord
  extend Enumerize
  include ::Post::Taggable
  include ::Post::Notifiable
  include Test::Filtrable
  def summary: (?Integer length) -> String
  def test_status: () -> Post::EnumerizeStatusValue
  def was_archived?: () -> bool
  def creator: () -> ::User
  def author_name: () -> String
  def publish!: () -> self
  def comments_count: () -> Integer
  def add_comment: (author: untyped, body: untyped) -> Comment
  def was_priority_high: () -> bool?
  def publish_in_transaction: () -> self
  def iterate_tags: () -> Tag::ActiveRecord_Associations_CollectionProxy
  def test_enumerize_status: () -> Post::EnumerizeStatusAttribute
  def test_enumerize_status_options: () -> Array[Array[untyped]]
  def user_email: () -> String
  def full_name: () -> String
  def user_created_at: () -> ActiveSupport::TimeWithZone
  def name: () -> String?
end