class Widget
  module Closeable
    extend ActiveSupport::Concern

    def close: () -> { action: (:published | "renamed" | :closed | :reopened), particulars: untyped }
    def reopen: () -> ({ action: Symbol | String, particulars: untyped } | nil)
    def audit: () -> true
  end
end
