class Widget
  module Closeable
    extend ActiveSupport::Concern

    def close: () -> { action: :closed, particulars: Hash[Symbol, untyped] }
    def reopen: () -> ({ action: Symbol | String, particulars: untyped } | nil)
    def audit: () -> true
  end
end
