class EmailNotifier
  attr_reader from_address: String
  attr_reader delivery_method: Symbol
  def initialize: (?from_address: untyped, ?delivery_method: untyped) -> untyped
  def notify: (untyped user, untyped message) -> Hash[untyped, untyped]
end