class Post < ApplicationRecord
  def summary: (?Integer length) -> untyped
  def creator: () -> ::User
  def author_name: () -> String
  def publish!: () -> untyped
  def comments_count: () -> Integer
  def add_comment: (author: untyped, body: untyped) -> Comment
end