class Post < ApplicationRecord
  def summary: (?Integer length) -> untyped
  def test_status: () -> Post::EnumerizeStatusValue
  def was_archived?: () -> bool
  def creator: () -> ::User
  def author_name: () -> String
  def publish!: () -> self
  def comments_count: () -> Integer
  def add_comment: (author: untyped, body: untyped) -> Comment
  def was_priority_high: () -> bool?
  def publish_in_transaction: () -> Post
  def iterate_tags: () -> ::Tag::ActiveRecord_Associations_CollectionProxy
end