class TagDestroy
  attr_reader tag: Tag
  attr_reader user: User
  attr_reader posts: Array[untyped]
  attr_reader xml: Nokogiri::XML::Document
  def initialize: (untyped tag_id, untyped user_id) -> void
  def call: () -> bool

  private

  def atribui_user: (untyped user_id) -> User
  def user_name: () -> String
  def iterate_tags: () -> Tag::ActiveRecord_Associations_CollectionProxy?
  def iterate_tag_posts: () -> Post::ActiveRecord_Associations_CollectionProxy
  def iterate_tag_posts_with_transaction: () -> Post::ActiveRecord_Associations_CollectionProxy
  def call_process_tag: () -> void
  def process_tag: (Tag tag) -> void
  def test_nokogiri: () -> Nokogiri::XML::Document
  def parse_xml: () -> Array[Nokogiri::XML::Node]
  def parse_xml_as_hash: () -> Array[Hash[Symbol, untyped]]
  def parse_xml_as_hash_with_parse: () -> Array[Hash[Symbol, untyped]]
  def test_hash: (Nokogiri::XML::Node order_xml) -> { order: untyped, date: untyped }
  def verify_multiples_returns_with_void: () -> void
  def verify_multiples_returns_with_void_and_rescue: () -> String?
  def save_post: () -> void
  def user_posts: () -> Post::ActiveRecord_Associations_CollectionProxy
end