# frozen_string_literal: true

require "fileutils"
require "prism"
require "set"

module RbsInfer
  module RailsCustom
    class Generator
      attr_reader :output_dir, :app_dir, :source_files

      def initialize(output_dir:, app_dir: nil, source_files: nil)
        @output_dir = output_dir
        @app_dir = app_dir || Dir.pwd
        @source_files = source_files || Dir[File.join(@app_dir, "app/**/*.rb")]
      end

      def generate_all
        FileUtils.mkdir_p(output_dir)

        File.write(File.join(output_dir, "application_controller.rbs"), rbs_content)
        File.write(File.join(output_dir, "action_view_context.rbs"), action_view_context_rbs)
      end

      private

      def rbs_content
        lines = []
        lines << "# Generated by rbs_infer (rails_custom)"
        lines << ""
        lines << "class ApplicationController < ActionController::Base"
        lines << "  include ApplicationHelper"
        lines << "  include ActionView::Helpers"
        lines << "  include Kaminari::Helpers" if kaminari_installed?
        lines << ""
        lines << "  include DeviseCustom"
        lines << ""
        lines << "  include _RbsRailsPathHelpers"
        lines << ""
        lines << "  # Convenience accessor for <tt>flash[:alert]</tt>."
        lines << "  def alert: () -> String"
        lines << ""
        lines << "  # Convenience accessor for <tt>flash[:notice]</tt>."
        lines << ""
        lines << "  def notice: () -> String"
        lines << ""
        lines << "  def user_signed_in?: () -> bool"
        if kaminari_installed?
          lines << ""
          lines << "  # Métodos do Kaminari"
          lines << ""
          lines << "  def page: () -> untyped"
          lines << ""
          lines << "  def remote: () -> untyped"
          lines << ""
          lines << "  def url: () -> untyped"
          lines << ""
          lines << "  def paginator: () -> untyped"
          lines << ""
          lines << "  def each_page: () { (untyped) -> void } -> void"
          lines << ""
          lines << "  def page_tag: (untyped page) -> String"
          lines << ""
          lines << "  def gap_tag: () -> String"
        end
        lines << "end"
        lines << ""
        lines << "module DeviseCustom"
        lines << "  def devise_mapping: () -> untyped"
        lines << ""
        lines << "  def resource: () -> untyped"
        lines << ""
        lines << "  def resource_name: () -> Symbol"
        lines << ""
        lines << "  def new_session_path: (Symbol) -> String"
        lines << ""
        lines << "  def session_path: (Symbol) -> String"
        lines << ""
        lines << "  def new_registration_path: (Symbol) -> String"
        lines << ""
        lines << "  def new_password_path: (Symbol) -> String"
        lines << ""
        lines << "  def new_confirmation_path: (Symbol) -> String"
        lines << ""
        lines << "  def confirmation_path: (Symbol) -> String"
        lines << ""
        lines << "  def confirmation_url: (Symbol, confirmation_token: String) -> String"
        lines << ""
        lines << "  def new_unlock_path: (Symbol) -> String"
        lines << ""
        lines << "  def unlock_path: (Symbol) -> String"
        lines << ""
        lines << "  def unlock_url: (Symbol, unlock_token: String) -> String"
        lines << ""
        lines << "  def registration_path: (Symbol) -> String"
        lines << ""
        lines << "  def password_path: (Symbol) -> String"
        lines << ""
        lines << "  def edit_password_url: (Symbol, reset_password_token: String) -> String"
        lines << ""
        lines << "  def bootstrap_devise_error_messages!: () -> String"
        lines << ""
        lines << "  def resource_class: () -> untyped"
        lines << ""
        lines << "  def omniauth_authorize_path: (Symbol, untyped) -> String"
        lines << "end"
        lines.join("\n") + "\n"
      end

      def kaminari_installed?
        Gem.loaded_specs.key?("kaminari") || Gem.loaded_specs.key?("kaminari-core")
      end

      def action_view_context_rbs
        lines = []
        lines << "# Generated by rbs_infer (rails_custom)"
        lines << ""
        lines << "module ActionViewContext"
        lines << "  include ActionView::Helpers"
        lines << "  include _RbsRailsPathHelpers" if path_helpers_available?
        lines << "  include Kaminari::Helpers::HelperMethods" if kaminari_installed?
        lines << "  include ApplicationHelper"

        extract_app_controller_helper_methods.each do |name, signature|
          lines << ""
          lines << "  def #{name}: #{signature}"
        end

        lines << "end"
        lines.join("\n") + "\n"
      end

      def path_helpers_available?
        path_helpers_rbs = Dir[File.join(@app_dir, "sig/**/path_helpers.rbs")].first
        path_helpers_rbs && File.read(path_helpers_rbs).include?("_RbsRailsPathHelpers")
      end

      def extract_app_controller_helper_methods
        app_ctrl = File.join(@app_dir, "app/controllers/application_controller.rb")
        return {} unless File.exist?(app_ctrl)

        source = File.read(app_ctrl)
        tree = Prism.parse(source).value

        names = Set.new
        each_call(tree, :helper_method) do |call|
          call.arguments&.arguments&.each do |arg|
            names << arg.value if arg.is_a?(Prism::SymbolNode)
          end
        end
        return {} if names.empty?

        rbs = RbsInfer::Analyzer.new(
          target_class: "ApplicationController",
          target_file: app_ctrl,
          source_files: @source_files
        ).generate_rbs
        return {} unless rbs

        signatures = {}
        rbs.each_line do |line|
          stripped = line.strip
          if (m = stripped.match(/\Adef (\w+[?!]?): (.+)\z/))
            signatures[m[1]] = m[2] if names.include?(m[1])
          end
        end
        signatures
      end

      def each_call(node, method_name, &block)
        yield node if node.is_a?(Prism::CallNode) && node.name == method_name
        node.compact_child_nodes.each { |child| each_call(child, method_name, &block) }
      end
    end
  end
end
