# frozen_string_literal: true

require "fileutils"

module RbsInfer
  module RailsCustom
    class Generator
      attr_reader :output_dir

      def initialize(output_dir:)
        @output_dir = output_dir
      end

      def generate_all
        output_path = File.join(output_dir, "application_controller.rbs")
        FileUtils.mkdir_p(File.dirname(output_path))
        File.write(output_path, rbs_content)
      end

      private

      def rbs_content
        lines = []
        lines << "# Generated by rbs_infer (rails_custom)"
        lines << ""
        lines << "class ApplicationController < ActionController::Base"
        lines << "  include ApplicationHelper"
        lines << "  include ActionView::Helpers"
        lines << "  include Kaminari::Helpers" if kaminari_installed?
        lines << ""
        lines << "  include DeviseCustom"
        lines << ""
        lines << "  include _RbsRailsPathHelpers"
        lines << ""
        lines << "  # Convenience accessor for <tt>flash[:alert]</tt>."
        lines << "  def alert: () -> String"
        lines << ""
        lines << "  # Convenience accessor for <tt>flash[:notice]</tt>."
        lines << ""
        lines << "  def notice: () -> String"
        lines << ""
        lines << "  def user_signed_in?: () -> bool"
        if kaminari_installed?
          lines << ""
          lines << "  # Métodos do Kaminari"
          lines << ""
          lines << "  def page: () -> untyped"
          lines << ""
          lines << "  def remote: () -> untyped"
          lines << ""
          lines << "  def url: () -> untyped"
          lines << ""
          lines << "  def paginator: () -> untyped"
          lines << ""
          lines << "  def each_page: () { (untyped) -> void } -> void"
          lines << ""
          lines << "  def page_tag: (untyped page) -> String"
          lines << ""
          lines << "  def gap_tag: () -> String"
        end
        lines << "end"
        lines << ""
        lines << "module DeviseCustom"
        lines << "  def devise_mapping: () -> untyped"
        lines << ""
        lines << "  def resource: () -> untyped"
        lines << ""
        lines << "  def resource_name: () -> Symbol"
        lines << ""
        lines << "  def new_session_path: (Symbol) -> String"
        lines << ""
        lines << "  def session_path: (Symbol) -> String"
        lines << ""
        lines << "  def new_registration_path: (Symbol) -> String"
        lines << ""
        lines << "  def new_password_path: (Symbol) -> String"
        lines << ""
        lines << "  def new_confirmation_path: (Symbol) -> String"
        lines << ""
        lines << "  def confirmation_path: (Symbol) -> String"
        lines << ""
        lines << "  def confirmation_url: (Symbol, confirmation_token: String) -> String"
        lines << ""
        lines << "  def new_unlock_path: (Symbol) -> String"
        lines << ""
        lines << "  def unlock_path: (Symbol) -> String"
        lines << ""
        lines << "  def unlock_url: (Symbol, unlock_token: String) -> String"
        lines << ""
        lines << "  def registration_path: (Symbol) -> String"
        lines << ""
        lines << "  def password_path: (Symbol) -> String"
        lines << ""
        lines << "  def edit_password_url: (Symbol, reset_password_token: String) -> String"
        lines << ""
        lines << "  def bootstrap_devise_error_messages!: () -> String"
        lines << ""
        lines << "  def resource_class: () -> untyped"
        lines << ""
        lines << "  def omniauth_authorize_path: (Symbol, untyped) -> String"
        lines << "end"
        lines.join("\n") + "\n"
      end

      def kaminari_installed?
        Gem.loaded_specs.key?("kaminari") || Gem.loaded_specs.key?("kaminari-core")
      end
    end
  end
end
