# frozen_string_literal: true
#
# GENERATED by RbsInfer::Extensions::Rails::CurrentAttributesRuntimeGenerator.
# Regenerated on every run; do not edit.

class Current
  module GeneratedAttributeMethods
    def user
      @user
    end
    def user=(value)
      @user = value
    end
    def author_name
      @author_name
    end
    def author_name=(value)
      @author_name = value
    end
  end
  include GeneratedAttributeMethods

  def self.user
    @user
  end

  def self.user=(value)
    @user = value
    instance.user = value
  end

  def self.author_name
    @author_name
  end

  def self.author_name=(value)
    @author_name = value
    instance.author_name = value
  end

  def self.set(user: nil, author_name: nil, &block)
    @user = user
    @author_name = author_name
    block&.call(nil)
  end

  def self.with(user: nil, author_name: nil, &block)
    @user = user
    @author_name = author_name
    block&.call(nil)
  end
end
