class User
  module Recoverable
    extend ActiveSupport::Concern
    def deactivate!: () -> self
    def reactivate!: () -> self
    def toggle_active!: () -> self
    def days_since_last_post: () -> untyped
    def test_concern_created_at: () -> ::ActiveSupport::TimeWithZone
    def dormant?: (?Integer threshold_days) -> untyped
  end
end
