class User
  module Recoverable
    extend ActiveSupport::Concern
    def deactivate!: () -> untyped
    def reactivate!: () -> untyped
    def toggle_active!: () -> untyped
    def days_since_last_post: () -> untyped
    def test_concern_created_at: () -> untyped
    def dormant?: (?Integer threshold_days) -> untyped
  end
end
