class PostPublisher
  def self.publish: (untyped post) -> true

  attr_reader post: Post
  attr_reader notifier: EmailNotifier

  def initialize: (Post post, ?notifier: EmailNotifier) -> void
  def call: () -> true
end
