class ProfileFormatter
  attr_reader nickname: (String | nil)
  def initialize: (nickname: (String | nil)) -> void
  # o retorno deveria ser `String?
  def call: () -> String
  def call_without_check: () -> String

  private

  def format_nickname: () -> String
end
