# ⚠️  Generated by rbs_infer for debugging — NEVER loaded at runtime.
#     Expanded view of app/models/example58/defaults.rb (macros desugared into pseudo-code).
#     Regenerated on every run; do not edit.
# The `class_methods do` block is what makes this file TWO top-level modules
# once expanded — the concern, then the desugared `module …::ClassMethods` —
# and that is what used to cost the concern its self type. The self-type
# annotation was appended at end-of-file, where it binds to the file's sole
# node: for a one-module file that node IS the module, and for this one it is
# the file's `begin`. `self.class` fell back to Steep's default module self,
# `(::Object & ::Example58::Defaults)`, `default_values` was not on it, and
# `default_indexed_by` came out `untyped` (felixefelip/steep#155). The
# annotation now goes inside the anchor module's body, where it always binds.
module Example58::Defaults
  extend ActiveSupport::Concern

  class_methods do
    def default_values
      { indexed_by: "all", sorted_by: "latest" }
    end
  end

  def default_indexed_by
    self.class.default_values[:indexed_by]
  end
end

module Example58::Defaults::ClassMethods
  # @type instance: singleton(::Example58) & ::Example58::Defaults::ClassMethods
  def default_values
    { indexed_by: "all", sorted_by: "latest" }
  end
end
