# resolve-type-names: false

class ::Post < ::ApplicationRecord
  extend ::ActiveRecord::Base::ClassMethods[::Post, ::Post::ActiveRecord_Relation, ::Integer]

  module ::Post::GeneratedAttributeMethods
    def id: () -> ::Integer

    def id=: (::Integer) -> ::Integer

    def id?: () -> bool

    def id_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def id_change: () -> [ ::Integer?, ::Integer? ]

    def id_will_change!: () -> void

    def id_was: () -> ::Integer?

    def id_previously_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def id_previous_change: () -> ::Array[::Integer?]?

    def id_previously_was: () -> ::Integer?

    def id_before_last_save: () -> ::Integer?

    def id_change_to_be_saved: () -> ::Array[::Integer?]?

    def id_in_database: () -> ::Integer?

    def saved_change_to_id: () -> ::Array[::Integer?]?

    def saved_change_to_id?: () -> bool

    def will_save_change_to_id?: () -> bool

    def restore_id!: () -> void

    def clear_id_change: () -> void

    def id_before_type_cast: () -> ::Integer

    def id_for_database: () -> ::Integer

    def user_id: () -> ::Integer

    def user_id=: (::Integer) -> ::Integer

    def user_id?: () -> bool

    def user_id_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def user_id_change: () -> [ ::Integer?, ::Integer? ]

    def user_id_will_change!: () -> void

    def user_id_was: () -> ::Integer?

    def user_id_previously_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def user_id_previous_change: () -> ::Array[::Integer?]?

    def user_id_previously_was: () -> ::Integer?

    def user_id_before_last_save: () -> ::Integer?

    def user_id_change_to_be_saved: () -> ::Array[::Integer?]?

    def user_id_in_database: () -> ::Integer?

    def saved_change_to_user_id: () -> ::Array[::Integer?]?

    def saved_change_to_user_id?: () -> bool

    def will_save_change_to_user_id?: () -> bool

    def restore_user_id!: () -> void

    def clear_user_id_change: () -> void

    def user_id_before_type_cast: () -> ::Integer

    def user_id_for_database: () -> ::Integer

    def title: () -> ::String

    def title=: (::String) -> ::String

    def title?: () -> bool

    def title_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def title_change: () -> [ ::String?, ::String? ]

    def title_will_change!: () -> void

    def title_was: () -> ::String?

    def title_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def title_previous_change: () -> ::Array[::String?]?

    def title_previously_was: () -> ::String?

    def title_before_last_save: () -> ::String?

    def title_change_to_be_saved: () -> ::Array[::String?]?

    def title_in_database: () -> ::String?

    def saved_change_to_title: () -> ::Array[::String?]?

    def saved_change_to_title?: () -> bool

    def will_save_change_to_title?: () -> bool

    def restore_title!: () -> void

    def clear_title_change: () -> void

    def title_before_type_cast: () -> ::String

    def title_for_database: () -> ::String

    def body: () -> ::String

    def body=: (::String) -> ::String

    def body?: () -> bool

    def body_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def body_change: () -> [ ::String?, ::String? ]

    def body_will_change!: () -> void

    def body_was: () -> ::String?

    def body_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def body_previous_change: () -> ::Array[::String?]?

    def body_previously_was: () -> ::String?

    def body_before_last_save: () -> ::String?

    def body_change_to_be_saved: () -> ::Array[::String?]?

    def body_in_database: () -> ::String?

    def saved_change_to_body: () -> ::Array[::String?]?

    def saved_change_to_body?: () -> bool

    def will_save_change_to_body?: () -> bool

    def restore_body!: () -> void

    def clear_body_change: () -> void

    def body_before_type_cast: () -> ::String

    def body_for_database: () -> ::String

    def published_at: () -> ::ActiveSupport::TimeWithZone?

    def published_at=: (::ActiveSupport::TimeWithZone?) -> ::ActiveSupport::TimeWithZone?

    def published_at?: () -> bool

    def published_at_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def published_at_change: () -> [ ::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone? ]

    def published_at_will_change!: () -> void

    def published_at_was: () -> ::ActiveSupport::TimeWithZone?

    def published_at_previously_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def published_at_previous_change: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def published_at_previously_was: () -> ::ActiveSupport::TimeWithZone?

    def published_at_before_last_save: () -> ::ActiveSupport::TimeWithZone?

    def published_at_change_to_be_saved: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def published_at_in_database: () -> ::ActiveSupport::TimeWithZone?

    def saved_change_to_published_at: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def saved_change_to_published_at?: () -> bool

    def will_save_change_to_published_at?: () -> bool

    def restore_published_at!: () -> void

    def clear_published_at_change: () -> void

    def published_at_before_type_cast: () -> ::Time?

    def published_at_for_database: () -> ::Time?

    def created_at: () -> ::ActiveSupport::TimeWithZone

    def created_at=: (::ActiveSupport::TimeWithZone) -> ::ActiveSupport::TimeWithZone

    def created_at?: () -> bool

    def created_at_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def created_at_change: () -> [ ::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone? ]

    def created_at_will_change!: () -> void

    def created_at_was: () -> ::ActiveSupport::TimeWithZone?

    def created_at_previously_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def created_at_previous_change: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def created_at_previously_was: () -> ::ActiveSupport::TimeWithZone?

    def created_at_before_last_save: () -> ::ActiveSupport::TimeWithZone?

    def created_at_change_to_be_saved: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def created_at_in_database: () -> ::ActiveSupport::TimeWithZone?

    def saved_change_to_created_at: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def saved_change_to_created_at?: () -> bool

    def will_save_change_to_created_at?: () -> bool

    def restore_created_at!: () -> void

    def clear_created_at_change: () -> void

    def created_at_before_type_cast: () -> ::Time

    def created_at_for_database: () -> ::Time

    def updated_at: () -> ::ActiveSupport::TimeWithZone

    def updated_at=: (::ActiveSupport::TimeWithZone) -> ::ActiveSupport::TimeWithZone

    def updated_at?: () -> bool

    def updated_at_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def updated_at_change: () -> [ ::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone? ]

    def updated_at_will_change!: () -> void

    def updated_at_was: () -> ::ActiveSupport::TimeWithZone?

    def updated_at_previously_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def updated_at_previous_change: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def updated_at_previously_was: () -> ::ActiveSupport::TimeWithZone?

    def updated_at_before_last_save: () -> ::ActiveSupport::TimeWithZone?

    def updated_at_change_to_be_saved: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def updated_at_in_database: () -> ::ActiveSupport::TimeWithZone?

    def saved_change_to_updated_at: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def saved_change_to_updated_at?: () -> bool

    def will_save_change_to_updated_at?: () -> bool

    def restore_updated_at!: () -> void

    def clear_updated_at_change: () -> void

    def updated_at_before_type_cast: () -> ::Time

    def updated_at_for_database: () -> ::Time

    def status: () -> ::Integer

    def status=: (::Integer) -> ::Integer

    def status?: () -> bool

    def status_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def status_change: () -> [ ::Integer?, ::Integer? ]

    def status_will_change!: () -> void

    def status_was: () -> ::Integer?

    def status_previously_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def status_previous_change: () -> ::Array[::Integer?]?

    def status_previously_was: () -> ::Integer?

    def status_before_last_save: () -> ::Integer?

    def status_change_to_be_saved: () -> ::Array[::Integer?]?

    def status_in_database: () -> ::Integer?

    def saved_change_to_status: () -> ::Array[::Integer?]?

    def saved_change_to_status?: () -> bool

    def will_save_change_to_status?: () -> bool

    def restore_status!: () -> void

    def clear_status_change: () -> void

    def status_before_type_cast: () -> ::Integer

    def status_for_database: () -> ::Integer

    def priority: () -> ::String?

    def priority=: (::String?) -> ::String?

    def priority?: () -> bool

    def priority_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def priority_change: () -> [ ::String?, ::String? ]

    def priority_will_change!: () -> void

    def priority_was: () -> ::String?

    def priority_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def priority_previous_change: () -> ::Array[::String?]?

    def priority_previously_was: () -> ::String?

    def priority_before_last_save: () -> ::String?

    def priority_change_to_be_saved: () -> ::Array[::String?]?

    def priority_in_database: () -> ::String?

    def saved_change_to_priority: () -> ::Array[::String?]?

    def saved_change_to_priority?: () -> bool

    def will_save_change_to_priority?: () -> bool

    def restore_priority!: () -> void

    def clear_priority_change: () -> void

    def priority_before_type_cast: () -> ::String?

    def priority_for_database: () -> ::String?

    def category: () -> ::Integer?

    def category=: (::Integer?) -> ::Integer?

    def category?: () -> bool

    def category_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def category_change: () -> [ ::Integer?, ::Integer? ]

    def category_will_change!: () -> void

    def category_was: () -> ::Integer?

    def category_previously_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def category_previous_change: () -> ::Array[::Integer?]?

    def category_previously_was: () -> ::Integer?

    def category_before_last_save: () -> ::Integer?

    def category_change_to_be_saved: () -> ::Array[::Integer?]?

    def category_in_database: () -> ::Integer?

    def saved_change_to_category: () -> ::Array[::Integer?]?

    def saved_change_to_category?: () -> bool

    def will_save_change_to_category?: () -> bool

    def restore_category!: () -> void

    def clear_category_change: () -> void

    def category_before_type_cast: () -> ::Integer?

    def category_for_database: () -> ::Integer?

    def pinned: () -> bool

    def pinned=: (bool) -> bool

    def pinned?: () -> bool

    def pinned_changed?: (?from: bool?, ?to: bool?) -> bool

    def pinned_change: () -> [ bool?, bool? ]

    def pinned_will_change!: () -> void

    def pinned_was: () -> bool?

    def pinned_previously_changed?: (?from: bool?, ?to: bool?) -> bool

    def pinned_previous_change: () -> ::Array[bool?]?

    def pinned_previously_was: () -> bool?

    def pinned_before_last_save: () -> bool?

    def pinned_change_to_be_saved: () -> ::Array[bool?]?

    def pinned_in_database: () -> bool?

    def saved_change_to_pinned: () -> ::Array[bool?]?

    def saved_change_to_pinned?: () -> bool

    def will_save_change_to_pinned?: () -> bool

    def restore_pinned!: () -> void

    def clear_pinned_change: () -> void

    def pinned_before_type_cast: () -> bool

    def pinned_for_database: () -> bool
  end
  include ::Post::GeneratedAttributeMethods
  module ::Post::GeneratedAliasAttributeMethods
    include ::Post::GeneratedAttributeMethods

    alias id_value id

    alias id_value= id=

    alias id_value? id?

    alias id_value_changed? id_changed?

    alias id_value_change id_change

    alias id_value_will_change! id_will_change!

    alias id_value_was id_was

    alias id_value_previously_changed? id_previously_changed?

    alias id_value_previous_change id_previous_change

    alias id_value_previously_was id_previously_was

    alias id_value_before_last_save id_before_last_save

    alias id_value_change_to_be_saved id_change_to_be_saved

    alias id_value_in_database id_in_database

    alias saved_change_to_id_value saved_change_to_id

    alias saved_change_to_id_value? saved_change_to_id?

    alias will_save_change_to_id_value? will_save_change_to_id?

    alias restore_id_value! restore_id!

    alias clear_id_value_change clear_id_change

    alias id_value_before_type_cast id_before_type_cast

    alias id_value_for_database id_for_database
  end
  include ::Post::GeneratedAliasAttributeMethods
  def comments: () -> ::Comment::ActiveRecord_Associations_CollectionProxy
  def comments=: (::Comment::ActiveRecord_Associations_CollectionProxy | ::Array[::Comment]) -> (::Comment::ActiveRecord_Associations_CollectionProxy | ::Array[::Comment])
  def comment_ids: () -> ::Array[::Integer]
  def comment_ids=: (::Array[::Integer]) -> ::Array[::Integer]
  def post_tags: () -> ::PostTag::ActiveRecord_Associations_CollectionProxy
  def post_tags=: (::PostTag::ActiveRecord_Associations_CollectionProxy | ::Array[::PostTag]) -> (::PostTag::ActiveRecord_Associations_CollectionProxy | ::Array[::PostTag])
  def post_tag_ids: () -> ::Array[::Integer]
  def post_tag_ids=: (::Array[::Integer]) -> ::Array[::Integer]
  def tags: () -> ::Tag::ActiveRecord_Associations_CollectionProxy
  def tags=: (::Tag::ActiveRecord_Associations_CollectionProxy | ::Array[::Tag]) -> (::Tag::ActiveRecord_Associations_CollectionProxy | ::Array[::Tag])
  def tag_ids: () -> ::Array[::Integer]
  def tag_ids=: (::Array[::Integer]) -> ::Array[::Integer]

  def user: () -> ::User
  def user=: (::User?) -> ::User?
  def reload_user: () -> ::User?
  def build_user: (untyped) -> ::User
  def create_user: (untyped) -> ::User
  def create_user!: (untyped) -> ::User

  def self.pinned: () -> ::Post::ActiveRecord_Relation
  def self.unpinned: () -> ::Post::ActiveRecord_Relation
  def self.by_title: (untyped title) -> ::Post::ActiveRecord_Relation
  def self.by_body: (untyped body) -> ::Post::ActiveRecord_Relation
  def self.query_filter: (untyped filter) -> ::Post::ActiveRecord_Relation

  module ::Post::GeneratedRelationMethods
    def pinned: () -> ::Post::ActiveRecord_Relation

    def unpinned: () -> ::Post::ActiveRecord_Relation

    def by_title: (untyped title) -> ::Post::ActiveRecord_Relation

    def by_body: (untyped body) -> ::Post::ActiveRecord_Relation

    def query_filter: (untyped filter) -> ::Post::ActiveRecord_Relation
  end

  class ::Post::ActiveRecord_Relation < ::ActiveRecord::Relation
    include ::Enumerable[::Post]
    include ::Post::GeneratedRelationMethods
    include ::ActiveRecord::Relation::Methods[::Post, ::Integer]
  end

  class ::Post::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
    include ::Enumerable[::Post]
    include ::Post::GeneratedRelationMethods
    include ::ActiveRecord::Relation::Methods[::Post, ::Integer]

    def build: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::Post
             | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::Post]
    def create: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::Post
              | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::Post]
    def create!: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::Post
               | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::Post]
    def reload: () -> ::Array[::Post]

    def replace: (::Array[::Post]) -> void
    def delete: (*::Post | ::Integer) -> ::Array[::Post]
    def destroy: (*::Post | ::Integer) -> ::Array[::Post]
    def <<: (*::Post | ::Array[::Post]) -> self
    def prepend: (*::Post | ::Array[::Post]) -> self
  end
end

class ::ApplicationRecord < ::ActiveRecord::Base
end
class ::Comment < ::ApplicationRecord
end
class ::Comment::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
end
class ::PostTag < ::ApplicationRecord
end
class ::PostTag::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
end
class ::Tag < ::ApplicationRecord
end
class ::Tag::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
end
class ::User < ::ApplicationRecord
end
