# frozen_string_literal: true

module RbsInfer
  module Extensions
    module Rails
      module ActiveRecord
        module Runtime
          # Pseudo-code for what `ActiveSupport::Concern` runs on `include`.
          #
          # `included do … end` is the shape a Rails app actually writes, and until this
          # file existed nothing in a project said what it DOES. The `do … end` is stored,
          # and it is `append_features` — the other half, in another method — that replays
          # it on the includer. A reader who has both can see that the block's defs belong
          # to the host; a reader who has neither sees a method call with a block and
          # stops there, which is where `IncludedHook::Sugared` stopped.
          #
          # So the shape is already understood — `StoredBlockReplayExpander` reads a stored
          # block replayed on an argument, and #259 taught it to read both of the forwards
          # `Module#include` writes, which is exactly the pair Concern splits itself over.
          # Measured at #260: the chain resolves the moment `active_support/concern.rb` is
          # in the corpus, and the corpus is `app/ lib/ sig/`. Nothing was missing but the
          # source, and the source ships in a gem. This is that source, transcribed.
          #
          # Transcribed rather than summarised, for the reason the Ruby-runtime sidecar
          # gives: a paraphrase describes some other method. In particular
          #
          #   * the `@_dependencies` branch is what makes a concern included INTO a concern
          #     defer instead of splice, so it must not collapse to the else branch;
          #   * `super` in `append_features` is `Module#append_features`, which the Ruby
          #     runtime sidecar exists to give it;
          #   * `included` has two call forms — the DSL (`included do`, base nil) and Ruby's
          #     own hook (`included(base)`, no block) — and only the first stores anything.
          #     Writing one form drops the other, and `Module#include` calls both.
          #
          # Nothing here states a type, the same rule the Devise and AR-runtime generators
          # follow. `# @rbs_infer |...` (#200) makes each emitted signature RBS's overloading
          # form, because gem_rbs_collection already declares all three of these — a plain
          # redeclaration is a `DuplicatedMethodDefinitionError` that aborts the run.
          #
          # NOT transcribed, each for a reason rather than as an omission:
          #
          #   * `prepend_features` / `prepended` — their replay is reached from
          #     `Module#prepend`, which the Ruby runtime sidecar does not model, so writing
          #     them would emit a storage whose replay nothing reaches: dead pseudo-code
          #     that still has to type-check. They belong with `Module#prepend`, on the
          #     same day.
          #   * the `MultipleIncludedBlocks` guard around the store — it establishes
          #     nothing a caller can read back, being a raise on a programmer error, and
          #     it is the one line here that cannot be made to check without stating a
          #     type: `@_included_block.source_location != block.source_location` derefs
          #     two values this file never claims are non-nil (`instance_variable_defined?`
          #     does not narrow, and `&block` is optional because the OTHER call form
          #     passes none). A generated file ships into every app that runs the
          #     generator, so a diagnostic in it is one every one of those apps reads;
          #     the whole sidecar checks clean and stays that way.
          module ConcernPseudoCode
            FILENAME = "active_support/concern.rb"

            SOURCE = <<~RUBY
              # frozen_string_literal: true
              #
              # GENERATED by RbsInfer::Extensions::Rails::ActiveRecord::Runtime::ConcernPseudoCode.
              # Regenerated on every run; do not edit.

              module ActiveSupport
                # What `extend ActiveSupport::Concern` gives a module — transcribed from
                # activesupport's `lib/active_support/concern.rb`, which no project reads.
                module Concern
                  # `extend` runs this, and the ivar it sets is the flag `append_features`
                  # below tests to tell a concern from an ordinary includer.
                  #
                  # `Array.new` where the real source writes `[]`: an empty literal has no
                  # element to read a type off, and this file states none. Same value, and
                  # nothing below asks which expression produced it.
                  # @rbs_infer |...
                  def self.extended(base)
                    base.instance_variable_set(:@_dependencies, Array.new)
                  end

                  # The replay. `Module#include` calls this first (see the Ruby runtime
                  # sidecar), and the `class_eval` at the end is what puts the stored
                  # block's defs on the includer.
                  # @rbs_infer |...
                  def append_features(base)
                    if base.instance_variable_defined?(:@_dependencies)
                      # Included into another CONCERN: defer, so the block runs once, on
                      # whatever class eventually includes that one.
                      base.instance_variable_get(:@_dependencies) << self
                      false
                    else
                      return false if base < self

                      @_dependencies.each { |dep| base.include(dep) }
                      super
                      base.extend const_get(:ClassMethods) if const_defined?(:ClassMethods)
                      base.class_eval(&@_included_block) if instance_variable_defined?(:@_included_block)
                    end
                  end

                  # The storage, and both call forms. `included do … end` arrives with no
                  # base and a block, and keeps the block; `included(base)` is Ruby's hook
                  # arriving with a base and no block, and forwards to `Module#included`.
                  # @rbs_infer |...
                  def included(base = nil, &block)
                    if base.nil?
                      @_included_block = block
                    else
                      super
                    end
                  end
                end
              end
            RUBY

            module_function

            def file_entry(entry_class)
              entry_class.new(filename: FILENAME, source: SOURCE)
            end
          end
        end
      end
    end
  end
end
