module ActionText
  module Attribute
  end

  module Attribute::ClassMethods
    def has_rich_text: (untyped name, ?encrypted: untyped, ?strict_loading: untyped, ?store_if_blank: untyped) -> untyped | ...
  end
end

module ActiveRecord
  class Base
    extend ActionText::Attribute::ClassMethods
  end
end
