# frozen_string_literal: true

require "prism"
require "fileutils"

module RbsEnumerize
  class Generator
    attr_reader :app_dir, :output_dir

    def initialize(app_dir:, output_dir:)
      @app_dir = app_dir
      @output_dir = output_dir
    end

    def generate_all
      Dir.glob(File.join(app_dir, "app/models/**/*.rb")).sort.each do |model_path|
        generate_for_model(model_path)
      end
    end

    private

    def generate_for_model(model_path)
      source = File.read(model_path)
      result = Prism.parse(source)

      class_info = extract_class_info(result.value)
      return unless class_info

      enumerize_calls = extract_enumerize_calls(result.value)
      return if enumerize_calls.empty?

      rbs = build_rbs(class_info[:name], enumerize_calls)

      relative_path = model_path.sub("#{app_dir}/", "")
      output_path = File.join(output_dir, relative_path.sub(/\.rb\z/, ".rbs"))

      FileUtils.mkdir_p(File.dirname(output_path))
      File.write(output_path, rbs)
    end

    def extract_class_info(node)
      case node
      when Prism::ProgramNode
        extract_class_info(node.statements)
      when Prism::StatementsNode
        node.body.each do |child|
          info = extract_class_info(child)
          return info if info
        end
        nil
      when Prism::ClassNode
        { name: constant_path_to_string(node.constant_path) }
      else
        nil
      end
    end

    def constant_path_to_string(node)
      case node
      when Prism::ConstantReadNode
        node.name.to_s
      when Prism::ConstantPathNode
        parent = node.parent ? "#{constant_path_to_string(node.parent)}::" : ""
        "#{parent}#{node.name}"
      else
        node.to_s
      end
    end

    def extract_enumerize_calls(node)
      calls = []
      visit(node) do |n|
        if n.is_a?(Prism::CallNode) && n.name == :enumerize && n.receiver.nil?
          call_info = parse_enumerize_call(n)
          calls << call_info if call_info[:name]
        end
      end
      calls
    end

    def visit(node, &block)
      return unless node.is_a?(Prism::Node)

      yield node
      node.child_nodes.compact.each { |child| visit(child, &block) }
    end

    def parse_enumerize_call(call_node)
      args = call_node.arguments&.arguments || []

      info = { name: nil, values: [], predicates: false, scope: nil, multiple: false }

      args.each do |arg|
        case arg
        when Prism::SymbolNode
          info[:name] = arg.value
        when Prism::KeywordHashNode
          parse_keyword_args(arg, info)
        end
      end

      info
    end

    def parse_keyword_args(hash_node, info)
      hash_node.elements.each do |element|
        next unless element.is_a?(Prism::AssocNode)

        key_name = extract_symbol_value(element.key)
        next unless key_name

        case key_name
        when "in"
          info[:values] = extract_symbol_array(element.value)
        when "predicates"
          info[:predicates] = extract_predicates_option(element.value)
        when "scope"
          info[:scope] = extract_scope_option(element.value)
        when "multiple"
          info[:multiple] = element.value.is_a?(Prism::TrueNode)
        end
      end
    end

    def extract_symbol_value(node)
      case node
      when Prism::SymbolNode
        node.value
      end
    end

    def extract_symbol_array(node)
      case node
      when Prism::ArrayNode
        node.elements.filter_map { |el| extract_symbol_value(el) }
      else
        []
      end
    end

    def extract_predicates_option(node)
      case node
      when Prism::TrueNode
        true
      when Prism::FalseNode
        false
      when Prism::HashNode
        parse_predicates_hash(node.elements)
      else
        false
      end
    end

    def parse_predicates_hash(elements)
      opts = { prefix: false, only: nil, except: nil }

      elements.each do |el|
        next unless el.is_a?(Prism::AssocNode)

        key = extract_symbol_value(el.key)
        case key
        when "prefix"
          opts[:prefix] = el.value.is_a?(Prism::TrueNode)
        when "only"
          opts[:only] = extract_symbol_array(el.value)
        when "except"
          opts[:except] = extract_symbol_array(el.value)
        end
      end

      opts
    end

    def extract_scope_option(node)
      case node
      when Prism::TrueNode
        :deep
      when Prism::SymbolNode
        node.value.to_sym
      else
        nil
      end
    end

    def build_rbs(class_name, enumerize_calls)
      lines = []
      lines << "# Generated by rbs_enumerize"
      lines << ""
      lines << "class ::#{class_name}"

      enumerize_calls.each do |call|
        call[:relation_type] = "#{class_name}::ActiveRecord_Relation"
        lines.concat(build_instance_methods(call))
        lines.concat(build_predicate_methods(call))
        lines.concat(build_scope_methods(call))
      end

      lines << "end"
      lines << ""
      lines.join("\n")
    end

    def build_instance_methods(call)
      attr_name = call[:name]
      lines = []

      if call[:multiple]
        lines << "  def #{attr_name}: () -> Enumerize::Set"
      else
        lines << "  def #{attr_name}: () -> Enumerize::Value?"
      end

      lines << "  def #{attr_name}=: (String | Symbol | nil) -> (String | Symbol | nil)"
      lines << "  def #{attr_name}_text: () -> String?"
      lines << "  def #{attr_name}_value: () -> String?"
      lines << ""

      lines
    end

    def build_predicate_methods(call)
      return [] unless call[:predicates]

      lines = []
      values = predicate_values(call)
      prefix = predicate_prefix(call)

      values.each do |value|
        method_name = prefix ? "#{call[:name]}_#{value}?" : "#{value}?"
        lines << "  def #{method_name}: () -> bool"
      end

      lines << "" unless lines.empty?
      lines
    end

    def predicate_values(call)
      values = call[:values]
      preds = call[:predicates]

      return values unless preds.is_a?(Hash)

      if preds[:only]
        values.select { |v| preds[:only].include?(v) }
      elsif preds[:except]
        values.reject { |v| preds[:except].include?(v) }
      else
        values
      end
    end

    def predicate_prefix(call)
      preds = call[:predicates]
      preds.is_a?(Hash) && preds[:prefix]
    end

    def build_scope_methods(call)
      return [] unless call[:scope]

      lines = []

      case call[:scope]
      when :shallow
        call[:values].each do |value|
          lines << "  def self.#{value}: () -> #{call[:relation_type]}"
          lines << "  def self.not_#{value}: () -> #{call[:relation_type]}"
        end
      when :deep
        lines << "  def self.with_#{call[:name]}: (*String | Symbol) -> #{call[:relation_type]}"
        lines << "  def self.without_#{call[:name]}: (*String | Symbol) -> #{call[:relation_type]}"
      end

      lines << "" unless lines.empty?
      lines
    end
  end
end
