# frozen_string_literal: true
#
# GENERATED by RbsInfer::Extensions::Rails::Views::RuntimeGenerator.
# Regenerated on every run; do not edit.

class ERBLayoutsApplication
  include ActionViewContext

  def params
    ActionController::Parameters.new
  end

  def __rbs_infer__body
    nil
  end
end
