---
postconditions:
- class: Comment
  method: save
  when_true:
    self: Comment & Comment::Validated
- class: Comment
  method: save!
  when_true:
    self: Comment & Comment::Validated
- class: Comment
  method: update
  when_true:
    self: Comment & Comment::Validated
- class: Comment
  method: update!
  when_true:
    self: Comment & Comment::Validated
- class: Comment
  method: valid?
  when_true:
    self: Comment & Comment::Validated
- class: Post
  method: save
  when_true:
    self: Post & Post::Validated
- class: Post
  method: save!
  when_true:
    self: Post & Post::Validated
- class: Post
  method: update
  when_true:
    self: Post & Post::Validated
- class: Post
  method: update!
  when_true:
    self: Post & Post::Validated
- class: Post
  method: valid?
  when_true:
    self: Post & Post::Validated
- class: PostTag
  method: save
  when_true:
    self: PostTag & PostTag::Validated
- class: PostTag
  method: save!
  when_true:
    self: PostTag & PostTag::Validated
- class: PostTag
  method: update
  when_true:
    self: PostTag & PostTag::Validated
- class: PostTag
  method: update!
  when_true:
    self: PostTag & PostTag::Validated
- class: PostTag
  method: valid?
  when_true:
    self: PostTag & PostTag::Validated
- class: Tag
  method: save
  when_true:
    self: Tag & Tag::Validated
- class: Tag
  method: save!
  when_true:
    self: Tag & Tag::Validated
- class: Tag
  method: update
  when_true:
    self: Tag & Tag::Validated
- class: Tag
  method: update!
  when_true:
    self: Tag & Tag::Validated
- class: Tag
  method: valid?
  when_true:
    self: Tag & Tag::Validated
- class: User
  method: save
  when_true:
    self: User & User::Validated
- class: User
  method: save!
  when_true:
    self: User & User::Validated
- class: User
  method: update
  when_true:
    self: User & User::Validated
- class: User
  method: update!
  when_true:
    self: User & User::Validated
- class: User
  method: valid?
  when_true:
    self: User & User::Validated
