---
version: 1
callbacks:
- class: Comment
  applies_self: Comment & Comment::Validated
  runs_before:
  - notify_post_author
- class: Posts::AssignmentsController
  apply_postcondition_of: set_post
  runs_before:
  - create
- class: PostsController
  apply_postcondition_of: set_post
  runs_before:
  - show
  - update
  - destroy
  - publish
- class: Users::AvatarsController
  apply_postcondition_of: set_user
  runs_before:
  - edit
  - update
