# frozen_string_literal: true

require "fileutils"
require "yaml"
require "active_support/core_ext/string/inflections"
require_relative "before_action_scanner"
require_relative "../../rbs_parser_util"

module RbsInfer
  module Extensions
    module Rails
      # CurrentAttributes-side consumer of guarded-callback facts
      # (felixefelip/steep#41): when a guarded before_action handler writes
      # `Current.user = current_user`, every action running after it reads
      # a proven-present `Current.user`. This generator owns the
      # CurrentAttributes artifacts:
      #
      # - `populated_markers.rbs` — `Current::UserPopulated` marker modules
      #   declaring the populated attribute as proven present.
      # - `.steep_callbacks.yml` — `applies_constants` entries narrowing
      #   reads of the constant inside guarded actions.
      #
      # The PROOF comes from the auth layer: `resource_types` maps each
      # guard scope to the proven type of its helper (today emitted by the
      # Devise extension; any auth system able to assert "current_<scope>
      # is non-nil under the guard" can feed this). Keeping the consumer
      # here separates the CurrentAttributes domain from Devise's.
      class CurrentAttributesCallbacksGenerator
        attr_reader :app_dir, :output_dir, :scanner, :resource_types

        # resource_types: { "user" => "(User & User::Validated)" } — the
        # proven (non-nil) type of `current_<scope>` under the guard.
        def initialize(app_dir:, output_dir:, scanner:, resource_types:)
          @app_dir = app_dir
          @output_dir = output_dir
          @scanner = scanner
          @resource_types = resource_types
        end

        # Returns the populated-constant facts ([] when no guarded handler
        # populates a constant — nothing is written in that case).
        def generate_all
          populated = scanner.populated_constants
          markers_path = File.join(output_dir, "populated_markers.rbs")
          sidecar_path = File.join(output_dir, ".steep_callbacks.yml")

          if populated.empty?
            FileUtils.rm_f(markers_path)
            FileUtils.rm_f(sidecar_path)
            return []
          end

          FileUtils.mkdir_p(output_dir)
          File.write(markers_path, markers_rbs(populated))
          File.write(sidecar_path, sidecar_yaml(populated))
          populated
        end

        private

        def markers_rbs(populated)
          lines = []
          lines << "# Generated by rbs_infer (current_attributes)"
          lines << "#"
          lines << "# Markers for `applies_constants` (felixefelip/steep#41): inside"
          lines << "# guarded actions, global state populated by a before_action"
          lines << "# handler is proven present."
          populated.group_by { |c| c[:const_name] }.each do |const_name, writes|
            lines << ""
            lines << "class #{const_name}"
            writes.uniq { |c| c[:attr] }.each_with_index do |c, idx|
              lines << "" if idx.positive?
              lines << "  module #{marker_name(c)}"
              lines << "    def #{c[:attr]}: () -> #{RbsParserUtil.parenthesize_compound(resource_types.fetch(c[:scope]))}"
              lines << "  end"
            end
            lines << "end"
          end
          lines.join("\n") + "\n"
        end

        # One constants-only entry per guarded controller that descends
        # from the populating handler's class. The Devise-side sidecar
        # carries the `applies_self` narrowing for the same methods; the
        # Steep callbacks loader merges entries across sidecar files.
        def sidecar_yaml(populated)
          entries = scanner.guarded_controllers.filter_map do |controller|
            constants = populated.select do |p|
              p[:scope] == controller[:scope] && scanner.descends_from?(controller[:class_name], p[:defining_class])
            end
            next if constants.empty?

            {
              "class" => controller[:class_name],
              "applies_constants" => constants.to_h do |c|
                [c[:const_name], "singleton(#{c[:const_name]}) & #{c[:const_name]}::#{marker_name(c)}"]
              end,
              "runs_before" => controller[:actions],
            }
          end

          { "version" => 1, "callbacks" => entries }.to_yaml
        end

        def marker_name(constant)
          "#{constant[:attr].camelize}Populated"
        end
      end
    end
  end
end
