# frozen_string_literal: true

require "fileutils"
require "prism"
require_relative "current_attributes_expander"

module RbsInfer
  module Extensions
    module Rails
      # Emits a plain-Ruby reopen of every ActiveSupport::CurrentAttributes
      # subclass whose singleton setter should delegate to the instance one
      # (felixefelip/steep#68 item 5):
      #
      #   class Current
      #     def self.user=(value)
      #       @user = value
      #       instance.user = value
      #     end
      #   end
      #
      # At runtime `Current.user = x` DOES delegate to the singleton instance's
      # `user=`, so a `user=` override (`self.author_name = value&.full_name`)
      # runs — meaning `Current.user = <non-nil>` also establishes
      # `Current.author_name`. Modelling the delegation as visible pseudo-code
      # lets the Steep fork prove that transitively, without teaching it what
      # CurrentAttributes is: it just reads the delegation and follows the
      # instance setter.
      #
      # Only emitted for a subclass with at least one attribute whose instance
      # setter the class OVERRIDES — a plain attribute's setter establishes
      # nothing, so the delegation would add only noise.
      class CurrentAttributesRuntimeGenerator
        # NOT dot-prefixed: `.rb` SOURCE the Steep fork type-checks via its
        # `check "sig/**/*.rb"` glob (`**` skips hidden dirs).
        SIDECAR_DIR = "sig/generated/steep_current_runtime"
        MODEL_ROOTS = %w[app/models].freeze

        Reopen = Struct.new(:class_name, :attributes, keyword_init: true)

        def initialize(app_dir:)
          @app_dir = app_dir
        end

        # => [{ filename:, source: }] (empty when nothing qualifies).
        def build
          reopens.map do |reopen|
            {
              filename: "#{RbsInfer.class_name_to_path(reopen.class_name).tr("/", "_")}.rb",
              source: reopen_source(reopen)
            }
          end
        end

        # Writes the sidecar dir (one file per reopen), removing a stale dir when
        # nothing qualifies. Returns the sidecar dir path.
        def generate
          files = build
          dir = File.join(@app_dir, SIDECAR_DIR)

          FileUtils.rm_rf(dir)
          unless files.empty?
            FileUtils.mkdir_p(dir)
            files.each { |file| File.write(File.join(dir, file[:filename]), file[:source]) }
          end

          dir
        end

        private

        def reopens
          Dir.glob(File.join(@app_dir, "app/models/**/*.rb")).sort.filter_map do |path|
            source = File.read(path)
            next unless source.include?("CurrentAttributes")

            reopen_for(source)
          end
        end

        # The subclass name + the attributes with an OVERRIDDEN instance setter
        # (`def user=`), or nil when none qualify.
        def reopen_for(source)
          result = Prism.parse(source)
          return nil unless result.success?

          klass = RbsInfer::Analyzer.find_all_nodes(result.value) { |n| n.is_a?(Prism::ClassNode) }
                                    .find { |n| CurrentAttributesExpander.current_attributes_subclass?(n) }
          return nil unless klass

          class_name = RbsInfer::Analyzer.extract_constant_path(klass.constant_path)&.delete_prefix("::")
          return nil unless class_name

          names = CurrentAttributesExpander.attribute_names(source)
          overridden = names.select { |name| instance_setter_override?(klass, name) }
          return nil if overridden.empty?

          Reopen.new(class_name: class_name, attributes: overridden)
        end

        # Whether the class body defines `def <name>=` itself (an override of the
        # generated instance setter — the one that establishes other attributes).
        def instance_setter_override?(klass, name)
          statements(klass.body).any? do |stmt|
            stmt.is_a?(Prism::DefNode) && stmt.receiver.nil? && stmt.name.to_s == "#{name}="
          end
        end

        def reopen_source(reopen)
          setters = reopen.attributes.map do |name|
            [
              "  def self.#{name}=(value)",
              "    @#{name} = value",
              "    instance.#{name} = value",
              "  end"
            ].join("\n")
          end

          <<~RUBY
            # frozen_string_literal: true
            #
            # GENERATED by RbsInfer::Extensions::Rails::CurrentAttributesRuntimeGenerator.
            # Regenerated on every run; do not edit.

            class #{reopen.class_name}
            #{setters.join("\n\n")}
            end
          RUBY
        end

        def statements(body)
          case body
          when Prism::StatementsNode then body.body
          when nil then []
          else [body]
          end
        end
      end
    end
  end
end
