# frozen_string_literal: true

require "prism"
require "fileutils"
require_relative "../../../rbs_infer"
require_relative "erb_convention_generator/view_path_naming"
require_relative "erb_convention_generator/controller_analyzer"
require_relative "erb_convention_generator/partial_locals_collector"

module RbsInfer
  module Extensions
    module Rails
      class ErbConventionGenerator
        include ViewPathNaming
        include ControllerAnalyzer
        include PartialLocalsCollector

        attr_reader :app_dir, :output_dir, :source_files

        def initialize(app_dir:, output_dir:, source_files: nil)
          @app_dir = app_dir
          @output_dir = output_dir
          @source_files = source_files || Dir[File.join(app_dir, "app/**/*.rb")]
        end

        def generate_all
          erb_files = Dir[File.join(@app_dir, "app/views/**/*.{html,turbo_stream}.erb")].sort

          # Phase 1: collect partial locals from render call sites
          @partial_locals = collect_partial_locals(erb_files)

          erb_files.each { |erb_path| generate_for_erb(erb_path) }
        end

        private

        def generate_for_erb(erb_path)
          relative = erb_path.sub("#{@app_dir}/", "")
          view_relative = relative.sub(%r{\Aapp/views/}, "")
          class_name = erb_class_name(view_relative)
          return unless class_name

          view_info = parse_view_path(view_relative)
          ivar_types = {}
          local_types = {}

          if view_info
            controller_file = find_controller_file(view_info[:controller_name])
            if controller_file
              ivar_types = extract_action_ivars(
                controller_file,
                view_info[:controller_class],
                view_info[:action]
              )
            end
          else
            # Partial: resolve locals from render call sites
            partial_key = partial_key_from_view_relative(view_relative)
            local_types = @partial_locals[partial_key] || {} if partial_key
          end

          helpers = detect_helpers(view_info)
          helper_methods = collect_helper_methods(view_info)
          rbs = build_rbs(class_name, ivar_types, local_types, helpers, helper_methods)

          output_subpath = relative.sub(/\.(html|turbo_stream)\.erb\z/, ".rbs")
          output_path = File.join(@output_dir, output_subpath)
          FileUtils.mkdir_p(File.dirname(output_path))
          File.write(output_path, rbs)
        end

        def build_rbs(class_name, ivar_types, local_types, helpers, helper_methods = {})
          lines = ["# Generated by rbs_infer (erb_convention)", ""]
          lines << "class #{class_name}"

          ivar_types.each do |name, type|
            lines << "  @#{name}: #{type}"
          end

          local_types.each do |name, type|
            lines << "  attr_reader #{name}: #{type}"
          end

          helper_methods.each do |name, signature|
            lines << "  def #{name}: #{signature}"
          end

          lines << "  def params: () -> ActionController::Parameters"

          helpers.each do |helper|
            lines << "  include #{helper}"
          end

          lines << "end"
          lines.join("\n") + "\n"
        end
      end
    end
  end
end
