# frozen_string_literal: true
#
# GENERATED by RbsInfer::Extensions::Rails::ActiveRecord::Runtime::ConcernPseudoCode.
# Regenerated on every run; do not edit.

module ActiveSupport
  # What `extend ActiveSupport::Concern` gives a module — transcribed from
  # activesupport's `lib/active_support/concern.rb`, which no project reads.
  module Concern
    # `extend` runs this, and the ivar it sets is the flag `append_features`
    # below tests to tell a concern from an ordinary includer.
    #
    # `Array.new` where the real source writes `[]`: an empty literal has no
    # element to read a type off, and this file states none. Same value, and
    # nothing below asks which expression produced it.
    # @rbs_infer |...
    def self.extended(base)
      base.instance_variable_set(:@_dependencies, Array.new)
    end

    # The replay. `Module#include` calls this first (see the Ruby runtime
    # sidecar), and the `class_eval` at the end is what puts the stored
    # block's defs on the includer.
    # @rbs_infer |...
    def append_features(base)
      if base.instance_variable_defined?(:@_dependencies)
        # Included into another CONCERN: defer, so the block runs once, on
        # whatever class eventually includes that one.
        base.instance_variable_get(:@_dependencies) << self
        false
      else
        return false if base < self

        @_dependencies.each { |dep| base.include(dep) }
        super
        base.extend const_get(:ClassMethods) if const_defined?(:ClassMethods)
        base.class_eval(&@_included_block) if instance_variable_defined?(:@_included_block)
      end
    end

    # What `class_methods do … end` runs, transcribed from
    # activesupport: fetch the module if the concern already has one,
    # build it if not, and evaluate the block into it. `append_features`
    # above is what then hands it to the includer.
    #
    # `const_defined?(:ClassMethods, false)` in the real source; the
    # second argument only excludes ancestors, which nothing here reads
    # either way.
    # @rbs_infer |...
    def class_methods(&class_methods_module_definition)
      mod = const_defined?(:ClassMethods) ? const_get(:ClassMethods) : const_set(:ClassMethods, Module.new)

      mod.module_eval(&class_methods_module_definition)
    end

    # The storage, and both call forms. `included do … end` arrives with no
    # base and a block, and keeps the block; `included(base)` is Ruby's hook
    # arriving with a base and no block, and forwards to `Module#included`.
    # @rbs_infer |...
    def included(base = nil, &block)
      if base.nil?
        @_included_block = block
      else
        super
      end
    end
  end
end
