# frozen_string_literal: true

require "spec_helper"
require "tmpdir"
require "fileutils"
require "rbs_infer/extensions/carrierwave/generator"

RSpec.describe RbsInfer::Extensions::CarrierWave::Generator do
  let(:app_dir) { Dir.mktmpdir }
  let(:output_dir) { File.join(app_dir, "sig/rbs_carrierwave") }
  let(:rbs_rails_dir) { File.join(app_dir, "sig/rbs_rails") }

  after { FileUtils.remove_entry(app_dir) }

  def write_model(relative_path, source)
    full_path = File.join(app_dir, relative_path)
    FileUtils.mkdir_p(File.dirname(full_path))
    File.write(full_path, source)
    full_path
  end

  def write_rbs_rails(relative_path, content)
    full_path = File.join(rbs_rails_dir, relative_path)
    FileUtils.mkdir_p(File.dirname(full_path))
    File.write(full_path, content)
    full_path
  end

  def generated_rbs(relative_path)
    File.read(File.join(output_dir, relative_path))
  end

  def run_generator
    RbsInfer::Extensions::CarrierWave::Generator.new(
      app_dir: app_dir,
      output_dir: output_dir,
      rbs_rails_dir: rbs_rails_dir
    ).generate_all
  end

  describe "mount_uploader (singular)" do
    before do
      write_model("app/models/user.rb", <<~RUBY)
        class User < ApplicationRecord
          mount_uploader :avatar, AvatarUploader
        end
      RUBY
    end

    it "emits a class reopener with the uploader as the getter return" do
      run_generator
      rbs = generated_rbs("app/models/user.rbs")

      expect(rbs).to start_with("# Generated by rbs_infer (carrierwave)\n\nclass ::User\n")
      expect(rbs).to include("def avatar: () -> ::AvatarUploader")
      expect(rbs).to include("def avatar=: (untyped) -> untyped")
      expect(rbs).to include("def avatar?: () -> bool")
    end

    it "emits the URL and identifier readers" do
      run_generator
      rbs = generated_rbs("app/models/user.rbs")

      expect(rbs).to include("def avatar_url: (*::Symbol) -> ::String?")
      expect(rbs).to include("def avatar_identifier: () -> ::String?")
    end

    it "emits the cache and remote-url accessors" do
      run_generator
      rbs = generated_rbs("app/models/user.rbs")

      expect(rbs).to include("def avatar_cache: () -> ::String?")
      expect(rbs).to include("def avatar_cache=: (::String?) -> ::String?")
      expect(rbs).to include("def remote_avatar_url: () -> ::String?")
      expect(rbs).to include("def remote_avatar_url=: (::String?) -> ::String?")
      expect(rbs).to include("def remote_avatar_request_header=: (untyped) -> untyped")
    end

    it "emits the lifecycle methods shared with the plural form" do
      run_generator
      rbs = generated_rbs("app/models/user.rbs")

      %w[
        remove_avatar
        remove_avatar=
        remove_avatar?
        remove_avatar!
        store_avatar!
        write_avatar_identifier
      ].each do |method|
        expect(rbs).to match(/^\s+def #{Regexp.escape(method)}:/), "missing def #{method}"
      end
    end

    it "emits singular and plural error readers with specific CarrierWave error types" do
      run_generator
      rbs = generated_rbs("app/models/user.rbs")

      expect(rbs).to include("def avatar_integrity_error: () -> ::CarrierWave::IntegrityError?")
      expect(rbs).to include("def avatar_processing_error: () -> ::CarrierWave::ProcessingError?")
      expect(rbs).to include("def avatar_download_error: () -> ::CarrierWave::DownloadError?")
      expect(rbs).to include("def avatar_integrity_errors: () -> ::Array[::CarrierWave::IntegrityError]")
      expect(rbs).to include("def avatar_processing_errors: () -> ::Array[::CarrierWave::ProcessingError]")
      expect(rbs).to include("def avatar_download_errors: () -> ::Array[::CarrierWave::DownloadError]")
    end

    it "emits the after_commit callback methods" do
      run_generator
      rbs = generated_rbs("app/models/user.rbs")

      expect(rbs).to include("def mark_remove_avatar_false: () -> void")
      expect(rbs).to include("def reset_previous_changes_for_avatar: () -> void")
      expect(rbs).to include("def remove_previously_stored_avatar: () -> void")
      expect(rbs).to include("def remove_rolled_back_avatar: () -> void")
    end

    it "does not emit the inexistent store_previous_changes_for_<col>" do
      run_generator
      rbs = generated_rbs("app/models/user.rbs")
      expect(rbs).not_to include("store_previous_changes_for_avatar")
    end

    it "strips conflicting plain accessors from sig/rbs_rails/ but keeps dirty-state methods" do
      write_rbs_rails("app/models/user.rbs", <<~RBS)
        class User
          module GeneratedAttributeMethods
            def avatar: () -> ::String?
            def avatar=: (::String?) -> ::String?
            def avatar?: () -> bool
            def avatar_changed?: (?from: ::String?, ?to: ::String?) -> bool
            def avatar_was: () -> ::String?
            def avatar_before_type_cast: () -> ::String?
          end
        end
      RBS

      run_generator
      stripped = File.read(File.join(rbs_rails_dir, "app/models/user.rbs"))

      expect(stripped).not_to match(/^\s+def avatar:/)
      expect(stripped).not_to match(/^\s+def avatar=:/)
      expect(stripped).not_to match(/^\s+def avatar\?:/)
      expect(stripped).to match(/^\s+def avatar_changed\?:/)
      expect(stripped).to match(/^\s+def avatar_was:/)
      expect(stripped).to match(/^\s+def avatar_before_type_cast:/)
    end
  end

  describe "mount_uploaders (plural)" do
    before do
      write_model("app/models/gallery.rb", <<~RUBY)
        class Gallery < ApplicationRecord
          mount_uploaders :photos, PhotoUploader
        end
      RUBY
    end

    it "emits Array-typed getter and pluralized url/identifier readers" do
      run_generator
      rbs = generated_rbs("app/models/gallery.rbs")

      expect(rbs).to start_with("# Generated by rbs_infer (carrierwave)\n\nclass ::Gallery\n")
      expect(rbs).to include("def photos: () -> ::Array[::PhotoUploader]")
      expect(rbs).to include("def photos=: (untyped) -> untyped")
      expect(rbs).to include("def photos?: () -> bool")
      expect(rbs).to include("def photos_urls: (*::Symbol) -> ::Array[::String]")
      expect(rbs).to include("def photos_identifiers: () -> ::Array[::String]")
    end

    it "emits pluralized remote-urls accessor (not singular)" do
      run_generator
      rbs = generated_rbs("app/models/gallery.rbs")

      expect(rbs).to include("def remote_photos_urls: () -> ::Array[::String]")
      expect(rbs).to include("def remote_photos_urls=: (::Array[::String]) -> ::Array[::String]")
      expect(rbs).to include("def remote_photos_request_headers=: (untyped) -> untyped")

      expect(rbs).not_to include("def remote_photos_url:")
      expect(rbs).not_to include("def remote_photos_url=:")
    end

    it "shares the lifecycle methods with the singular form" do
      run_generator
      rbs = generated_rbs("app/models/gallery.rbs")

      %w[
        remove_photos
        remove_photos=
        remove_photos?
        remove_photos!
        store_photos!
        write_photos_identifier
      ].each do |method|
        expect(rbs).to match(/^\s+def #{Regexp.escape(method)}:/), "missing def #{method}"
      end
    end

    it "emits only the plural error collections (no singular *_error)" do
      run_generator
      rbs = generated_rbs("app/models/gallery.rbs")

      expect(rbs).to include("def photos_integrity_errors: () -> ::Array[::CarrierWave::IntegrityError]")
      expect(rbs).to include("def photos_processing_errors: () -> ::Array[::CarrierWave::ProcessingError]")
      expect(rbs).to include("def photos_download_errors: () -> ::Array[::CarrierWave::DownloadError]")

      expect(rbs).not_to match(/^\s+def photos_integrity_error:/)
      expect(rbs).not_to match(/^\s+def photos_processing_error:/)
      expect(rbs).not_to match(/^\s+def photos_download_error:/)
    end

    it "emits the after_commit callback methods" do
      run_generator
      rbs = generated_rbs("app/models/gallery.rbs")

      expect(rbs).to include("def mark_remove_photos_false: () -> void")
      expect(rbs).to include("def reset_previous_changes_for_photos: () -> void")
      expect(rbs).to include("def remove_previously_stored_photos: () -> void")
      expect(rbs).to include("def remove_rolled_back_photos: () -> void")
    end
  end

  describe "edge cases" do
    it "skips models without any mount call" do
      write_model("app/models/post.rb", "class Post < ApplicationRecord; end")
      run_generator

      expect(File.exist?(File.join(output_dir, "app/models/post.rbs"))).to be false
    end

    it "emits multiple class reopenings when a model mounts more than one uploader" do
      write_model("app/models/profile.rb", <<~RUBY)
        class Profile < ApplicationRecord
          mount_uploader :avatar, AvatarUploader
          mount_uploader :banner, BannerUploader
        end
      RUBY

      run_generator
      rbs = generated_rbs("app/models/profile.rbs")

      expect(rbs).to include("def avatar: () -> ::AvatarUploader")
      expect(rbs).to include("def banner: () -> ::BannerUploader")
      expect(rbs).to include("def avatar_url: ")
      expect(rbs).to include("def banner_url: ")
    end

    it "supports models inside a namespace" do
      write_model("app/models/admin/user.rb", <<~RUBY)
        class Admin::User < ApplicationRecord
          mount_uploader :avatar, Admin::AvatarUploader
        end
      RUBY

      run_generator
      rbs = generated_rbs("app/models/admin/user.rbs")

      expect(rbs).to include("class ::Admin::User")
      expect(rbs).to include("def avatar: () -> ::Admin::AvatarUploader")
    end

    it "ignores method calls named mount_uploader on a receiver" do
      write_model("app/models/decoy.rb", <<~RUBY)
        class Decoy < ApplicationRecord
          some_object.mount_uploader(:avatar, AvatarUploader)
        end
      RUBY

      run_generator
      expect(File.exist?(File.join(output_dir, "app/models/decoy.rbs"))).to be false
    end
  end
end
