# frozen_string_literal: true

require "prism"

module RbsInfer
  module Extensions
    module Rails
      module ActiveRecord
        module BelongsToDefault
          # Turns the scanned reflections + construction sites into the
          # `example.rb`-shaped synthetic program Steep checks, and the
          # source-map linking each inlined `default:` lambda back to its real
          # span (felixefelip/rbs_infer#72 / felixefelip/steep#54).
          #
          # Each synthetic class is emitted to its OWN file (a `FileEntry`) so
          # the sidecar is a directory of small, readable units rather than one
          # blob. Every class carries the `RbsInferBelongsToDefault` prefix so
          # it never collides with the real app classes, and is a top-level
          # class (not nested in a wrapper module) because the analyzer's
          # multi-class discovery only walks top-level classes.
          class ExpansionBuilder
            PREFIX = "RbsInferBelongsToDefault"

            # One emitted file: `filename` is the basename within the sidecar
            # directory; `source` is the standalone Ruby.
            FileEntry = Struct.new(:class_name, :filename, :source, keyword_init: true)

            # files:      [FileEntry] — one per synthetic class.
            # source_map: [{ expanded_file:, expanded_line:, original_* }] —
            #             each inlined `default:` deref back to its real span.
            Result = Struct.new(:files, :source_map, keyword_init: true) do
              # The whole expansion as one string — the per-class files are
              # independent top-level classes, so concatenation is equivalent
              # for a Steep check. Used by end-to-end scenarios.
              def combined_source
                files.map(&:source).join("\n")
              end
            end

            # models: the belongs_to-default models (get lifecycle + witness).
            # all_models: every scanned model (unused today; kept so a future
            #   deeper deref resolution can consult the full graph).
            # sites: [ConstructionSite].
            def initialize(models:, all_models:, sites:)
              @models = models
              @all_models = all_models
              @sites = sites
              @files = []
              @source_map = []
            end

            def build
              emit_target_classes
              @models.each { |model| emit_model(model) }
              emit_runner

              Result.new(files: @files, source_map: @source_map)
            end

            private

            # Collects the lines of one class into a FileEntry. `@lines` /
            # `@filename` / `@depth` are the per-file accumulators an `emit_*`
            # writes into; `current_line` is 1-based within the file for the
            # source-map. `emit` indents by the current nesting depth, so the
            # `emit_*` helpers never hardcode leading spaces.
            def in_file(class_name)
              @lines = []
              @filename = "#{syn(class_name)}.rb"
              @depth = 0
              emit "# frozen_string_literal: true"
              emit "#"
              emit "# GENERATED by RbsInfer::Extensions::Rails::ActiveRecord::BelongsToDefaultGenerator."
              emit "# Regenerated on every run; do not edit."
              emit ""
              yield
              @files << FileEntry.new(class_name: class_name, filename: @filename, source: "#{@lines.join("\n")}\n")
            end

            def emit(line)
              @lines << (line.empty? ? "" : ("  " * @depth) + line)
            end

            def indent
              @depth += 1
              yield
              @depth -= 1
            end

            def current_line
              @lines.length + 1
            end

            def emit_class(name)
              emit "class #{name}"
              @member_started = false
              indent { yield }
              emit "end"
            end

            # Wraps one class member (an `attr_accessor` or a method), emitting a
            # blank separator line before every member after the first — so the
            # class reads with a blank line between the accessor and the methods
            # and between each method, with no trailing blank before `end`.
            def member
              emit "" if @member_started
              @member_started = true
              yield
            end

            def emit_method(name)
              emit "def #{name}"
              indent { yield }
              emit "end"
            end

            def emit_singleton_method(name)
              emit "def self.#{name}"
              indent { yield }
              emit "end"
            end

            # --- Synthetic belongs_to target classes -------------------------
            #
            # One class per belongs_to target of a default model — every one is
            # `.new`'d by the witness/sites, so all must exist. A target used as
            # a deref receiver in a lambda body (`post` → `Post`) also gets a
            # stub for each method called directly on that receiver (`post.user`
            # → `def user; raise; end`). A `raise` body returns `bot` (⊥), so any
            # DEEPER chain (`post.user.name`) rides on it and type-checks — while
            # the FIRST hop on a nilable `post` still errors, which is exactly
            # the diagnostic we cover.
            def emit_target_classes
              stubs = target_method_stubs
              target_class_names.each do |class_name|
                in_file(class_name) do
                  emit_class(syn(class_name)) do
                    (stubs[class_name] || []).sort.each { |method| member { emit_method(method) { emit "raise" } } }
                  end
                end
              end
            end

            # Every belongs_to target across the default models (deduped, stable
            # order). These are the classes referenced by `attr_accessor`
            # setters and constructed in the runner.
            def target_class_names
              @models.flat_map { |m| m.belongs_to.map(&:class_name) }.uniq.sort
            end

            # target class name => Set of method names called on a belongs_to
            # receiver of that class, across every default lambda.
            def target_method_stubs
              stubs = Hash.new { |h, k| h[k] = [] }
              @models.each do |model|
                belongs_by_name = model.belongs_to.to_h { |b| [b.name, b.class_name] }
                model.default_associations.each do |default|
                  deref_calls(default.default_body).each do |recv_name, method|
                    target = belongs_by_name[recv_name]
                    next unless target

                    stubs[target] << method unless stubs[target].include?(method)
                  end
                end
              end
              stubs
            end

            # [[receiver_name, method], ...] for `receiver.method` calls in a
            # lambda body where `receiver` is a bare (receiverless) name — the
            # shape of a `belongs_to` deref. Deeper hops are ignored here (they
            # ride on the ⊥ return of the first hop's stub).
            def deref_calls(body_source)
              result = Prism.parse(body_source)
              return [] unless result.success?

              RbsInfer::Analyzer.find_all_nodes(result.value) { |n| n.is_a?(Prism::CallNode) }
                                .filter_map do |call|
                recv = call.receiver
                next unless recv.is_a?(Prism::CallNode) && recv.receiver.nil? && recv.arguments.nil?

                [recv.name.to_s, call.name.to_s]
              end
            end

            # --- Synthetic model class ---------------------------------------
            #
            #   class Assignment
            #     attr_accessor :post, :owner
            #     def save
            #       run_before_validation_callbacks
            #     end
            #     def run_before_validation_callbacks
            #       run_belongs_to_default_callbacks
            #     end
            #     def run_belongs_to_default_callbacks
            #       self.owner = post.user    # <- inlined lambda body, source-mapped
            #     end
            #   end
            def emit_model(model)
              in_file(model.class_name) do
                emit_class(syn(model.class_name)) do
                  member { emit "attr_accessor #{model.belongs_to.map { |b| ":#{b.name}" }.join(', ')}" }
                  member { emit_method("save") { emit "run_before_validation_callbacks" } }
                  member { emit_method("run_before_validation_callbacks") { emit "run_belongs_to_default_callbacks" } }
                  member do
                    emit_method("run_belongs_to_default_callbacks") do
                      model.default_associations.each { |default| emit_default_body(model, default) }
                    end
                  end
                end
              end
            end

            # The inlined lambda body — `self.<assoc> = <body>` — and its
            # source-map entry back to the real `default:` lambda. The mapped
            # ORIGINAL column comes from the reflection; the expansion file +
            # line are captured live as we emit.
            def emit_default_body(model, default)
              line = current_line
              emit "self.#{default.name} = #{default.default_body}"

              @source_map << {
                "expanded_file" => @filename,
                "expanded_line" => line,
                "original_path" => model.path,
                "original_line" => default.default_location[:line],
                "original_column" => default.default_location[:column],
                "original_length" => default.default_location[:length]
              }
            end

            # --- Runner (one checked method per construction site) ------------
            #
            # A witness seeds each derefed belongs_to's external-setter type
            # (mirroring the scenario's `def self.setup`), so rbs_infer infers
            # `post: Post?` even when no safe caller exists. Then one method per
            # site reproduces the caller: `:association` sites set the inverse
            # belongs_to from the owner and `save` (safe); `:direct` sites set
            # only the belongs_to passed as non-nil literals (params-sourced
            # attrs stay nilable → the default's deref is still flagged).
            def emit_runner
              in_file("Runner") do
                emit_class(syn("Runner")) do
                  @models.each { |model| member { emit_witness(model) } }
                  @sites.each_with_index { |site, idx| member { emit_site(site, idx + 1) } }
                end
              end
            end

            def emit_witness(model)
              emit_singleton_method("witness_#{underscore(model.class_name)}") do
                emit "record = #{syn(model.class_name)}.new"
                model.belongs_to.each { |b| emit "record.#{b.name} = #{syn(b.class_name)}.new" }
              end
            end

            def emit_site(site, idx)
              emit_singleton_method("site_#{idx}") do
                emit "record = #{syn(site.model.class_name)}.new"

                if site.kind == :association && site.inverse_belongs_to
                  emit "owner = #{syn(site.owner_class)}.new"
                  emit "record.#{site.inverse_belongs_to.name} = owner"
                end

                belongs_by_name = site.model.belongs_to.to_h { |b| [b.name, b.class_name] }
                site.literal_belongs_to.each { |name| emit "record.#{name} = #{syn(belongs_by_name[name])}.new" }

                emit "record.save"
              end
            end

            # The synthetic class name for a real class: the prefix + the real
            # name with `::` removed (`Blog::Post` →
            # `RbsInferBelongsToDefaultBlogPost`) — a unique top-level constant
            # that never shadows the real class. camelCase, NOT underscored, on
            # purpose: an underscore in a constant currently defeats the
            # analyzer's `.new`/external-setter resolution, so an underscored
            # synthetic name would type every `attr_accessor` `untyped` instead
            # of the nilable `T?` the whole contract depends on.
            def syn(class_name)
              "#{PREFIX}#{class_name.gsub('::', '')}"
            end

            def underscore(name)
              name.gsub("::", "_").gsub(/([a-z\d])([A-Z])/, '\1_\2').downcase
            end
          end
        end
      end
    end
  end
end
