# frozen_string_literal: true
#
# GENERATED by RbsInfer::Extensions::Rails::Views::RuntimeGenerator.
# Regenerated on every run; do not edit.

class ERBDashboardShow
  include ActionViewContext

  def initialize(account:, recent_posts:)
    @account = account
    @recent_posts = recent_posts
  end

  def params
    ActionController::Parameters.new
  end

  def __rbs_infer__body
    nil
  end
end
