# frozen_string_literal: true
#
# GENERATED by RbsInfer::Extensions::Rails::Controllers::RuntimeGenerator.
# Regenerated on every run; do not edit.

class DashboardController
  def render(target = nil, *rest)
    @__rbs_infer__performed = true
    case target
    when :show then ERBDashboardShow.new(account: @account, recent_posts: @recent_posts).__rbs_infer__body
    end
    true
  end

  private

  def __rbs_infer__run_show
    authenticate_user
    return if performed?

    log_user_author_name if current_user_present?
    return if performed?

    authenticate_account!
    return if performed?

    set_current_account
    return if performed?

    set_current_viewer
    return if performed?

    show

    return if performed?

    render :show
  end
end
