# frozen_string_literal: true
#
# GENERATED by RbsInfer::Extensions::Rails::Controllers::RuntimeGenerator.
# Regenerated on every run; do not edit.

class PostsController
  def render(*args)
    @__rbs_infer__performed = true
    case args.first
    when :edit then ERBPostsEdit.new.__rbs_infer__body
    when :new then ERBPostsNew.new.__rbs_infer__body
    end
    true
  end

  private

  def __rbs_infer__run_index
    authenticate_user
    return if performed?

    log_user_author_name if current_user_present?
    return if performed?

    index

    return if performed?

    ERBPostsIndex.new.__rbs_infer__body
  end

  def __rbs_infer__run_show
    authenticate_user
    return if performed?

    log_user_author_name if current_user_present?
    return if performed?

    set_post
    return if performed?

    show

    return if performed?

    ERBPostsShow.new.__rbs_infer__body
  end

  def __rbs_infer__run_new
    authenticate_user
    return if performed?

    log_user_author_name if current_user_present?
    return if performed?

    new

    return if performed?

    ERBPostsNew.new.__rbs_infer__body
  end

  def __rbs_infer__run_create
    authenticate_user
    return if performed?

    log_user_author_name if current_user_present?
    return if performed?

    create
  end

  def __rbs_infer__run_update
    authenticate_user
    return if performed?

    log_user_author_name if current_user_present?
    return if performed?

    set_post
    return if performed?

    update
  end

  def __rbs_infer__run_destroy
    authenticate_user
    return if performed?

    log_user_author_name if current_user_present?
    return if performed?

    set_post
    return if performed?

    destroy
  end

  def __rbs_infer__run_publish
    authenticate_user
    return if performed?

    log_user_author_name if current_user_present?
    return if performed?

    set_post
    return if performed?

    publish
  end
end
