class PostsController
  @__rbs_infer__performed: true?

  def render: (?(:index | :show | :new | :edit)? target, *{ status: :unprocessable_entity } rest) -> true

  private

  def __rbs_infer__run_index: () -> true?
  def __rbs_infer__run_show: () -> true?
  def __rbs_infer__run_new: () -> true?
  def __rbs_infer__run_create: () -> void
  def __rbs_infer__run_update: () -> void
  def __rbs_infer__run_destroy: () -> void
  def __rbs_infer__run_publish: () -> void
end
