module Users
  class AvatarsController
    @__rbs_infer__performed: true?

    def render: (?Symbol? target, *{ status: Symbol } rest) -> bool

    private

    def __rbs_infer__run_edit: () -> bool?
    def __rbs_infer__run_update: () -> void
  end
end
