class UsersController
  @__rbs_infer__performed: true?

  def render: (?(:show | "posts/show")? target, *untyped rest) -> true

  private

  def __rbs_infer__run_index: () -> void
  def __rbs_infer__run_show: () -> true?
  def __rbs_infer__run_featured_post: () -> void
end
