# frozen_string_literal: true

require "active_support/core_ext/string/inflections"
require_relative "attribute_scanner"
require_relative "accessor_transcriber"

module RbsInfer
  module Extensions
    module Rails
      module ActionText
        module Runtime
          # Renders one reopen per model that declares `has_rich_text`.
          #
          # The reopen carries the accessors and NOTHING else. The `has_one
          # :rich_text_<name>` the macro also declares, and the two scopes, are
          # reflections — rbs_rails reflects them at runtime and already writes
          # `rich_text_content: () -> ::ActionText::RichText?` and
          # `build_rich_text_content: (?untyped) -> ::ActionText::RichText`.
          # Re-emitting them here would be a second declaration of the same
          # method, and the pipeline would have to be told which is right.
          #
          # So this states no type at all. `content` is typed because
          # `rich_text_content || build_rich_text_content` is, and `content?`
          # because `.present?` is — the same way any other method in the app
          # gets its signature.
          module PseudoCodeBuilder
            FileEntry = Struct.new(:filename, :source, keyword_init: true)

            module_function

            # => [FileEntry], empty when no model declares the macro or the
            # macro itself could not be read.
            def build(units)
              units.filter_map { |unit| file_for(unit) }
            end

            def file_for(unit)
              accessors = unit.attributes.filter_map do |attribute|
                AccessorTranscriber.transcribe(name: attribute.name, options: attribute.options)
              end
              return nil if accessors.empty?

              FileEntry.new(
                filename: "#{file_name(unit.class_name)}.rb",
                source: source_for(unit.class_name, accessors)
              )
            end

            def source_for(class_name, accessors)
              body = accessors.join("\n").rstrip.lines
                              .map { |line| line.strip.empty? ? line : "  #{line}" }.join

              "#{header}class #{class_name}\n#{body}\nend\n"
            end

            def header
              <<~HEADER
                # frozen_string_literal: true
                #
                # GENERATED by RbsInfer::Extensions::Rails::ActionText::RuntimeGenerator.
                # Regenerated on every run; do not edit.
                #
                # The methods `has_rich_text` defines, transcribed from the installed
                # ActionText. The macro writes them with `class_eval` on a HEREDOC, and
                # a string is where every static reader stops — so they are opened here,
                # where the gem is loaded, and left as the plain Ruby they always were.
                #
                # The `has_one :rich_text_<name>` and the scopes the macro also declares
                # are absent on purpose: those are reflections, and rbs_rails already
                # writes them.

              HEADER
            end

            def file_name(constant)
              constant.underscore.gsub("/", "_")
            end
          end
        end
      end
    end
  end
end
