# frozen_string_literal: true

require "fileutils"

module RbsInfer::Project
  # Emits pseudo-code for what the LANGUAGE runs on a declaration. `Module#include` is
  # written in C, so nothing in a project says that `include M` runs `M.included(self)`
  # — and that call is the only thing that says which class a hook's parameter is.
  #
  # So write `Module#include`, once — transcribed from `rb_mod_include` in MRI's
  # `eval.c`, which is:
  #
  #   rb_check_arity(argc, 1, UNLIMITED_ARGUMENTS);
  #   ...
  #   while (argc--) {
  #       rb_funcall(argv[argc], id_append_features, 1, module);
  #       rb_funcall(argv[argc], id_included, 1, module);
  #   }
  #   return module;
  #
  # Three things in there the pseudo-code has to say, or it is describing some other
  # method: `while (argc--)` walks the arguments BACKWARDS (which is why `include A, B`
  # leaves `A` closest in the ancestors); `append_features` is where the chain is
  # actually spliced (`rb_include_module`); and `rb_funcall` dispatches by name
  # IGNORING visibility — both of those methods are private on `Module`, and `included`
  # is a no-op there (`rb_obj_dummy1`), so the plain-call spelling `mod.included(self)`
  # asserts a public call Ruby never makes. `send` is what `rb_funcall` is.
  #
  # The two it delegates to are written here as well, under `private` because that is
  # their visibility on `Module` (measured: `Module.instance_method(:included).owner` is
  # `Module`, and RBS core declares both `private def`). Neither can state its whole
  # effect — the splice is `rb_include_module` and the hook is `rb_obj_dummy1` — but
  # writing them gives an app's override a `super` that resolves, which is what
  # `ActiveSupport::Concern#append_features` needs.
  #
  # `extend` is the same story told about the singleton: `rb_obj_extend` in object.c
  # runs `extend_object` and then `extended`, so `extend Deferring` is what says that
  # `Deferring.extended(Shared)` ran — and that call is the only thing that says which
  # module a hook's parameter is. Without it a pass can only ASSUME the hook fired,
  # which is what felixefelip/rbs_infer#302 is about.
  #
  # Nothing here states a type; the same rule the Devise and AR-runtime generators
  # follow. `# @rbs_infer |...` (#200) makes the emitted signature RBS's overloading
  # form, so this ADDS to core's `Module#include` instead of redeclaring it — a plain
  # redeclaration is a `DuplicatedMethodDefinitionError` that aborts the whole run.
  #
  # Sibling to `steep_ar_runtime` / `steep_controller_runtime` / `steep_actionview_runtime`,
  # which model a FRAMEWORK's runtime. This one models the language's, which is why it is
  # CORE rather than an extension: `include` is plain Ruby, so the litmus in
  # docs/engineering/keep-core-framework-agnostic.md ("would this make sense for a gem
  # that doesn't exist?") answers yes. `ActiveSupport::Concern` needs nothing of its own —
  # a Concern's `included` is a method its includers call the same way, and so is a
  # hand-rolled one.
  class RubyRuntimeGenerator
    # NOT dot-prefixed: these are `.rb` SOURCE files, and `**` skips hidden directories
    # — same reason as the AR-runtime sidecar.
    SIDECAR_DIR = "sig/generated/steep_ruby_runtime"

    # One emitted file: `filename` within the sidecar dir, `source` its contents.
    FileEntry = Struct.new(:filename, :source, keyword_init: true)

    MODULE_PSEUDO_CODE = <<~RUBY
      # frozen_string_literal: true
      #
      # GENERATED by RbsInfer::Project::RubyRuntimeGenerator.
      # Regenerated on every run; do not edit.

      class Module
        # What `include M` runs — `rb_mod_include` in MRI's eval.c, written in C, so no
        # source says it.
        #
        # `| ...` (rbs_infer#200) makes this ADD to core's `Module#include` rather than
        # redeclare it, which RBS rejects as a duplicate.
        # @rbs_infer |...
        def include(*modules)
          raise ArgumentError, "wrong number of arguments (given 0, expected 1+)" if modules.empty?

          # `while (argc--)`: backwards, which is why `include A, B` leaves A closest in
          # the ancestors. `send` because `rb_funcall` dispatches by name ignoring
          # visibility, and both of these are private on Module.
          modules.reverse_each do |mod|
            mod.send(:append_features, self)
            mod.send(:included, self)
          end

          self
        end

        private

        # What `include` delegates the actual work to — `rb_mod_append_features` in eval.c:
        #
        #   if (!CLASS_OR_MODULE_P(include)) Check_Type(include, T_CLASS);
        #   rb_include_module(include, module);
        #   return module;
        #
        # The splice itself is `rb_include_module`, and no Ruby spells it — so the body says
        # the two things it CAN say: the type check, and that the answer is the module. A
        # module that overrides this (`ActiveSupport::Concern` does) now has a `super` to
        # resolve against.
        # @rbs_infer |...
        def append_features(mod)
          raise TypeError, "wrong argument type (expected Class or Module)" unless mod.is_a?(Module)

          mod.send(:__rbs_infer__include_module, self)
          self
        end

        def __rbs_infer__include_module(mod)
          nil
        end

        # The notification, and on `Module` it does nothing at all: `rb_obj_dummy1`, one
        # argument, returns nil. A module that wants to know overrides it with
        # `def self.included(base)`, which shadows this and is PUBLIC in the process — which
        # is why `include` above has to reach this one with `send`.
        # @rbs_infer |...
        def included(base)
          nil
        end

        # What `extend` delegates the singleton splice to — `rb_mod_extend_object`
        # in eval.c:
        #
        #   rb_extend_object(obj, mod);   /* rb_include_module(rb_singleton_class(obj), mod) */
        #   return obj;
        #
        # Same shape as `append_features` and unstatable for the same reason — the
        # splice is C — so the body says the one thing it can: the answer is the
        # OBJECT, not the module. That asymmetry is the difference between the two,
        # and a module that overrides this now has a `super` to resolve against.
        # @rbs_infer |...
        def extend_object(obj)
          obj.singleton_class.include(self)
          obj
        end

        # The notification, and on `Module` it does nothing at all: `rb_obj_dummy1`,
        # one argument, returns nil — the same stub as `included`. A module that
        # wants to know overrides it with `def self.extended(base)`, which shadows
        # this and is PUBLIC in the process, which is why `extend` reaches this one
        # with `send`.
        # @rbs_infer |...
        def extended(base)
          nil
        end
      end
    RUBY

    # `extend` is `Kernel#extend` (measured: `Object.instance_method(:extend).owner`),
    # and it is written here on `Object` instead, deliberately. What reads this file
    # resolves a core reopening through the SUPERCLASS chain, and no module is on one
    # — `Kernel` included. `Object` is on both the class chain and the module chain,
    # so it is where `extend` is reachable by the ancestry that does the reading, and
    # `class Object` is the cheaper claim than teaching that chain about modules.
    OBJECT_PSEUDO_CODE = <<~RUBY
      # frozen_string_literal: true
      #
      # GENERATED by RbsInfer::Project::RubyRuntimeGenerator.
      # Regenerated on every run; do not edit.

      class Object
        # What `obj.extend M` runs — `rb_obj_extend` in MRI's object.c, written in C,
        # so no source says it:
        #
        #   rb_check_arity(argc, 1, UNLIMITED_ARGUMENTS);
        #   for (i = 0; i < argc; i++) Check_Type(argv[i], T_MODULE);
        #   while (argc--) {
        #       rb_funcall(argv[argc], id_extend_object, 1, obj);
        #       rb_funcall(argv[argc], id_extended, 1, obj);
        #   }
        #   return obj;
        #
        # `| ...` (rbs_infer#200) makes this ADD to the `extend` core declares rather
        # than replace it — the declaration it adds to is `Kernel`'s, reached from here
        # because `Object` includes `Kernel`.
        # @rbs_infer |...
        def extend(*modules)
          raise ArgumentError, "wrong number of arguments (given 0, expected 1+)" if modules.empty?

          # `for (i = 0; i < argc; i++) Check_Type(...)`: EVERY argument is checked
          # before ANY hook runs, which is where this parts company with `include` —
          # there the check lives inside `append_features`, so `include Foo, 1` can
          # already have notified `Foo`.
          modules.each do |mod|
            raise TypeError, "wrong argument type (expected Module)" unless mod.is_a?(Module)
          end

          # `while (argc--)`: backwards, as in `include`. `send` because `rb_funcall`
          # dispatches by name ignoring visibility, and both of these are private on
          # Module.
          modules.reverse_each do |mod|
            mod.send(:extend_object, self)
            mod.send(:extended, self)
          end

          self
        end
      end
    RUBY

    def initialize(app_dir:)
      @app_dir = app_dir
    end

    # Returns [FileEntry]. Public so specs can read the pseudo-code without touching disk.
    def build
      [FileEntry.new(filename: "module.rb", source: MODULE_PSEUDO_CODE),
       FileEntry.new(filename: "object.rb", source: OBJECT_PSEUDO_CODE)]
    end

    # (Re)writes the sidecar directory.
    def generate
      dir = File.join(@app_dir, SIDECAR_DIR)

      FileUtils.rm_rf(dir)
      FileUtils.mkdir_p(dir)
      build.each { |file| File.write(File.join(dir, file.filename), file.source) }

      dir
    end
  end
end
