# frozen_string_literal: true

require "fileutils"

module RbsInfer::Project
  # Emits pseudo-code for what the LANGUAGE runs on a declaration. `Module#include` is
  # written in C, so nothing in a project says that `include M` runs `M.included(self)`
  # — and that call is the only thing that says which class a hook's parameter is.
  #
  # So write `Module#include`, once:
  #
  #   class Module
  #     # @rbs_infer |...
  #     def include(*modules)
  #       modules.each { |mod| mod.included(self) }
  #       self
  #     end
  #   end
  #
  # Nothing here states a type; the same rule the Devise and AR-runtime generators
  # follow. `# @rbs_infer |...` (#200) makes the emitted signature RBS's overloading
  # form, so this ADDS to core's `Module#include` instead of redeclaring it — a plain
  # redeclaration is a `DuplicatedMethodDefinitionError` that aborts the whole run.
  #
  # Sibling to `steep_ar_runtime` / `steep_controller_runtime` / `steep_actionview_runtime`,
  # which model a FRAMEWORK's runtime. This one models the language's, which is why it is
  # CORE rather than an extension: `include` is plain Ruby, so the litmus in
  # docs/engineering/keep-core-framework-agnostic.md ("would this make sense for a gem
  # that doesn't exist?") answers yes. `ActiveSupport::Concern` needs nothing of its own —
  # a Concern's `included` is a method its includers call the same way, and so is a
  # hand-rolled one.
  class RubyRuntimeGenerator
    # NOT dot-prefixed: these are `.rb` SOURCE files, and `**` skips hidden directories
    # — same reason as the AR-runtime sidecar.
    SIDECAR_DIR = "sig/generated/steep_ruby_runtime"

    # One emitted file: `filename` within the sidecar dir, `source` its contents.
    FileEntry = Struct.new(:filename, :source, keyword_init: true)

    PSEUDO_CODE = <<~RUBY
      # frozen_string_literal: true
      #
      # GENERATED by RbsInfer::Project::RubyRuntimeGenerator.
      # Regenerated on every run; do not edit.

      class Module
        # What `include M` runs. Written in C, so no source says it.
        #
        # `| ...` (rbs_infer#200) makes this ADD to core's `Module#include` rather than
        # redeclare it, which RBS rejects as a duplicate.
        # @rbs_infer |...
        def include(*modules)
          modules.each { |mod| mod.included(self) }
          self
        end
      end
    RUBY

    def initialize(app_dir:)
      @app_dir = app_dir
    end

    # Returns [FileEntry]. Public so specs can read the pseudo-code without touching disk.
    def build
      [FileEntry.new(filename: "module.rb", source: PSEUDO_CODE)]
    end

    # (Re)writes the sidecar directory.
    def generate
      dir = File.join(@app_dir, SIDECAR_DIR)

      FileUtils.rm_rf(dir)
      FileUtils.mkdir_p(dir)
      build.each { |file| File.write(File.join(dir, file.filename), file.source) }

      dir
    end
  end
end
