# ⚠️  Generated by rbs_infer for debugging — NEVER loaded at runtime.
#     Expanded view of app/models/example54/baz.rb (macros desugared into pseudo-code).
#     Regenerated on every run; do not edit.
class Example54
  module Foo
    def banana_class_method(&block)
      mod = const_defined?(:BananaMethods) ? const_get(:BananaMethods) : const_set(:BananaMethods, Module.new)

      mod.module_eval(&block)
    end

    def included(base)
      base.extend(const_get(:BananaMethods)) if const_defined?(:BananaMethods)
    end
  end

  module Baz
    extend Example54::Foo

    banana_class_method do
      def age
        31
      end
    end
  end
end

module Example54::Baz::BananaMethods
  # @type instance: singleton(::Example54::Bar) & ::Example54::Baz::BananaMethods
  def age
    31
  end
end
