# frozen_string_literal: true
#
# GENERATED by RbsInfer::Extensions::Rails::Views::RuntimeGenerator.
# Regenerated on every run; do not edit.

class ERBPostsEdit
  include ActionViewContext
  include PostsHelper

  def initialize(post:)
    @post = post
  end

  def render(*args)
    ERBPartialPostsForm.new(post: @post)
  end

  def params
    ActionController::Parameters.new
  end

  def __rbs_infer__body
    nil
  end
end
