# frozen_string_literal: true
#
# GENERATED by RbsInfer::Extensions::Rails::Views::RuntimeGenerator.
# Regenerated on every run; do not edit.

class ERBPostsIndex
  include ActionViewContext
  include PostsHelper

  def initialize(posts:)
    @posts = posts
  end

  def params
    ActionController::Parameters.new
  end

  def __rbs_infer__body
    nil
  end
end
