# frozen_string_literal: true
#
# GENERATED by RbsInfer::Extensions::Rails::Views::RuntimeGenerator.
# Regenerated on every run; do not edit.

class ERBPostsShow
  include ActionViewContext
  include PostsHelper

  def initialize(comments:, post:)
    @comments = comments
    @post = post
  end

  def render(target = nil, *rest)
    case target
    when "comment" then @comments.each { |comment| ERBPartialPostsComment.new(comment: comment) }
    when "posts/summary" then ERBPartialPostsSummary.new(post: @post)
    end
    nil
  end

  def params
    ActionController::Parameters.new
  end

  def __rbs_infer__body
    nil
  end
end
