# frozen_string_literal: true
#
# GENERATED by RbsInfer::Extensions::Rails::ActiveRecord::RuntimeGenerator.
# Regenerated on every run; do not edit.

module Notification::GeneratedStoreAccessors
  def channel
    @__store_settings_channel
  end

  def channel=(value)
    @__store_settings_channel = value
  end

  def theme
    @__store_settings_theme
  end

  def theme=(value)
    @__store_settings_theme = value
  end

  def settings_digest
    @__store_settings_digest
  end

  def settings_digest=(value)
    @__store_settings_digest = value
  end
end
