class Notification
  module GeneratedStoreAccessors
    @__store_settings_channel: "none"?

    def channel: () -> String?
    def channel=: ("none"? value) -> "none"?
    def theme: () -> untyped
    def theme=: (untyped value) -> untyped
    def settings_digest: () -> untyped
    def settings_digest=: (untyped value) -> untyped
  end
end
