class Post
  module Notifiable
    extend ActiveSupport::Concern
    def notification_title: () -> String
    def notify_subscribers: (untyped subscribers) -> untyped
    def notification_excerpt: (?Integer length) -> untyped
    def notification_payload: () -> Hash[Symbol, untyped]

    private

    def deliver_notification: (untyped subscriber) -> Hash[Symbol, untyped]
  end
end