class IncludedHook
  module Slots
    @slot: "value"?
    @badge: "value"?
    @stamp: "value"?

    def slot: () -> String?
    def slot=: ("value"? value) -> "value"?
    def badge: () -> String?
    def badge=: ("value"? value) -> "value"?
    def stamp: () -> String?
    def stamp=: ("value"? value) -> "value"?
  end
end
