# frozen_string_literal: true

require "prism"
require "fileutils"

module RbsInfer
  module Extensions
    module CarrierWave
      # Walks each app/models/**/*.rb, captures `mount_uploader` / `mount_uploaders`
      # calls, and emits RBS that reopens the model class with the uploader-typed
      # accessors plus the helpers CarrierWave injects (`*_cache`, `remove_*`,
      # `remote_*_url`, `store_*!`, etc.).
      #
      # Because rbs_rails emits `def avatar: () -> ::String?` from the column,
      # we also strip the conflicting plain-accessor defs (`avatar`, `avatar=`,
      # `avatar?`) from the corresponding `sig/rbs_rails/app/models/<m>.rbs`.
      # The dirty-state predicates (`*_changed?`, `*_was`, `*_before_type_cast`,
      # etc.) keep their `String?` type since they reflect the DB column, not the
      # uploader instance — so we leave those untouched.
      class Generator
        attr_reader :app_dir, :output_dir, :rbs_rails_dir

        def initialize(app_dir:, output_dir:, rbs_rails_dir: nil)
          @app_dir = app_dir
          @output_dir = output_dir
          @rbs_rails_dir = rbs_rails_dir || File.join(app_dir, "sig/rbs_rails")
        end

        def generate_all
          Dir.glob(File.join(app_dir, "app/models/**/*.rb")).sort.each do |model_path|
            generate_for_model(model_path)
          end
        end

        private

        def generate_for_model(model_path)
          source = File.read(model_path)
          result = Prism.parse(source)

          class_info = extract_class_info(result.value)
          return unless class_info

          mount_calls = extract_mount_calls(result.value)
          return if mount_calls.empty?

          rbs = build_rbs(class_info[:name], mount_calls)

          relative_path = model_path.sub("#{app_dir}/", "")
          output_path = File.join(output_dir, relative_path.sub(/\.rb\z/, ".rbs"))

          FileUtils.mkdir_p(File.dirname(output_path))
          File.write(output_path, rbs)

          strip_rbs_rails_accessors(relative_path, mount_calls)
        end

        def extract_class_info(node)
          case node
          when Prism::ProgramNode
            extract_class_info(node.statements)
          when Prism::StatementsNode
            node.body.each do |child|
              info = extract_class_info(child)
              return info if info
            end
            nil
          when Prism::ClassNode
            { name: constant_path_to_string(node.constant_path) }
          end
        end

        def constant_path_to_string(node)
          case node
          when Prism::ConstantReadNode
            node.name.to_s
          when Prism::ConstantPathNode
            parent = node.parent ? "#{constant_path_to_string(node.parent)}::" : ""
            "#{parent}#{node.name}"
          else
            node.to_s
          end
        end

        def extract_mount_calls(node)
          calls = []
          visit(node) do |n|
            next unless n.is_a?(Prism::CallNode)
            next unless n.receiver.nil?
            next unless %i[mount_uploader mount_uploaders].include?(n.name)

            info = parse_mount_call(n)
            calls << info if info
          end
          calls
        end

        def visit(node, &block)
          return unless node.is_a?(Prism::Node)

          yield node
          node.child_nodes.compact.each { |child| visit(child, &block) }
        end

        def parse_mount_call(call_node)
          args = call_node.arguments&.arguments || []
          return nil if args.size < 2

          attr_node = args[0]
          uploader_node = args[1]

          return nil unless attr_node.is_a?(Prism::SymbolNode)

          uploader_name = constant_path_to_string(uploader_node)
          return nil if uploader_name.nil? || uploader_name.empty?

          {
            name: attr_node.value,
            uploader: uploader_name,
            multiple: call_node.name == :mount_uploaders
          }
        end

        def build_rbs(class_name, mount_calls)
          lines = []
          lines << "# Generated by rbs_infer (carrierwave)"
          lines << ""
          lines << "class ::#{class_name}"
          mount_calls.each_with_index do |call, idx|
            lines << "" if idx > 0
            lines.concat(build_methods(call))
          end
          lines << "end"
          lines << ""
          lines.join("\n")
        end

        def build_methods(call)
          attr = call[:name]
          uploader = "::#{call[:uploader]}"
          getter_type = call[:multiple] ? "Array[#{uploader}]" : uploader

          [
            "  def #{attr}: () -> #{getter_type}",
            "  def #{attr}=: (untyped) -> untyped",
            "  def #{attr}?: () -> bool",
            "",
            "  def remove_#{attr}: () -> bool",
            "  def remove_#{attr}=: (bool | ::String) -> (bool | ::String)",
            "  def remove_#{attr}?: () -> bool",
            "",
            "  def #{attr}_cache: () -> ::String?",
            "  def #{attr}_cache=: (::String?) -> ::String?",
            "",
            "  def remote_#{attr}_url: () -> ::String?",
            "  def remote_#{attr}_url=: (::String?) -> ::String?",
            "",
            "  def write_#{attr}_identifier: () -> void",
            "  def store_#{attr}!: () -> void",
            "  def remove_#{attr}!: () -> void",
            "  def store_previous_changes_for_#{attr}: () -> void"
          ]
        end

        def strip_rbs_rails_accessors(model_relative_path, mount_calls)
          rbs_path = File.join(rbs_rails_dir, model_relative_path.sub(/\.rb\z/, ".rbs"))
          return unless File.exist?(rbs_path)

          content = File.read(rbs_path)
          stripped = content.dup

          mount_calls.each do |call|
            attr = Regexp.escape(call[:name].to_s)
            # Match only the three plain accessors; keep *_changed?, *_was, etc.
            stripped.gsub!(/^[ \t]*def #{attr}(?:=|\?)?: [^\n]*\n/, "")
          end

          File.write(rbs_path, stripped) if stripped != content
        end
      end
    end
  end
end
