# frozen_string_literal: true

require "prism"

module RbsInfer
  module Extensions
    module Rails
      module BelongsToDefault
        # Turns the scanned reflections + construction sites into the
        # `example.rb`-shaped synthetic program Steep checks, and the
        # source-map linking each inlined `default:` lambda back to its real
        # span (felixefelip/rbs_infer#72 / felixefelip/steep#54).
        #
        # Every synthetic class carries the `RbsInferBelongsToDefault_` prefix
        # so it never collides with the real app classes when both flow through
        # the rbs_infer→Steep contract pipeline. The classes are emitted at the
        # TOP LEVEL (not nested in a wrapper module) because the analyzer's
        # multi-class discovery only walks top-level classes — a module wrapper
        # would drop every class but the first.
        class ExpansionBuilder
          PREFIX = "RbsInferBelongsToDefault"

          Result = Struct.new(:expanded_source, :source_map, keyword_init: true)

          # models: the belongs_to-default models (get lifecycle + witness).
          # all_models: every scanned model (unused today; kept so a future
          #   deeper deref resolution can consult the full graph).
          # sites: [ConstructionSite].
          def initialize(models:, all_models:, sites:)
            @models = models
            @all_models = all_models
            @sites = sites
            @lines = []
            @source_map = []
          end

          def build
            emit "# frozen_string_literal: true"
            emit "#"
            emit "# GENERATED by RbsInfer::Extensions::Rails::BelongsToDefaultGenerator."
            emit "# The example.rb-shaped expansion of `belongs_to ..., default:` that"
            emit "# Steep type-checks; diagnostics map back via .steep_belongs_to_default.yml."
            emit "# Regenerated on every run; do not edit."
            emit ""
            emit_target_classes
            @models.each { |model| emit_model(model) }
            emit_runner

            Result.new(expanded_source: "#{@lines.join("\n")}\n", source_map: @source_map)
          end

          private

          def emit(line)
            @lines << line
          end

          def current_line
            @lines.length + 1
          end

          # --- Synthetic belongs_to target classes ---------------------------
          #
          # One class per belongs_to target of a default model — every one is
          # `.new`'d by the witness/sites, so all must exist. A target used as a
          # deref receiver in a lambda body (`post` → `Post`) also gets a stub
          # for each method called directly on that receiver (`post.user` →
          # `def user; raise; end`). A `raise` body returns `bot` (⊥), so any
          # DEEPER chain (`post.user.name`) rides on it and type-checks — while
          # the FIRST hop on a nilable `post` still errors, which is exactly the
          # diagnostic we cover.
          def emit_target_classes
            stubs = target_method_stubs
            target_class_names.each do |class_name|
              emit "class #{syn(class_name)}"
              (stubs[class_name] || []).sort.each do |method|
                emit "  def #{method}; raise; end"
              end
              emit "end"
              emit ""
            end
          end

          # Every belongs_to target across the default models (deduped, stable
          # order). These are the classes referenced by `attr_accessor`
          # setters and constructed in the runner.
          def target_class_names
            @models.flat_map { |m| m.belongs_to.map(&:class_name) }.uniq.sort
          end

          # target class name => Set of method names called on a belongs_to
          # receiver of that class, across every default lambda.
          def target_method_stubs
            stubs = Hash.new { |h, k| h[k] = [] }
            @models.each do |model|
              belongs_by_name = model.belongs_to.to_h { |b| [b.name, b.class_name] }
              model.default_associations.each do |default|
                deref_calls(default.default_body).each do |recv_name, method|
                  target = belongs_by_name[recv_name]
                  next unless target

                  stubs[target] << method unless stubs[target].include?(method)
                end
              end
            end
            stubs
          end

          # [[receiver_name, method], ...] for `receiver.method` calls in a
          # lambda body where `receiver` is a bare (receiverless) name — the
          # shape of a `belongs_to` deref. Deeper hops are ignored here (they
          # ride on the ⊥ return of the first hop's stub).
          def deref_calls(body_source)
            result = Prism.parse(body_source)
            return [] unless result.success?

            RbsInfer::Analyzer.find_all_nodes(result.value) { |n| n.is_a?(Prism::CallNode) }
                              .filter_map do |call|
              recv = call.receiver
              next unless recv.is_a?(Prism::CallNode) && recv.receiver.nil? && recv.arguments.nil?

              [recv.name.to_s, call.name.to_s]
            end
          end

          # --- Synthetic model class -----------------------------------------
          #
          #   class Assignment
          #     attr_accessor :post, :owner
          #     def save; run_before_validation_callbacks; end
          #     def run_before_validation_callbacks; run_belongs_to_default_callbacks; end
          #     def run_belongs_to_default_callbacks
          #       self.owner = post.user    # <- inlined lambda body, source-mapped
          #     end
          #   end
          def emit_model(model)
            emit "class #{syn(model.class_name)}"
            emit "  attr_accessor #{model.belongs_to.map { |b| ":#{b.name}" }.join(', ')}"
            emit "  def save; run_before_validation_callbacks; end"
            emit "  def run_before_validation_callbacks; run_belongs_to_default_callbacks; end"
            emit "  def run_belongs_to_default_callbacks"
            model.default_associations.each { |default| emit_default_body(model, default) }
            emit "  end"
            emit "end"
            emit ""
          end

          # The inlined lambda body — `self.<assoc> = <body>` — and its
          # source-map entry back to the real `default:` lambda. The mapped
          # ORIGINAL column comes from the reflection; the expansion line is
          # captured live as we emit.
          def emit_default_body(model, default)
            line = current_line
            emit "    self.#{default.name} = #{default.default_body}"

            @source_map << {
              "expanded_line" => line,
              "original_path" => model.path,
              "original_line" => default.default_location[:line],
              "original_column" => default.default_location[:column],
              "original_length" => default.default_location[:length]
            }
          end

          # --- Runners (one checked method per construction site) -------------
          #
          # A witness seeds each derefed belongs_to's external-setter type
          # (mirroring the scenario's `def self.setup`), so rbs_infer infers
          # `post: Post?` even when no safe caller exists. Then one method per
          # site reproduces the caller: `:association` sites set the inverse
          # belongs_to from the owner and `save` (safe); `:direct` sites set
          # only the belongs_to passed as non-nil literals (params-sourced
          # attrs stay nilable → the default's deref is still flagged).
          def emit_runner
            emit "class #{syn('Runner')}"
            @models.each { |model| emit_witness(model) }
            @sites.each_with_index { |site, idx| emit_site(site, idx + 1) }
            emit "end"
          end

          def emit_witness(model)
            emit "  def self.witness_#{underscore(model.class_name)}"
            emit "    record = #{syn(model.class_name)}.new"
            model.belongs_to.each do |b|
              emit "    record.#{b.name} = #{syn(b.class_name)}.new"
            end
            emit "  end"
          end

          def emit_site(site, idx)
            emit "  def self.site_#{idx}"
            emit "    record = #{syn(site.model.class_name)}.new"

            if site.kind == :association && site.inverse_belongs_to
              emit "    owner = #{syn(site.owner_class)}.new"
              emit "    record.#{site.inverse_belongs_to.name} = owner"
            end

            belongs_by_name = site.model.belongs_to.to_h { |b| [b.name, b.class_name] }
            site.literal_belongs_to.each do |name|
              emit "    record.#{name} = #{syn(belongs_by_name[name])}.new"
            end

            emit "    record.save"
            emit "  end"
          end

          # The synthetic class name for a real class: the prefix + the real
          # name with `::` removed (`Blog::Post` →
          # `RbsInferBelongsToDefaultBlogPost`) — a unique top-level constant
          # that never shadows the real class. camelCase, NOT underscored, on
          # purpose: an underscore in a constant currently defeats the
          # analyzer's `.new`/external-setter resolution, so an underscored
          # synthetic name would type every `attr_accessor` `untyped` instead
          # of the nilable `T?` the whole contract depends on.
          def syn(class_name)
            "#{PREFIX}#{class_name.gsub('::', '')}"
          end

          def underscore(name)
            name.gsub("::", "_").gsub(/([a-z\d])([A-Z])/, '\1_\2').downcase
          end
        end
      end
    end
  end
end
