class Comment < ApplicationRecord
  def author_name: () -> String?
  def short_body: (?Integer max) -> String
  def create_custom: () -> void
  def display_author: () -> String?
  def display_body: () -> String
  def notify_post_author: () -> String
end
