module Eventable
  extend ActiveSupport::Concern

  def track_event: ((:published | "renamed" | :closed | :reopened) action, **untyped) -> { action: (:published | "renamed" | :closed | :reopened), particulars: untyped }
end
