class Example8
  @name: String?
  @value: Integer?

  def run_name: () -> (String | Integer | nil)
  def run_age: () -> (String | Integer | nil)
  def show: (Symbol which) -> (String | Integer | nil)
end
