class Example67Source
  def enabled?: () -> bool
  def window_size: () -> 30
  def window: () -> Example67Window?
  def windowed?: () -> bool
  def detect_spikes: () -> bool

  class AfterWindowed
    def window: () -> ::Example67Window
  end
end
