class Example14
  @halted: true?
  @user: Example14::User?

  def run: () -> String?

  private

  def halt: () -> bool
  def verify: () -> Example14::User
  def set_user: () -> User
end

class Example14
  class User
    attr_reader name: untyped

    def initialize: (name: String) -> void
  end
end
