class Example10
  def run: () -> String
end

class Example10
  class Foo
    self.@name: String?

    def self.name: () -> String?
    def self.name=: (String value) -> String
  end
end

class Example10
  class Sink
    self.@last: String?

    def self.last: () -> String?
    def self.last=: (String value) -> String
  end
end

class Example10
  class Bar
    def greet: () -> String
  end
end
