class Example34
  module Foo
    @_bazingado_block: (^(*untyped) [self: Module] -> Symbol)?

    def include: (*singleton(::Example34::Baz) modules) -> Array[singleton(Example34::Baz)]
    def included: (?Module? base) ?{ (*untyped) [self: Module] -> Symbol } -> (^(*untyped) [self: Module] -> Symbol | nil | Symbol)
  end

  module Baz
    extend ::Example34::Foo
  end
end

class Example34
  class Bar
    extend ::Example34::Foo
    include ::Example34::Baz
  end
end
