class Example12
  @name: String?
  @value: Integer?

  def run_name: () -> untyped
  def run_age: () -> untyped
  def dispatch_name: () -> untyped
  def dispatch_age: () -> untyped
  def show: (Symbol which) -> untyped
end
