class Example56
  def self.call: () -> Integer
end

class Example56
  class Reader
    def name: () -> "farm"
    def maybe_name: () -> String?
    def label: () -> "FARM"
    def shout: () -> "FARM"
    def maybe_label: () -> "loud"?
  end
end
