class Example15
  @halted: true?

  def run: () -> String?

  private

  def halt: () -> bool
  def verify: () -> Example15::User
  def set_user: () -> Example15::User
end

class Example15
  class User
    attr_reader name: String

    def initialize: (name: String) -> void
  end
end

class Example15
  class Registry
    self.@user: User?

    def self.user: () -> Example15::User?
    def self.user=: (User value) -> User
  end
end
