class Example4
  def run: () -> untyped
end

class Example4
  class Foo
    self.@name: String?

    def self.name: () -> String?
    def self.name=: ((String | nil) value) -> untyped
  end
end

class Example4
  class Bar
    def foo_name_before: () -> untyped
    def foo_name: () -> String?
    def foo_name_after: () -> untyped
  end
end
