class Example51
  module Foo
    def banana_class_method: () ?{ (*untyped) -> Symbol } -> untyped
  end

  module Baz
    extend ::Example51::Foo
  end
end

class Example51
  class Bar
    def methods_module: () -> untyped
  end
end
