module Example69
  class Foo
    def name: () -> String
    def action: () -> String
    def call_name_action: () -> String
    def call_action: () -> String
    def call_dynamic: () -> String
    def call_dynamic_with_name: () -> String
    def call_both: () -> Array[String]
    def name_action_dynamic: (flag_name: bool) -> String
    def call_unknown: (flag_name: untyped) -> String

    private

    def call: (?flag_name: bool) -> String
  end
end
