class Example28
  module Foo
    attr_reader bazingado_block: untyped
    def bazinga: (singleton(::Example28::Baz) module_included) -> untyped
    def bazingado: () ?{ (*untyped) -> Symbol } -> (^(*untyped) -> Symbol)?
  end

  module Baz
    extend ::Example28::Foo
  end

  class AfterBazingado
    attr_reader bazingado_block: (^(*untyped) -> Symbol)?
  end
end

class Example28
  class Bar
    extend ::Example28::Foo

    def self.validade_age: () -> String

    def age: () -> Integer
    def call_test: () -> String
    def greet: () -> String
    def age_after_a_decade: () -> Integer
  end
end
