class Example3
  def self.run: () -> String
end

class Example3
  class User
    attr_reader name: String

    def initialize: (name: String) -> void
  end
end

class Example3
  class Foo
    module GeneratedAttributes
      attr_accessor user: User?
      attr_accessor name: String
      attr_writer foo_instance: untyped
    end

    include GeneratedAttributes

    def self.foo_instance: () -> Example3::Foo
    def self.user: () -> Example3::User?
    def self.user=: (User value) -> User
    def self.name: () -> String
    def self.name=: (String value) -> String

    def user=: (User value) -> String?

    class AfterUser
      attr_reader user: Example3::User
    end
  end
end
