class IncludedHook
  module Hookable
    def self.included: (untyped base) -> untyped
    def from_hook: () -> String
    def slot: () -> untyped
  end
  module Arbitrary
    def self.foo_included: (untyped base) -> untyped
    def from_arbitrary: () -> String
  end
  module Shared
    def self.included: (untyped base) -> untyped
    def from_shared: () -> Integer
  end

  include Slots
  include Hookable
end

class IncludedHookCaller
  def fill: () -> String
  def read_slot: () -> untyped
  def read_shared: () -> Integer
end
