class IncludedHook
  module Hookable
    def self.included: (Module base) -> Symbol
  end

  module Sugared
    extend ActiveSupport::Concern
  end

  module Homespun
    extend ::IncludedHook::HomeMade
  end

  module Arbitrary
    def self.foo_included: (untyped base) -> untyped
  end

  include Slots
  include Hookable
  include Sugared
  include Homespun

  def from_homespun: () -> String
  def stamp: () -> String
end

class IncludedHookCaller
  def fill: () -> String
  def read_slot: () -> String?
  def read_badge: () -> String?
  def read_stamp: () -> String
  def read_shared: () -> Integer
end
