class Notification < ApplicationRecord
  def channel: () -> String
  def mute!: () -> "none"
  def read?: () -> bool
  def headline: () -> String

  class AfterRead
    def read_at: () -> ::ActiveSupport::TimeWithZone
  end
end
