class Post < ApplicationRecord
  def summary: (?Integer length) -> untyped
  def test_status: () -> ::Integer
  def was_archived?: () -> untyped
  def creator: () -> ::User
  def author_name: () -> String
  def publish!: () -> self
  def comments_count: () -> Integer
  def add_comment: (author: untyped, body: untyped) -> Comment
end
