class User < ApplicationRecord
  attr_accessor session_token: untyped
  def full_name: () -> String
  def active?: () -> bool?
  def posts_count: () -> ::Integer
  def recent_posts: (?untyped) -> ::Post::ActiveRecord_Associations_CollectionProxy
end
