class Comment
  class Create
    def create: (Integer comment_id) -> void

    private

    def process_creation_response: (Comment comment, Symbol status) -> void
    def dummy_hash: () -> Hash[Symbol, untyped]
    def test_dummy_hash: () -> untyped
  end
end
