---
version: 2
call_sites:
  app/models/article.rb:12:2:
  - |2
              def summary
                rich_text_summary || build_rich_text_summary
              end

              def summary?
                rich_text_summary.present?
              end
  - |2
                def summary=(body)
                  if body.present?
                    self.summary.body = body
                  else
                    if summary?
                      self.summary.body = body
                      self.summary.mark_for_destruction
                    end
                  end
                end
  app/models/article.rb:7:2:
  - |2
              def content
                rich_text_content || build_rich_text_content
              end

              def content?
                rich_text_content.present?
              end
  - |2
                def content=(body)
                  self.content.body = body
                end
  app/models/example60.rb:9:2:
  - source: def stamp(...);  _ = example60_printer;  _.stamp(...);rescue NoMethodError
      => e;  if _.nil? && e.name == :stamp;    raise ::ActiveSupport::DelegationError.nil_target(:stamp,
      :'example60_printer');  else;    raise;  end;end
    target: "::Example60"
  app/models/example60/labels.rb:17:2:
  - source: def human_name(...);  (self.class).human_name(...);end
    target: "::Example60::Labels"
  app/models/example71.rb:108:4:
  - def from_mixin; :mixed; end
  app/models/example71.rb:50:4:
  - def from_self; :self; end
  app/models/example71.rb:51:4:
  - source: def from_constant; :constant; end
    target: "::Example71::Target"
  app/models/example71.rb:52:4:
  - source: def from_local; :local; end
    target: "::Example71::Target"
  app/models/example71.rb:53:4:
  - source: def from_fix_string; 0; end
    target: "::Example71::Target"
  app/models/example71.rb:76:4:
  - def from_inherited; :inherited; end
  app/models/example75.rb:80:4:
  - def email;  user.email;end
  app/models/example75.rb:85:4:
  - def human_name;  self.class.human_name;end
  app/models/example76.rb:76:4:
  - def human_name(index);  self.class.human_name(index);end
  app/models/example76.rb:80:4:
  -
  app/models/example77.rb:54:4:
  - source: def human_name(index);  self.class.human_name(index);end
    target: "::Example77::Peel"
  app/models/example77.rb:62:4:
  - source: def nick(name);  self.class.nick(name);end
    target: "::Example77::Rind"
  app/models/example79.rb:29:4:
  - def nick;end
  -
  app/models/example80.rb:58:4:
  - source: def email;  user.email;end;def name;  user.name;end
    target: "::Example80::Account"
  app/models/example80.rb:64:4:
  - source: def name;  _ = buyer;  _&.name;end
    target: "::Example80::Order"
  app/models/example81.rb:29:2:
  - source: def full_name(...);  _ = author;  _.full_name(...);rescue NoMethodError
      => e;  if _.nil? && e.name == :full_name;    raise ::ActiveSupport::DelegationError.nil_target(:full_name,
      :'author');  else;    raise;  end;end
    target: "::Example81"
  app/models/example81.rb:30:2:
  - source: def owner_full_name(...);  _ = @owner;  _.full_name(...);rescue NoMethodError
      => e;  if _.nil? && e.name == :full_name;    raise ::ActiveSupport::DelegationError.nil_target(:owner_full_name,
      :'@owner');  else;    raise;  end;end
    target: "::Example81"
  app/models/example81.rb:31:2:
  - source: def fetch(key, &);  _ = ::Example81::Shelf;  _.fetch(key, &);rescue NoMethodError
      => e;  if _.nil? && e.name == :fetch;    raise ::ActiveSupport::DelegationError.nil_target(:fetch,
      :'::Example81::Shelf');  else;    raise;  end;end
    target: "::Example81"
  app/models/example82.rb:29:2:
  - source: def owner_full_name(...);  _ = owner;  if !_.nil? || nil.respond_to?(:full_name);    _.full_name(...);  end;end
    target: "::Example82"
  app/models/example82.rb:30:2:
  - source: def author_full_name(...);  _ = author;  if !_.nil? || nil.respond_to?(:full_name);    _.full_name(...);  end;end
    target: "::Example82"
  app/models/example83.rb:53:2:
  - source: def tags; :direct; end
    target: "::Example83"
  app/models/example83.rb:54:2:
  - source: def labels; :direct; end
    target: "::Example83"
  app/models/example83.rb:55:2:
  - source: def posts; :stored; end
    target: "::Example83"
  app/models/example83.rb:56:2:
  - source: def comments; :stored; end
    target: "::Example83"
  app/models/example84.rb:42:2:
  -
  app/models/example84.rb:43:2:
  -
  app/models/example85.rb:57:2:
  -
  app/models/example85.rb:58:2:
  -
  app/models/post.rb:31:2:
  - source: def user_email(...);  _ = user;  _.email(...);rescue NoMethodError =>
      e;  if _.nil? && e.name == :email;    raise ::ActiveSupport::DelegationError.nil_target(:user_email,
      :'user');  else;    raise;  end;end
    target: "::Post"
  app/models/post.rb:32:2:
  - source: def full_name(...);  _ = user;  _.full_name(...);rescue NoMethodError
      => e;  if _.nil? && e.name == :full_name;    raise ::ActiveSupport::DelegationError.nil_target(:full_name,
      :'user');  else;    raise;  end;end
    target: "::Post"
  app/models/post.rb:33:2:
  - source: def user_created_at(...);  _ = user;  _.created_at(...);rescue NoMethodError
      => e;  if _.nil? && e.name == :created_at;    raise ::ActiveSupport::DelegationError.nil_target(:user_created_at,
      :'user');  else;    raise;  end;end
    target: "::Post"
  app/models/post.rb:34:2:
  - source: def name(...);  _ = tag;  if !_.nil? || nil.respond_to?(:name);    _.name(...);  end;end
    target: "::Post"
  app/models/post/notifiable.rb:7:4:
  - source: def user_updated_at(...);  _ = user;  _.updated_at(...);rescue NoMethodError
      => e;  if _.nil? && e.name == :updated_at;    raise ::ActiveSupport::DelegationError.nil_target(:user_updated_at,
      :'user');  else;    raise;  end;end
    target: "::Post"
