---
version: 1
methods:
  Assignment#log_post_user_name:
    requires:
    - kind: not_nil
      expr:
        kind: send
        receiver:
          kind: self
        method: post
    enforced: false
  Assignment#run_before_validation_callbacks:
    requires:
    - kind: not_nil
      expr:
        kind: send
        receiver:
          kind: self
        method: post
    enforced: false
  Column#save:
    requires:
    - kind: not_nil
      expr:
        kind: send
        receiver:
          kind: self
        method: board
  Column#set_default_user_name:
    requires:
    - kind: not_nil
      expr:
        kind: send
        receiver:
          kind: self
        method: board
  Comment#author_name:
    requires:
    - kind: not_nil
      expr:
        kind: send
        receiver:
          kind: self
        method: user
  Comment#short_body:
    requires:
    - kind: not_nil
      expr:
        kind: send
        receiver:
          kind: self
        method: body
  Post#author_name:
    requires:
    - kind: not_nil
      expr:
        kind: send
        receiver:
          kind: self
        method: user
  Post::Notifiable#notification_payload:
    requires:
    - kind: not_nil
      expr:
        kind: send
        receiver:
          kind: self
        method: user
    enforced: false
  ProfileFormatter#call_without_check:
    requires:
    - kind: not_nil
      expr:
        kind: send
        receiver:
          kind: self
        method: nickname
    enforced: false
  ProfileFormatter#format_nickname:
    requires:
    - kind: not_nil
      expr:
        kind: send
        receiver:
          kind: self
        method: nickname
    enforced: false
