---
version: 1
methods:
  EmailNotifier#notify:
    ((::User | nil), "post_notification"): '{ :body => "post_notification", :from
      => ::String, :sent_at => ::ActiveSupport::TimeWithZone, :to => (::String | nil)
      }'
  EventTracker#track_event:
    '(action: "created")': '{ :action => "created" }'
    "(action: :reported)": "{ :action => :reported }"
  Example12#show:
    "(:age)": "::Integer"
    "(:name)": "::String"
  Example19#record:
    ("denied"): '"denied"'
  Example20#record:
    ("denied"): '"denied"'
  Example4::Foo.name=:
    ("John Doe"): '"John Doe"'
  Example69::Foo#call:
    "(flag_name: false)": '"delete"'
    "(flag_name: true)": '"name_delete"'
  Example69::Foo#name_action_dynamic:
    "(flag_name: false)": '"delete"'
    "(flag_name: true)": '"name_delete"'
  Example7::Dispatcher#show:
    "(:age)": "::Integer"
    "(:name)": "::String"
  Example8#show:
    "(:age)": "::Integer"
    "(:name)": "::String"
  Example9::Dispatcher#show:
    "(:age)": "::Integer"
    "(:name)": "::String"
