---
app/controllers/concerns/filter_configuration.rb:
  modules:
  - anchor: FilterConfiguration
    annotations:
    - "# @type self: singleton(PostsController) & singleton(FilterConfiguration)"
    - "# @type instance: PostsController & FilterConfiguration"
app/helpers/application_helper.rb:
  modules:
  - anchor: ApplicationHelper
    annotations:
    - "# @type instance: ApplicationController & ApplicationHelper"
app/helpers/posts_helper.rb:
  modules:
  - anchor: PostsHelper
    annotations:
    - "# @type instance: (ERBPostsEdit & PostsHelper) | (ERBPostsIndex & PostsHelper)
      | (ERBPostsNew & PostsHelper) | (ERBPostsShow & PostsHelper)"
app/models/concerns/test/filtrable.rb:
  modules:
  - anchor: Filtrable
    annotations:
    - "# @type self: singleton(Post) & singleton(Test::Filtrable)"
    - "# @type instance: Post & Test::Filtrable"
app/models/eval_reopen/slots.rb:
  modules:
  - anchor: Slots
    annotations:
    - "# @type instance: EvalReopen & EvalReopen::Slots"
app/models/eventable.rb:
  modules:
  - anchor: Eventable
    annotations:
    - "# @type self: singleton(Widget) & singleton(Eventable)"
    - "# @type instance: Widget & Eventable"
app/models/example13.rb:
  modules:
  - anchor: GeneratedAttributes
    annotations:
    - "# @type instance: Example13::Registry & Example13::Registry::GeneratedAttributes"
app/models/example22.rb:
  modules:
  - anchor: Foo
    annotations:
    - "# @type instance: singleton(Example22::Bar)"
app/models/example23.rb:
  modules:
  - anchor: Foo
    annotations:
    - "# @type instance: (singleton(Example23::Bar)) | (singleton(Example23::BarOther))
      | (singleton(Example23::Baz))"
    defs:
      bazinga: singleton(Example23::Bar) | singleton(Example23::BarOther)
app/models/example24.rb:
  modules:
  - anchor: Foo
    annotations:
    - "# @type instance: (singleton(Example24::Bar)) | (singleton(Example24::BarOther))
      | (singleton(Example24::Baz))"
    defs:
      bazinga: singleton(Example24::Bar) | singleton(Example24::BarOther)
app/models/example25.rb:
  modules:
  - anchor: Foo
    annotations:
    - "# @type instance: (singleton(Example25::Bar)) | (singleton(Example25::BarOther))
      | (singleton(Example25::Baz)) | (singleton(Example25::BazOther))"
    defs:
      bazinga: singleton(Example25::Bar) | singleton(Example25::BarOther)
    paths:
      bazinga:
      - when:
          module_included: singleton(Example25::Baz)
        self: singleton(Example25::Bar)
      - when:
          module_included: singleton(Example25::BazOther)
        self: singleton(Example25::BarOther)
app/models/example26.rb:
  modules:
  - anchor: Foo
    annotations:
    - "# @type instance: (singleton(Example26::Bar)) | (singleton(Example26::BarOther))
      | (singleton(Example26::Baz)) | (singleton(Example26::BazOther))"
    defs:
      bazinga: singleton(Example26::Bar) | singleton(Example26::BarOther)
    paths:
      bazinga:
      - when:
          module_included: singleton(Example26::Baz)
        self: singleton(Example26::Bar)
      - when:
          module_included: singleton(Example26::BazOther)
        self: singleton(Example26::BarOther)
app/models/example27.rb:
  modules:
  - anchor: Foo
    annotations:
    - "# @type instance: (singleton(Example27::Bar)) | (singleton(Example27::Baz))"
    defs:
      bazinga: singleton(Example27::Bar)
app/models/example28.rb:
  modules:
  - anchor: Foo
    annotations:
    - "# @type instance: (singleton(Example28::Bar)) | (singleton(Example28::Baz))"
    defs:
      bazinga: singleton(Example28::Bar)
  blocks:
  - call: bazingado
    in: "::Example28::Baz"
    implements: "::Example28::Bar"
app/models/example29.rb:
  modules:
  - anchor: Foo
    annotations:
    - "# @type instance: (singleton(Example29::Bar)) | (singleton(Example29::BarOther))
      | (singleton(Example29::Baz)) | (singleton(Example29::BazOther))"
    defs:
      bazinga: singleton(Example29::Bar) | singleton(Example29::BarOther)
    paths:
      bazinga:
      - when:
          module_included: singleton(Example29::Baz)
        self: singleton(Example29::Bar)
      - when:
          module_included: singleton(Example29::BazOther)
        self: singleton(Example29::BarOther)
  blocks:
  - call: bazingado
    in: "::Example29::Baz"
    implements: "::Example29::Bar"
  - call: bazingado
    in: "::Example29::BazOther"
    implements: "::Example29::BarOther"
app/models/example3.rb:
  modules:
  - anchor: GeneratedAttributes
    annotations:
    - "# @type instance: Example3::Foo & Example3::Foo::GeneratedAttributes"
app/models/example31.rb:
  modules:
  - anchor: Age
    annotations:
    - "# @type instance: Example31::Bar & Example31::Age"
  - anchor: Foo
    annotations:
    - "# @type instance: (singleton(Example31::Bar)) | (singleton(Example31::Baz))"
    defs:
      bazinga: singleton(Example31::Bar)
  blocks:
  - call: bazingado
    in: "::Example31::Baz"
    implements: "::Example31::Bar"
app/models/example32.rb:
  modules:
  - anchor: Foo
    annotations:
    - "# @type instance: (singleton(Example32::Bar)) | (singleton(Example32::Baz))"
    defs:
      bazinga: singleton(Example32::Bar)
  blocks:
  - call: bazingado
    in: "::Example32::Baz"
    implements: "::Example32::Bar"
app/models/example33.rb:
  modules:
  - anchor: Foo
    annotations:
    - "# @type instance: (singleton(Example33::Bar)) | (singleton(Example33::BarOther))
      | (singleton(Example33::Baz)) | (singleton(Example33::BazOther))"
    defs:
      bazinga: singleton(Example33::Bar) | singleton(Example33::BarOther)
    paths:
      bazinga:
      - when:
          module_included: singleton(Example33::Baz)
        self: singleton(Example33::Bar)
      - when:
          module_included: singleton(Example33::BazOther)
        self: singleton(Example33::BarOther)
  blocks:
  - call: bazingado
    in: "::Example33::Baz"
    implements: "::Example33::Bar"
  - call: bazingado
    in: "::Example33::BazOther"
    implements: "::Example33::BarOther"
app/models/example34.rb:
  modules:
  - anchor: Baz
    annotations:
    - "# @type instance: Example34::Bar & Example34::Baz"
  - anchor: Foo
    annotations:
    - "# @type instance: (singleton(Example34::Bar)) | (singleton(Example34::Baz))"
  blocks:
  - call: included
    in: "::Example34::Baz"
    implements: "::Example34::Bar"
app/models/example35.rb:
  blocks:
  - call: bazingado
    in: "::Example35::Baz"
    implements: "::Example35::Bar"
app/models/example36.rb:
  blocks:
  - call: bazingado
    in: "::Example36::Baz"
    implements: "::Example36::Bar"
app/models/example37.rb:
  modules:
  - anchor: Foo
    annotations:
    - "# @type instance: (singleton(Example37::Bar)) | (singleton(Example37::Baz))"
    defs:
      bazinga: singleton(Example37::Bar)
  blocks:
  - call: bazingado
    in: "::Example37::Baz"
    implements: "::Example37::Bar"
app/models/example38.rb:
  modules:
  - anchor: Foo
    annotations:
    - "# @type instance: (singleton(Example38::Bar)) | (singleton(Example38::Baz))
      | (singleton(Example38::BazOther))"
    defs:
      bazinga: singleton(Example38::Bar)
  blocks:
  - call: bazingado
    in: "::Example38::Baz"
    implements: "::Example38::Bar"
  - call: bazingado
    in: "::Example38::BazOther"
    implements: "::Example38::Bar"
app/models/example39.rb:
  modules:
  - anchor: Foo
    annotations:
    - "# @type instance: (singleton(Example39::Bar)) | (singleton(Example39::Baz))"
    defs:
      bananed: singleton(Example39::Baz)
  blocks:
  - call: bananed
    in: "::Example39::Baz"
    implements: "::Example39::Bar"
app/models/example40.rb:
  modules:
  - anchor: Foo
    annotations:
    - "# @type instance: (singleton(Example40::Bar)) | (singleton(Example40::Baz))
      | (singleton(Example40::BazOther))"
    defs:
      bazinga: singleton(Example40::Bar)
  blocks:
  - call: bazingado
    in: "::Example40::Baz"
    implements: "::Example40::Bar"
  - call: bazingado
    in: "::Example40::BazOther"
    implements: "::Example40::Bar"
app/models/example41.rb:
  modules:
  - anchor: Baz
    annotations:
    - "# @type instance: Example41::Bar & Example41::Baz"
  - anchor: Foo
    annotations:
    - "# @type instance: (singleton(Example41::Bar)) | (singleton(Example41::Baz))"
  blocks:
  - call: included
    in: "::Example41::Baz"
    implements: "::Example41::Bar"
app/models/example42.rb:
  modules:
  - anchor: Foo
    annotations:
    - "# @type instance: (singleton(Example42::Bar)) | (singleton(Example42::BarOther))
      | (singleton(Example42::Baz))"
    defs:
      bazinga: singleton(Example42::Bar) | singleton(Example42::BarOther)
  blocks:
  - call: bazingado
    in: "::Example42::Baz"
    implements:
    - "::Example42::Bar"
    - "::Example42::BarOther"
app/models/example43.rb:
  modules:
  - anchor: Foo
    annotations:
    - "# @type instance: (singleton(Example43::Bar)) | (singleton(Example43::BarOther))
      | (singleton(Example43::BarOther2)) | (singleton(Example43::Baz)) | (singleton(Example43::BazOther))"
    defs:
      bazinga: singleton(Example43::Bar) | singleton(Example43::BarOther) | singleton(Example43::BarOther2)
  blocks:
  - call: bazingado
    in: "::Example43::Baz"
    implements:
    - "::Example43::Bar"
    - "::Example43::BarOther"
    - "::Example43::BarOther2"
  - call: bazingado
    in: "::Example43::BazOther"
    implements: "::Example43::BarOther2"
app/models/example44.rb:
  modules:
  - anchor: Baz
    annotations:
    - "# @type instance: (Example44::Bar & Example44::Baz) | (Example44::BarOther
      & Example44::Baz)"
  - anchor: Foo
    annotations:
    - "# @type instance: (singleton(Example44::Bar)) | (singleton(Example44::BarOther))
      | (singleton(Example44::Baz))"
  blocks:
  - call: included
    in: "::Example44::Baz"
    implements:
    - "::Example44::Bar"
    - "::Example44::BarOther"
app/models/example45.rb:
  modules:
  - anchor: Baz
    annotations:
    - "# @type instance: (Example45::Bar & Example45::Baz) | (Example45::BarOther
      & Example45::Baz)"
  - anchor: Foo
    annotations:
    - "# @type instance: singleton(Example45::Baz)"
  blocks:
  - call: banana_class_method
    in: "::Example45::Baz"
    implements:
    - singleton(::Example45::Bar)
    - singleton(::Example45::BarOther)
app/models/example47.rb:
  modules:
  - anchor: BananaMethods
    annotations:
    - "# @type instance: singleton(Example47::Bar)"
  - anchor: Foo
    annotations:
    - "# @type instance: singleton(Example47::Baz)"
  blocks:
  - call: banana_class_method
    in: "::Example47::Baz"
    implements: "::Example47::Baz::BananaMethods"
app/models/example48.rb:
  modules:
  - anchor: Baz
    annotations:
    - "# @type instance: Example48::Bar & Example48::Baz"
  - anchor: Foo
    annotations:
    - "# @type instance: singleton(Example48::Baz)"
app/models/example49.rb:
  modules:
  - anchor: Baz
    annotations:
    - "# @type instance: singleton(Example49::Bar)"
app/models/example50.rb:
  modules:
  - anchor: BananaMethods
    annotations:
    - "# @type instance: singleton(Example50::Bar)"
  - anchor: Foo
    annotations:
    - "# @type instance: singleton(Example50::Baz)"
  blocks:
  - call: banana_class_method
    in: "::Example50::Baz"
    implements: "::Example50::Baz::BananaMethods"
app/models/example51.rb:
  modules:
  - anchor: Foo
    annotations:
    - "# @type instance: singleton(Example51::Baz)"
  blocks:
  - call: banana_class_method
    in: "::Example51::Baz"
    implements: "::Example51::Baz::BananaMethods"
app/models/example52.rb:
  modules:
  - anchor: Baz
    annotations:
    - "# @type instance: Example52::Bar & Example52::Baz"
  - anchor: Foo
    annotations:
    - "# @type instance: singleton(Example52::Baz)"
  blocks:
  - call: banana_class_method
    in: "::Example52::Baz"
    implements: "::Example52::Baz::BananaMethods"
app/models/example53.rb:
  modules:
  - anchor: Baz
    annotations:
    - "# @type instance: Example53::Bar & Example53::Baz"
  - anchor: Foo
    annotations:
    - "# @type instance: singleton(Example53::Baz)"
  blocks:
  - call: banana_class_method
    in: "::Example53::Baz"
    implements: "::Example53::Baz::BananaMethods"
app/models/included_hook/home_made.rb:
  modules:
  - anchor: HomeMade
    annotations:
    - "# @type instance: singleton(IncludedHook::Homespun)"
app/models/included_hook/shared.rb:
  modules:
  - anchor: Shared
    annotations:
    - "# @type instance: (IncludedHookFirst & IncludedHook::Shared) | (IncludedHookSecond
      & IncludedHook::Shared)"
app/models/included_hook/slots.rb:
  modules:
  - anchor: Slots
    annotations:
    - "# @type instance: IncludedHook & IncludedHook::Slots"
app/models/included_hook.rb:
  modules:
  - anchor: Homespun
    annotations:
    - "# @type self: singleton(IncludedHook) & singleton(IncludedHook::Homespun)"
    - "# @type instance: IncludedHook & IncludedHook::Homespun"
  - anchor: Hookable
    annotations:
    - "# @type self: singleton(IncludedHook) & singleton(IncludedHook::Hookable)"
    - "# @type instance: IncludedHook & IncludedHook::Hookable"
  - anchor: Sugared
    annotations:
    - "# @type self: singleton(IncludedHook) & singleton(IncludedHook::Sugared)"
    - "# @type instance: IncludedHook & IncludedHook::Sugared"
  blocks:
  - call: class_eval
    in: "::IncludedHook::Hookable"
    implements: "::IncludedHook"
    method: included
  - call: included
    in: "::IncludedHook::Sugared"
    implements: "::IncludedHook"
  - call: included
    in: "::IncludedHook::Homespun"
    implements: "::IncludedHook"
app/models/post/notifiable.rb:
  modules:
  - anchor: Notifiable
    annotations:
    - "# @type self: singleton(Post) & singleton(Post::Notifiable)"
    - "# @type instance: Post & Post::Notifiable"
app/models/post/taggable.rb:
  modules:
  - anchor: Taggable
    annotations:
    - "# @type self: singleton(Post) & singleton(Post::Taggable)"
    - "# @type instance: Post & Post::Taggable"
  blocks:
  - call: class_methods
    implements: "::Post::Taggable::ClassMethods"
    self: singleton(::Post) & ::Post::Taggable::ClassMethods
app/models/user/displayable.rb:
  modules:
  - anchor: Displayable
    annotations:
    - "# @type self: singleton(User) & singleton(User::Displayable)"
    - "# @type instance: User & User::Displayable"
app/models/user/notifiable.rb:
  modules:
  - anchor: Notifiable
    annotations:
    - "# @type self: singleton(User) & singleton(User::Notifiable)"
    - "# @type instance: User & User::Notifiable"
app/models/user/recoverable.rb:
  modules:
  - anchor: Recoverable
    annotations:
    - "# @type self: singleton(User) & singleton(User::Recoverable)"
    - "# @type instance: User & User::Recoverable"
app/models/widget/closeable.rb:
  modules:
  - anchor: Closeable
    annotations:
    - "# @type self: singleton(Widget) & singleton(Widget::Closeable)"
    - "# @type instance: Widget & Widget::Closeable"
app/models/widget/publishable.rb:
  modules:
  - anchor: Publishable
    annotations:
    - "# @type self: singleton(Widget) & singleton(Widget::Publishable)"
    - "# @type instance: Widget & Widget::Publishable"
sig/generated/steep_ar_runtime/active_support/concern.rb:
  modules:
  - anchor: Concern
    annotations:
    - "# @type instance: (singleton(Eventable)) | (singleton(FilterConfiguration))
      | (singleton(IncludedHook::Sugared)) | (singleton(Post::Notifiable)) | (singleton(Post::Taggable))
      | (singleton(Test::Filtrable)) | (singleton(User::Displayable)) | (singleton(User::Notifiable))
      | (singleton(User::Recoverable)) | (singleton(Widget::Closeable)) | (singleton(Widget::Publishable))"
sig/generated/steep_ar_runtime/notification/generated_store_accessors.rb:
  modules:
  - anchor: GeneratedStoreAccessors
    annotations:
    - "# @type instance: Notification & Notification::GeneratedStoreAccessors"
sig/generated/steep_ar_runtime/user/generated_store_accessors.rb:
  modules:
  - anchor: GeneratedStoreAccessors
    annotations:
    - "# @type instance: User & User::GeneratedStoreAccessors"
sig/generated/steep_controller_runtime/action_controller/metal/http_authentication.rb:
  modules:
  - anchor: ControllerMethods
    annotations:
    - "# @type instance: ActionController::Base & ActionController::HttpAuthentication::Token::ControllerMethods"
sig/generated/steep_current_runtime/current.rb:
  modules:
  - anchor: GeneratedAttributeMethods
    annotations:
    - "# @type instance: Current & Current::GeneratedAttributeMethods"
sig/generated/steep_devise_runtime/devise_scoped_helpers.rb:
  modules:
  - anchor: DeviseScopedHelpers
    annotations:
    - "# @type instance: ActionController::Base & DeviseScopedHelpers"
