---
version: 1
postconditions:
- class: Post_Assignment::ActiveRecord_Associations_CollectionProxy
  method: build
  unconditional:
    returns:
      establishes:
      - post
- class: Posts::AssignmentsController
  method: create
  unconditional:
    ivars:
      "@assignment": "::Assignment"
    self: "::Posts::AssignmentsController & ::Posts::AssignmentsController::AfterCreate"
- class: Posts::AssignmentsController
  method: set_post
  unconditional:
    ivars:
      "@post": "(::Post & ::Post::Validated)"
    self: "::Posts::AssignmentsController & ::Posts::AssignmentsController::AfterSetPost"
- class: PostsController
  method: create
  unconditional:
    ivars:
      "@post": "::Post"
    self: "::PostsController & ::PostsController::AfterCreate"
- class: PostsController
  method: index
  unconditional:
    ivars:
      "@posts": "::Post::ActiveRecord_Relation"
    self: "::PostsController & ::PostsController::AfterIndex"
- class: PostsController
  method: new
  unconditional:
    ivars:
      "@post": "::Post"
    self: "::PostsController & ::PostsController::AfterNew"
- class: PostsController
  method: set_post
  unconditional:
    ivars:
      "@post": "(::Post & ::Post::Validated)"
    self: "::PostsController & ::PostsController::AfterSetPost"
- class: PostsController
  method: show
  unconditional:
    ivars:
      "@comments": "::Comment::ActiveRecord_Relation"
    self: "::PostsController & ::PostsController::AfterShow"
- class: Users::AvatarsController
  method: set_user
  unconditional:
    ivars:
      "@user": "(::User & ::User::Validated)"
    self: "::Users::AvatarsController & ::Users::AvatarsController::AfterSetUser"
- class: UsersController
  method: index
  unconditional:
    ivars:
      "@users": "::User::ActiveRecord_Relation"
    self: "::UsersController & ::UsersController::AfterIndex"
- class: UsersController
  method: show
  unconditional:
    ivars:
      "@posts": "::User_Post::ActiveRecord_Associations_CollectionProxy"
      "@user": "(::User & ::User::Validated)"
    self: "::UsersController & ::UsersController::AfterShow"
