---
app/controllers/concerns/filter_configuration.rb:
  modules:
  - anchor: FilterConfiguration
    annotations:
    - "# @type self: singleton(PostsController) & singleton(FilterConfiguration)"
    - "# @type instance: PostsController & FilterConfiguration"
app/helpers/application_helper.rb:
  modules:
  - anchor: ApplicationHelper
    annotations:
    - "# @type instance: ApplicationController & ApplicationHelper"
app/helpers/posts_helper.rb:
  modules:
  - anchor: PostsHelper
    annotations:
    - "# @type instance: (ERBPostsEdit & PostsHelper) | (ERBPostsIndex & PostsHelper)
      | (ERBPostsNew & PostsHelper) | (ERBPostsShow & PostsHelper)"
app/models/concerns/test/filtrable.rb:
  modules:
  - anchor: Filtrable
    annotations:
    - "# @type self: singleton(Post) & singleton(Test::Filtrable)"
    - "# @type instance: Post & Test::Filtrable"
app/models/eval_reopen/slots.rb:
  modules:
  - anchor: Slots
    annotations:
    - "# @type instance: EvalReopen & EvalReopen::Slots"
app/models/eventable.rb:
  modules:
  - anchor: Eventable
    annotations:
    - "# @type self: singleton(Widget) & singleton(Eventable)"
    - "# @type instance: Widget & Eventable"
app/models/example13.rb:
  modules:
  - anchor: GeneratedAttributes
    annotations:
    - "# @type instance: Example13::Registry & Example13::Registry::GeneratedAttributes"
app/models/example22.rb:
  modules:
  - anchor: Foo
    annotations:
    - "# @type instance: singleton(Example22::Bar)"
app/models/example23.rb:
  modules:
  - anchor: Foo
    annotations:
    - "# @type instance: (singleton(Example23::Bar)) | (singleton(Example23::BarOther))
      | (singleton(Example23::Baz))"
    defs:
      bazinga: singleton(Example23::Bar) | singleton(Example23::BarOther)
app/models/example24.rb:
  modules:
  - anchor: Foo
    annotations:
    - "# @type instance: (singleton(Example24::Bar)) | (singleton(Example24::BarOther))
      | (singleton(Example24::Baz))"
    defs:
      bazinga: singleton(Example24::Bar) | singleton(Example24::BarOther)
app/models/example25.rb:
  modules:
  - anchor: Foo
    annotations:
    - "# @type instance: (singleton(Example25::Bar)) | (singleton(Example25::BarOther))
      | (singleton(Example25::Baz)) | (singleton(Example25::BazOther))"
    defs:
      bazinga: singleton(Example25::Bar) | singleton(Example25::BarOther)
    paths:
      bazinga:
      - when:
          module_included: singleton(Example25::Baz)
        self: singleton(Example25::Bar)
      - when:
          module_included: singleton(Example25::BazOther)
        self: singleton(Example25::BarOther)
app/models/example26.rb:
  modules:
  - anchor: Foo
    annotations:
    - "# @type instance: (singleton(Example26::Bar)) | (singleton(Example26::BarOther))
      | (singleton(Example26::Baz)) | (singleton(Example26::BazOther))"
    defs:
      bazinga: singleton(Example26::Bar) | singleton(Example26::BarOther)
    paths:
      bazinga:
      - when:
          module_included: singleton(Example26::Baz)
        self: singleton(Example26::Bar)
      - when:
          module_included: singleton(Example26::BazOther)
        self: singleton(Example26::BarOther)
app/models/example27.rb:
  modules:
  - anchor: Foo
    annotations:
    - "# @type instance: (singleton(Example27::Bar)) | (singleton(Example27::Baz))"
    defs:
      bazinga: singleton(Example27::Bar)
app/models/example28.rb:
  modules:
  - anchor: Foo
    annotations:
    - "# @type instance: (singleton(Example28::Bar)) | (singleton(Example28::Baz))"
    defs:
      bazinga: singleton(Example28::Bar)
  blocks:
  - call: bazingado
    in: "::Example28::Baz"
    implements: "::Example28::Bar"
app/models/example29.rb:
  modules:
  - anchor: Foo
    annotations:
    - "# @type instance: (singleton(Example29::Bar)) | (singleton(Example29::BarOther))
      | (singleton(Example29::Baz)) | (singleton(Example29::BazOther))"
    defs:
      bazinga: singleton(Example29::Bar) | singleton(Example29::BarOther)
    paths:
      bazinga:
      - when:
          module_included: singleton(Example29::Baz)
        self: singleton(Example29::Bar)
      - when:
          module_included: singleton(Example29::BazOther)
        self: singleton(Example29::BarOther)
  blocks:
  - call: bazingado
    in: "::Example29::Baz"
    implements: "::Example29::Bar"
  - call: bazingado
    in: "::Example29::BazOther"
    implements: "::Example29::BarOther"
app/models/example3.rb:
  modules:
  - anchor: GeneratedAttributes
    annotations:
    - "# @type instance: Example3::Foo & Example3::Foo::GeneratedAttributes"
app/models/example31.rb:
  modules:
  - anchor: Age
    annotations:
    - "# @type instance: Example31::Bar & Example31::Age"
  - anchor: Foo
    annotations:
    - "# @type instance: (singleton(Example31::Bar)) | (singleton(Example31::Baz))"
    defs:
      bazinga: singleton(Example31::Bar)
  blocks:
  - call: bazingado
    in: "::Example31::Baz"
    implements: "::Example31::Bar"
app/models/example32.rb:
  modules:
  - anchor: Foo
    annotations:
    - "# @type instance: (singleton(Example32::Bar)) | (singleton(Example32::Baz))"
    defs:
      bazinga: singleton(Example32::Bar)
  blocks:
  - call: bazingado
    in: "::Example32::Baz"
    implements: "::Example32::Bar"
app/models/example33.rb:
  modules:
  - anchor: Foo
    annotations:
    - "# @type instance: (singleton(Example33::Bar)) | (singleton(Example33::BarOther))
      | (singleton(Example33::Baz)) | (singleton(Example33::BazOther))"
    defs:
      bazinga: singleton(Example33::Bar) | singleton(Example33::BarOther)
    paths:
      bazinga:
      - when:
          module_included: singleton(Example33::Baz)
        self: singleton(Example33::Bar)
      - when:
          module_included: singleton(Example33::BazOther)
        self: singleton(Example33::BarOther)
  blocks:
  - call: bazingado
    in: "::Example33::Baz"
    implements: "::Example33::Bar"
  - call: bazingado
    in: "::Example33::BazOther"
    implements: "::Example33::BarOther"
app/models/example34.rb:
  modules:
  - anchor: Baz
    annotations:
    - "# @type instance: Example34::Bar & Example34::Baz"
  - anchor: Foo
    annotations:
    - "# @type instance: (singleton(Example34::Bar)) | (singleton(Example34::Baz))"
    defs:
      include: singleton(Example34::Bar)
      included: singleton(Example34::Baz)
app/models/example35.rb:
  blocks:
  - call: bazingado
    in: "::Example35::Baz"
    implements: "::Example35::Bar"
app/models/example36.rb:
  blocks:
  - call: bazingado
    in: "::Example36::Baz"
    implements: "::Example36::Bar"
app/models/example37.rb:
  modules:
  - anchor: Foo
    annotations:
    - "# @type instance: (singleton(Example37::Bar)) | (singleton(Example37::Baz))"
    defs:
      bazinga: singleton(Example37::Bar)
  blocks:
  - call: bazingado
    in: "::Example37::Baz"
    implements: "::Example37::Bar"
app/models/included_hook/home_made.rb:
  modules:
  - anchor: HomeMade
    annotations:
    - "# @type instance: singleton(IncludedHook::Homespun)"
app/models/included_hook/shared.rb:
  modules:
  - anchor: Shared
    annotations:
    - "# @type instance: (IncludedHookFirst & IncludedHook::Shared) | (IncludedHookSecond
      & IncludedHook::Shared)"
app/models/included_hook/slots.rb:
  modules:
  - anchor: Slots
    annotations:
    - "# @type instance: IncludedHook & IncludedHook::Slots"
app/models/included_hook.rb:
  modules:
  - anchor: Homespun
    annotations:
    - "# @type self: singleton(IncludedHook) & singleton(IncludedHook::Homespun)"
    - "# @type instance: IncludedHook & IncludedHook::Homespun"
  - anchor: Hookable
    annotations:
    - "# @type self: singleton(IncludedHook) & singleton(IncludedHook::Hookable)"
    - "# @type instance: IncludedHook & IncludedHook::Hookable"
  - anchor: Sugared
    annotations:
    - "# @type self: singleton(IncludedHook) & singleton(IncludedHook::Sugared)"
    - "# @type instance: IncludedHook & IncludedHook::Sugared"
app/models/post/notifiable.rb:
  modules:
  - anchor: Notifiable
    annotations:
    - "# @type self: singleton(Post) & singleton(Post::Notifiable)"
    - "# @type instance: Post & Post::Notifiable"
app/models/post/taggable.rb:
  modules:
  - anchor: Taggable
    annotations:
    - "# @type self: singleton(Post) & singleton(Post::Taggable)"
    - "# @type instance: Post & Post::Taggable"
  blocks:
  - call: class_methods
    implements: "::Post::Taggable::ClassMethods"
    self: singleton(::Post) & ::Post::Taggable::ClassMethods
app/models/user/displayable.rb:
  modules:
  - anchor: Displayable
    annotations:
    - "# @type self: singleton(User) & singleton(User::Displayable)"
    - "# @type instance: User & User::Displayable"
app/models/user/notifiable.rb:
  modules:
  - anchor: Notifiable
    annotations:
    - "# @type self: singleton(User) & singleton(User::Notifiable)"
    - "# @type instance: User & User::Notifiable"
app/models/user/recoverable.rb:
  modules:
  - anchor: Recoverable
    annotations:
    - "# @type self: singleton(User) & singleton(User::Recoverable)"
    - "# @type instance: User & User::Recoverable"
app/models/widget/closeable.rb:
  modules:
  - anchor: Closeable
    annotations:
    - "# @type self: singleton(Widget) & singleton(Widget::Closeable)"
    - "# @type instance: Widget & Widget::Closeable"
app/models/widget/publishable.rb:
  modules:
  - anchor: Publishable
    annotations:
    - "# @type self: singleton(Widget) & singleton(Widget::Publishable)"
    - "# @type instance: Widget & Widget::Publishable"
sig/generated/steep_ar_runtime/notification/generated_store_accessors.rb:
  modules:
  - anchor: GeneratedStoreAccessors
    annotations:
    - "# @type instance: Notification & Notification::GeneratedStoreAccessors"
sig/generated/steep_ar_runtime/user/generated_store_accessors.rb:
  modules:
  - anchor: GeneratedStoreAccessors
    annotations:
    - "# @type instance: User & User::GeneratedStoreAccessors"
sig/generated/steep_controller_runtime/action_controller/metal/http_authentication.rb:
  modules:
  - anchor: ControllerMethods
    annotations:
    - "# @type instance: ActionController::Base & ActionController::HttpAuthentication::Token::ControllerMethods"
sig/generated/steep_current_runtime/current.rb:
  modules:
  - anchor: GeneratedAttributeMethods
    annotations:
    - "# @type instance: Current & Current::GeneratedAttributeMethods"
sig/generated/steep_devise_runtime/devise_scoped_helpers.rb:
  modules:
  - anchor: DeviseScopedHelpers
    annotations:
    - "# @type instance: ActionController::Base & DeviseScopedHelpers"
