---
version: 1
methods:
  Assignment#log_post_user_name:
    requires:
    - kind: not_nil
      expr:
        kind: send
        receiver:
          kind: self
        method: post
    - kind: not_nil
      expr:
        kind: send
        receiver:
          kind: self
        method: post
        chain:
        - user
    - kind: not_nil
      expr:
        kind: send
        receiver:
          kind: self
        method: post
        chain:
        - user
        - name
  Assignment#run_before_validation_callbacks:
    requires:
    - kind: not_nil
      expr:
        kind: send
        receiver:
          kind: self
        method: post
    - kind: not_nil
      expr:
        kind: send
        receiver:
          kind: self
        method: post
        chain:
        - user
    - kind: not_nil
      expr:
        kind: send
        receiver:
          kind: self
        method: post
        chain:
        - user
        - name
  Assignment#run_belongs_to_default_callbacks:
    requires:
    - kind: not_nil
      expr:
        kind: send
        receiver:
          kind: self
        method: post
  Assignment#run_belongs_to_default_owner:
    requires:
    - kind: not_nil
      expr:
        kind: send
        receiver:
          kind: self
        method: post
  Assignment#save:
    requires:
    - kind: not_nil
      expr:
        kind: send
        receiver:
          kind: self
        method: post
    - kind: not_nil
      expr:
        kind: send
        receiver:
          kind: self
        method: post
        chain:
        - user
    - kind: not_nil
      expr:
        kind: send
        receiver:
          kind: self
        method: post
        chain:
        - user
        - name
  Column#save:
    requires:
    - kind: not_nil
      expr:
        kind: send
        receiver:
          kind: self
        method: board
  Column#set_default_user_name:
    requires:
    - kind: not_nil
      expr:
        kind: send
        receiver:
          kind: self
        method: board
  Comment#author_name:
    requires:
    - kind: not_nil
      expr:
        kind: send
        receiver:
          kind: self
        method: user
  Comment#short_body:
    requires:
    - kind: not_nil
      expr:
        kind: send
        receiver:
          kind: self
        method: body
  Post#author_name:
    requires:
    - kind: not_nil
      expr:
        kind: send
        receiver:
          kind: self
        method: user
  Post::Notifiable#notification_payload:
    requires:
    - kind: not_nil
      expr:
        kind: send
        receiver:
          kind: self
        method: user
    enforced: false
  Post_Assignment::ActiveRecord_Associations_CollectionProxy#create:
    requires:
    - kind: not_nil
      expr:
        kind: send
        receiver:
          kind: self
        method: owner
        chain:
        - user
    - kind: not_nil
      expr:
        kind: send
        receiver:
          kind: self
        method: owner
        chain:
        - user
        - name
  Post_Assignment::ActiveRecord_Associations_CollectionProxy#create!:
    requires:
    - kind: not_nil
      expr:
        kind: send
        receiver:
          kind: self
        method: owner
        chain:
        - user
    - kind: not_nil
      expr:
        kind: send
        receiver:
          kind: self
        method: owner
        chain:
        - user
        - name
  ProfileFormatter#call_without_check:
    requires:
    - kind: not_nil
      expr:
        kind: send
        receiver:
          kind: self
        method: nickname
    enforced: false
  ProfileFormatter#format_nickname:
    requires:
    - kind: not_nil
      expr:
        kind: send
        receiver:
          kind: self
        method: nickname
    enforced: false
  TagDestroy#parse_xml:
    requires:
    - kind: not_nil
      expr:
        kind: send
        receiver:
          kind: self
        method: xml
    enforced: false
  TagDestroy#parse_xml_as_hash:
    requires:
    - kind: not_nil
      expr:
        kind: send
        receiver:
          kind: self
        method: xml
    enforced: false
  TagDestroy#parse_xml_as_hash_with_parse:
    requires:
    - kind: not_nil
      expr:
        kind: send
        receiver:
          kind: self
        method: xml
    enforced: false
  TagDestroy#test_array_with_array:
    requires:
    - kind: not_nil
      expr:
        kind: send
        receiver:
          kind: self
        method: xml
    enforced: false
  TagDestroy#test_array_with_array_with_elements_untyped:
    requires:
    - kind: not_nil
      expr:
        kind: send
        receiver:
          kind: self
        method: xml
    enforced: false
  TagDestroy#user_name:
    requires:
    - kind: not_nil
      expr:
        kind: send
        receiver:
          kind: self
        method: user
    enforced: false
  TagDestroy#verify_multiples_returns_with_void:
    requires:
    - kind: not_nil
      expr:
        kind: send
        receiver:
          kind: self
        method: user
    enforced: false
  Test::Filtrable#filtrable?:
    requires:
    - kind: not_nil
      expr:
        kind: send
        receiver:
          kind: self
        method: created_at
    - kind: not_nil
      expr:
        kind: send
        receiver:
          kind: self
        method: updated_at
    enforced: false
  Test::Filtrable#teste:
    requires:
    - kind: not_nil
      expr:
        kind: send
        receiver:
          kind: self
        method: asdasd
    enforced: false
