# frozen_string_literal: true
#
# GENERATED by RbsInfer::Extensions::Rails::ActiveRecord::RuntimeGenerator.
# Regenerated on every run; do not edit.

module User::GeneratedStoreAccessors
  def digest_hour
    @__store_preferences_digest_hour
  end

  def digest_hour=(value)
    @__store_preferences_digest_hour = value
  end
end
