class ProfileFormatter
  attr_reader nickname: (String | nil)

  def initialize: (nickname: (String | nil)) -> void
  def call: () -> untyped
  def call_without_check: () -> untyped

  private

  def format_nickname: () -> untyped
end
