# frozen_string_literal: true
#
# GENERATED by RbsInfer::Extensions::Rails::ActiveRecord::RuntimeGenerator.
# Regenerated on every run; do not edit.

class Assignment
  def save(**)
    run_before_validation_callbacks
    true
  end

  def run_before_validation_callbacks
    log_post_user_name
  end
end
