class Assignment
  def save: (**untyped) -> bool
  def run_before_validation_callbacks: () -> User?
  def run_belongs_to_default_callbacks: () -> User?
  def run_belongs_to_default_owner: () -> User?
end
