# frozen_string_literal: true
#
# GENERATED by RbsInfer::Extensions::Rails::ActiveRecord::RuntimeGenerator.
# Regenerated on every run; do not edit.

class Post
  def assignments
    Post_Assignment::ActiveRecord_Associations_CollectionProxy.new(Assignment, self)
  end
end
