# frozen_string_literal: true
#
# GENERATED by RbsInfer::Extensions::Rails::ActiveRecord::RuntimeGenerator.
# Regenerated on every run; do not edit.

class Post_Tag::ActiveRecord_Associations_CollectionProxy
  def initialize(klass, owner)
    @owner = owner
  end

  def owner
    @owner
  end
end
