# frozen_string_literal: true
#
# GENERATED by RbsInfer::Extensions::Rails::ActiveRecord::RuntimeGenerator.
# Regenerated on every run; do not edit.

class Tag
  def post_tags
    Tag_PostTag::ActiveRecord_Associations_CollectionProxy.new(PostTag, self)
  end

  def posts
    Tag_Post::ActiveRecord_Associations_CollectionProxy.new(Post, self)
  end
end
