# frozen_string_literal: true
#
# GENERATED by RbsInfer::Extensions::Rails::ActiveRecord::RuntimeGenerator.
# Regenerated on every run; do not edit.

class User_Post::ActiveRecord_Associations_CollectionProxy
  def initialize(klass, owner)
    @owner = owner
  end

  def owner
    @owner
  end

  def build(*)
    record = Post.new
    record.user = owner
    record
  end

  def create(*)
    record = build
    record.save
    record
  end

  def create!(*)
    create or raise ActiveRecord::RecordInvalid
  end
end
